apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fi-fhir

commonLabels:
  app.kubernetes.io/name: fi-fhir
  app.kubernetes.io/managed-by: kustomize

resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pdb.yaml

# Images can be overridden per environment
images:
  - name: fi-fhir
    newName: fi-fhir
    newTag: latest
