apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: fi-fhir
  namespace: fi-fhir
  labels:
    app.kubernetes.io/name: fi-fhir
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fi-fhir
