apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fi-fhir.fullname" . }}
  labels:
    {{- include "fi-fhir.labels" . | nindent 4 }}
data:
  workflow.yaml: |
    {{- .Values.workflowConfig | nindent 4 }}
  registry.json: |
    {{- .Values.previewRegistry | nindent 4 }}
