apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fi-fhir.fullname" . }}
  labels:
    {{- include "fi-fhir.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.config.database.enabled }}
  database-host: {{ .Values.secrets.database.host | quote }}
  database-port: {{ .Values.secrets.database.port | quote }}
  database-name: {{ .Values.secrets.database.name | quote }}
  database-username: {{ .Values.secrets.database.username | quote }}
  database-password: {{ .Values.secrets.database.password | quote }}
  {{- end }}
  {{- if .Values.config.queue.enabled }}
  queue-brokers: {{ .Values.secrets.queue.brokers | quote }}
  {{- end }}
  {{- if .Values.secrets.fhir.baseUrl }}
  fhir-base-url: {{ .Values.secrets.fhir.baseUrl | quote }}
  fhir-auth-type: {{ .Values.secrets.fhir.authType | quote }}
  {{- if eq .Values.secrets.fhir.authType "basic" }}
  fhir-username: {{ .Values.secrets.fhir.username | quote }}
  fhir-password: {{ .Values.secrets.fhir.password | quote }}
  {{- end }}
  {{- if eq .Values.secrets.fhir.authType "bearer" }}
  fhir-bearer-token: {{ .Values.secrets.fhir.bearerToken | quote }}
  {{- end }}
  {{- if eq .Values.secrets.fhir.authType "oauth2" }}
  fhir-oauth2-token-url: {{ .Values.secrets.fhir.oauth2TokenUrl | quote }}
  fhir-oauth2-client-id: {{ .Values.secrets.fhir.oauth2ClientId | quote }}
  fhir-oauth2-client-secret: {{ .Values.secrets.fhir.oauth2ClientSecret | quote }}
  {{- end }}
  {{- end }}
