// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AnalyzeQualityInput struct {
	Event     map[string]any `json:"event"`
	EventType EventType      `json:"eventType"`
}

type ApprovePendingAutorouteInput struct {
	ID          string              `json:"id"`
	Equivalence *MappingEquivalence `json:"equivalence,omitempty"`
	Comment     *string             `json:"comment,omitempty"`
}

type ApproveWorkflowVersionInput struct {
	ApprovalRequestID string  `json:"approvalRequestId"`
	ReviewedBy        *string `json:"reviewedBy,omitempty"`
	Comment           *string `json:"comment,omitempty"`
}

type ArchiveWorkflowDefinitionInput struct {
	WorkflowID string  `json:"workflowId"`
	ArchivedBy *string `json:"archivedBy,omitempty"`
}

type AssigningAuthority struct {
	Code   string  `json:"code"`
	System string  `json:"system"`
	Name   *string `json:"name,omitempty"`
}

type AssigningAuthorityInput struct {
	Code   string  `json:"code"`
	System string  `json:"system"`
	Name   *string `json:"name,omitempty"`
}

type AutorouteStep struct {
	Step       string         `json:"step"`
	Result     string         `json:"result"`
	DurationMs int            `json:"durationMs"`
	Metadata   map[string]any `json:"metadata,omitempty"`
}

type AutorouteTrace struct {
	TraceID         string          `json:"traceId"`
	Timestamp       time.Time       `json:"timestamp"`
	Steps           []AutorouteStep `json:"steps"`
	TotalDurationMs int             `json:"totalDurationMs"`
}

// One object under a batch source's input prefix or directory.
type BatchPeekObject struct {
	Path string `json:"path"`
	Size int    `json:"size"`
	// The provider's exact version: an S3 version ID, or an SFTP change stamp.
	Version string `json:"version"`
	// The provider's modification time. Advisory: never a trust input.
	ModifiedAt *time.Time `json:"modifiedAt,omitempty"`
}

type BatchPeekResult struct {
	// At most maxObjects objects, in the provider's listing order.
	Objects []BatchPeekObject `json:"objects"`
	// The samples this peek added to the session; empty without objectPath.
	Samples []SessionSample `json:"samples"`
	// The peek's audit row, finished.
	Capture  *ConnectionCapture  `json:"capture"`
	Problems []ConnectionProblem `json:"problems"`
}

type BulkApproveInput struct {
	MinConfidence *float64 `json:"minConfidence,omitempty"`
	MaxCount      *int     `json:"maxCount,omitempty"`
}

type BulkApproveResult struct {
	Approved int           `json:"approved"`
	Skipped  int           `json:"skipped"`
	Mappings []CodeMapping `json:"mappings"`
}

type ClassifyMessageInput struct {
	Data   string       `json:"data"`
	Format SourceFormat `json:"format"`
}

type CodeMapping struct {
	ID            string             `json:"id"`
	SourceSystem  string             `json:"sourceSystem"`
	SourceCode    string             `json:"sourceCode"`
	SourceDisplay *string            `json:"sourceDisplay,omitempty"`
	TargetSystem  string             `json:"targetSystem"`
	TargetCode    string             `json:"targetCode"`
	TargetDisplay *string            `json:"targetDisplay,omitempty"`
	Equivalence   MappingEquivalence `json:"equivalence"`
	Confidence    *float64           `json:"confidence,omitempty"`
	Comment       *string            `json:"comment,omitempty"`
	Origin        MappingOrigin      `json:"origin"`
	ProfileID     *string            `json:"profileId,omitempty"`
	UploadBatchID *string            `json:"uploadBatchId,omitempty"`
	CreatedAt     time.Time          `json:"createdAt"`
	CreatedBy     *string            `json:"createdBy,omitempty"`
	ApprovedAt    *time.Time         `json:"approvedAt,omitempty"`
	ApprovedBy    *string            `json:"approvedBy,omitempty"`
}

type CodeMappingConnection struct {
	Nodes      []CodeMapping `json:"nodes"`
	TotalCount int           `json:"totalCount"`
	PageInfo   *PageInfo     `json:"pageInfo"`
}

type Connection struct {
	// The connection's artifact ID; every compiled revision carries it.
	ID          string              `json:"id"`
	Direction   ConnectionDirection `json:"direction"`
	Kind        ConnectionKind      `json:"kind"`
	Name        string              `json:"name"`
	Description string              `json:"description"`
	// The kind's spec: snake_case, non-secret, and possibly incomplete (compile reports what is missing).
	Spec           map[string]any            `json:"spec"`
	SecretBindings []ConnectionSecretBinding `json:"secretBindings"`
	// Optimistic draft version, starting at 1. Every update and archive advances it; compile does not.
	Version        int                 `json:"version"`
	Archived       bool                `json:"archived"`
	LatestRevision *ConnectionRevision `json:"latestRevision,omitempty"`
	// Lifecycle definition revisions that name any revision of this connection.
	References    []ConnectionReference   `json:"references"`
	Runtime       *ConnectionRuntimeState `json:"runtime"`
	CreatedBy     *OperatorPrincipal      `json:"createdBy"`
	CreatedAt     time.Time               `json:"createdAt"`
	UpdatedBy     *OperatorPrincipal      `json:"updatedBy"`
	UpdatedReason string                  `json:"updatedReason"`
	UpdatedAt     time.Time               `json:"updatedAt"`
}

// One audited peek or stream capture.
type ConnectionCapture struct {
	ID        string `json:"id"`
	SessionID string `json:"sessionId"`
	// The runtime source ID a stream capture taps, or the peeked revision's source_id.
	SourceID string `json:"sourceId"`
	// The catalog connection a peek read; null for a stream capture, which names a runtime source.
	ConnectionID *string                 `json:"connectionId,omitempty"`
	Mode         ConnectionCaptureMode   `json:"mode"`
	Status       ConnectionCaptureStatus `json:"status"`
	// Messages that reached the session.
	Captured    int `json:"captured"`
	MaxMessages int `json:"maxMessages"`
	// When an armed capture stops by itself; a peek's own deadline.
	ExpiresAt   time.Time          `json:"expiresAt"`
	RequestedBy *OperatorPrincipal `json:"requestedBy"`
	Reason      string             `json:"reason"`
	RequestedAt time.Time          `json:"requestedAt"`
	// Null while armed.
	CompletedAt *time.Time `json:"completedAt,omitempty"`
	// Why it finished as it did: SECRET_UNRESOLVABLE (path is the spec field naming
	// the binding), SOURCE_UNAVAILABLE, OBJECT_NOT_FOUND, MESSAGE_UNREADABLE, or
	// SAMPLE_WRITE_FAILED (path is the input field, or empty). Empty when it did all
	// it was asked.
	Problems []ConnectionProblem `json:"problems"`
}

type ConnectionCommandInput struct {
	ID              string `json:"id"`
	ExpectedVersion int    `json:"expectedVersion"`
	Reason          string `json:"reason"`
}

type ConnectionCompileResult struct {
	Connection *Connection `json:"connection"`
	// Null exactly when a blocking problem was found; nothing was written then.
	Revision *ConnectionRevision `json:"revision,omitempty"`
	Problems []ConnectionProblem `json:"problems"`
}

// One field-level finding. path is JSON dot form relative to the spec
// (timeouts.read_seconds, s3.bucket, clients.allowed_cidrs[0]) or
// secret_bindings[i].<field>; empty for the document as a whole. Every code but
// UNUSED_BINDING blocks compile.
type ConnectionProblem struct {
	Code    string `json:"code"`
	Path    string `json:"path"`
	Message string `json:"message"`
}

// One lifecycle definition revision that names a revision of this connection,
// as its source or as one of its destinations.
type ConnectionReference struct {
	DefinitionID string `json:"definitionId"`
	// The referencing definition's revision ID.
	RevisionID string `json:"revisionId"`
	// The digest of this connection's revision that the definition names.
	Digest string `json:"digest"`
	// The definition revision's lifecycle state (draft ... deployed, paused, retired).
	State  string `json:"state"`
	Health string `json:"health"`
}

type ConnectionRevision struct {
	ArtifactID string `json:"artifactId"`
	// Revision IDs are 1, 2, ... per connection.
	RevisionID string              `json:"revisionId"`
	Digest     string              `json:"digest"`
	Direction  ConnectionDirection `json:"direction"`
	Kind       ConnectionKind      `json:"kind"`
	// The exact bytes serve mounts.
	RevisionJSON string `json:"revisionJson"`
	// The draft version this revision was compiled from.
	CompiledFromVersion int                `json:"compiledFromVersion"`
	CreatedBy           *OperatorPrincipal `json:"createdBy"`
	CreatedReason       string             `json:"createdReason"`
	CreatedAt           time.Time          `json:"createdAt"`
}

type ConnectionRuntimeState struct {
	// True when this replica runs a revision of this connection.
	Mounted bool `json:"mounted"`
	// mllp-listener, batch-runner, http-ingress, or delivery-registry; null when not mounted.
	Role *string `json:"role,omitempty"`
	// Which revision is mounted, and by what; null when not mounted.
	Detail *string `json:"detail,omitempty"`
	// The mounted revision's id; null when not mounted and for http-ingress,
	// which is bound by definition id rather than a mounted document.
	RevisionID *string `json:"revisionId,omitempty"`
	// The mounted revision's digest; null exactly when revisionId is.
	Digest *string `json:"digest,omitempty"`
	// Replicas with a fresh heartbeat (engineRuntime.observations, stale false)
	// that report a revision of this connection mounted. Unlike mounted, this is
	// every replica's report, not only the one that answered.
	ObservedReplicas int `json:"observedReplicas"`
	// Replicas with any fresh heartbeat; observedReplicas of totalReplicas.
	TotalReplicas int `json:"totalReplicas"`
}

// A reference to a secret: never its value.
type ConnectionSecretBinding struct {
	Name string `json:"name"`
	// env, file, vault, aws-ssm, or k8s.
	Provider string  `json:"provider"`
	Key      string  `json:"key"`
	Version  *string `json:"version,omitempty"`
}

type ConnectionSecretBindingInput struct {
	Name     string  `json:"name"`
	Provider string  `json:"provider"`
	Key      string  `json:"key"`
	Version  *string `json:"version,omitempty"`
}

type CreateConnectionInput struct {
	ID             string                         `json:"id"`
	Direction      ConnectionDirection            `json:"direction"`
	Kind           ConnectionKind                 `json:"kind"`
	Name           string                         `json:"name"`
	Description    *string                        `json:"description,omitempty"`
	Spec           map[string]any                 `json:"spec"`
	SecretBindings []ConnectionSecretBindingInput `json:"secretBindings,omitempty"`
	Reason         string                         `json:"reason"`
}

type CreateMappingInput struct {
	SourceSystem  string              `json:"sourceSystem"`
	SourceCode    string              `json:"sourceCode"`
	SourceDisplay *string             `json:"sourceDisplay,omitempty"`
	TargetSystem  string              `json:"targetSystem"`
	TargetCode    string              `json:"targetCode"`
	TargetDisplay *string             `json:"targetDisplay,omitempty"`
	Equivalence   *MappingEquivalence `json:"equivalence,omitempty"`
	Confidence    *float64            `json:"confidence,omitempty"`
	Origin        *MappingOrigin      `json:"origin,omitempty"`
	Comment       *string             `json:"comment,omitempty"`
	ProfileID     *string             `json:"profileId,omitempty"`
}

type CreateProfileInput struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type CreateWorkflowDefinitionInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	CreatedBy   *string `json:"createdBy,omitempty"`
}

type DataQualityIssue struct {
	Dimension     string  `json:"dimension"`
	Severity      string  `json:"severity"`
	Field         *string `json:"field,omitempty"`
	Description   string  `json:"description"`
	ActualValue   *string `json:"actualValue,omitempty"`
	ExpectedValue *string `json:"expectedValue,omitempty"`
}

type DataQualityScore struct {
	OverallScore     float64                 `json:"overallScore"`
	Dimensions       *QualityDimensions      `json:"dimensions"`
	Issues           []DataQualityIssue      `json:"issues"`
	Recommendations  []QualityRecommendation `json:"recommendations"`
	ProcessingTimeMs *int                    `json:"processingTimeMs,omitempty"`
	Model            *string                 `json:"model,omitempty"`
}

// One ingress or egress adapter. Every field but kind and enabled is null when
// the adapter is disabled or the field does not apply to its kind.
type EngineAdapter struct {
	// http, mllp, batch, or delivery.
	Kind                    string  `json:"kind"`
	Enabled                 bool    `json:"enabled"`
	DefinitionID            *string `json:"definitionId,omitempty"`
	IntegrationID           *string `json:"integrationId,omitempty"`
	SourceID                *string `json:"sourceId,omitempty"`
	SourceRevisionID        *string `json:"sourceRevisionId,omitempty"`
	SourceDigest            *string `json:"sourceDigest,omitempty"`
	ListenAddress           *string `json:"listenAddress,omitempty"`
	Path                    *string `json:"path,omitempty"`
	AuthMode                *string `json:"authMode,omitempty"`
	TLSMode                 *string `json:"tlsMode,omitempty"`
	Provider                *string `json:"provider,omitempty"`
	PollSeconds             *int    `json:"pollSeconds,omitempty"`
	MaxConnections          *int    `json:"maxConnections,omitempty"`
	MaxMessageBytes         *int    `json:"maxMessageBytes,omitempty"`
	MaxBodyBytes            *int    `json:"maxBodyBytes,omitempty"`
	RequireClientIdentity   *bool   `json:"requireClientIdentity,omitempty"`
	RequireWorkloadIdentity *bool   `json:"requireWorkloadIdentity,omitempty"`
	QueueDriver             *string `json:"queueDriver,omitempty"`
	MaxAttempts             *int    `json:"maxAttempts,omitempty"`
	WorkerID                *string `json:"workerId,omitempty"`
}

type EngineDestination struct {
	ArtifactID string `json:"artifactId"`
	RevisionID string `json:"revisionId"`
	Digest     string `json:"digest"`
	// kafka, https, or fhir.
	Transport string `json:"transport"`
	// production or sandbox.
	Class string `json:"class"`
	// Scheme, host, and path only; advisory, never a trust input.
	EndpointAdvisory string `json:"endpointAdvisory"`
}

type EngineDestinationIdentity struct {
	// strict or compatibility.
	Mode         string              `json:"mode"`
	Destinations []EngineDestination `json:"destinations"`
}

type EngineLedger struct {
	Name    string `json:"name"`
	Version int    `json:"version"`
}

// One replica's report of one adapter: which document it mounted, and when it
// last said so. adapter is http, mllp, batch, delivery, or
// destination:<artifact id>. artifactId, revisionId, and digest are null when the
// adapter is disabled or mounts no document of its own.
type EngineObservation struct {
	ReplicaID   string    `json:"replicaId"`
	Adapter     string    `json:"adapter"`
	ArtifactID  *string   `json:"artifactId,omitempty"`
	RevisionID  *string   `json:"revisionId,omitempty"`
	Digest      *string   `json:"digest,omitempty"`
	HeartbeatAt time.Time `json:"heartbeatAt"`
	// True when heartbeatAt is older than three report intervals.
	Stale bool `json:"stale"`
}

type EngineProperty struct {
	// The environment variable that sets it; change it in GitOps.
	Key string `json:"key"`
	// The value, the documented default, or "" when neither; set/unset when secret.
	Value  string `json:"value"`
	Secret bool   `json:"secret"`
	// env or default.
	Source string `json:"source"`
}

type EngineRegistry struct {
	IntegrationCount int                         `json:"integrationCount"`
	Integrations     []EngineRegistryIntegration `json:"integrations"`
}

type EngineRegistryIntegration struct {
	IntegrationID string `json:"integrationId"`
	DefinitionID  string `json:"definitionId"`
	RevisionID    string `json:"revisionId"`
	Digest        string `json:"digest"`
	SourceID      string `json:"sourceId"`
	Format        string `json:"format"`
}

// What this replica composed at startup: PHI-free and secret-free. Process
// properties are an allowlist of the documented serve settings; a secret one
// renders only as "set" or "unset".
type EngineRuntime struct {
	Version  string `json:"version"`
	TenantID string `json:"tenantId"`
	// hostname-pid, as the MLLP rate quota derives it.
	ReplicaID string `json:"replicaId"`
	// GraphQL authentication mode: static or oidc.
	AuthMode            string          `json:"authMode"`
	TrustedNetwork      bool            `json:"trustedNetwork"`
	AccessIdentity      bool            `json:"accessIdentity"`
	ControlPlane        bool            `json:"controlPlane"`
	IntegrationSessions bool            `json:"integrationSessions"`
	Streaming           bool            `json:"streaming"`
	RetentionPurge      bool            `json:"retentionPurge"`
	LlmConfigured       bool            `json:"llmConfigured"`
	Registry            *EngineRegistry `json:"registry"`
	// Exactly four rows, enabled or not: http, mllp, batch, delivery.
	Adapters []EngineAdapter `json:"adapters"`
	// Null when no delivery identity registry is loaded.
	DestinationIdentity *EngineDestinationIdentity `json:"destinationIdentity,omitempty"`
	// Every forward-only migration ledger and the version this binary expects.
	Ledgers    []EngineLedger   `json:"ledgers"`
	Properties []EngineProperty `json:"properties"`
	// Every replica's heartbeat rows from the connection ledger, this one's
	// included, ordered by replica and adapter. Empty when the connection catalog
	// is not configured.
	Observations []EngineObservation `json:"observations"`
}

type EventClassificationRule struct {
	MessageType string  `json:"messageType"`
	Condition   *string `json:"condition,omitempty"`
	EventType   string  `json:"eventType"`
	Priority    int     `json:"priority"`
}

type EventClassificationRuleInput struct {
	MessageType string  `json:"messageType"`
	Condition   *string `json:"condition,omitempty"`
	EventType   string  `json:"eventType"`
	Priority    int     `json:"priority"`
}

type ExplainWorkflowInput struct {
	WorkflowYaml string  `json:"workflowYaml"`
	Audience     *string `json:"audience,omitempty"`
}

type ExtractEntitiesInput struct {
	Text           string   `json:"text"`
	DocumentType   *string  `json:"documentType,omitempty"`
	PatientAge     *int     `json:"patientAge,omitempty"`
	PatientGender  *string  `json:"patientGender,omitempty"`
	MinConfidence  *float64 `json:"minConfidence,omitempty"`
	IncludeNegated *bool    `json:"includeNegated,omitempty"`
}

type ExtractedAllergy struct {
	Substance  string  `json:"substance"`
	Code       *string `json:"code,omitempty"`
	CodeSystem *string `json:"codeSystem,omitempty"`
	Severity   *string `json:"severity,omitempty"`
	Reaction   *string `json:"reaction,omitempty"`
	Confidence float64 `json:"confidence"`
	Negated    *bool   `json:"negated,omitempty"`
	TextSpan   *string `json:"textSpan,omitempty"`
}

type ExtractedCondition struct {
	Name       string  `json:"name"`
	Code       *string `json:"code,omitempty"`
	CodeSystem *string `json:"codeSystem,omitempty"`
	Confidence float64 `json:"confidence"`
	Negated    *bool   `json:"negated,omitempty"`
	TextSpan   *string `json:"textSpan,omitempty"`
	Status     *string `json:"status,omitempty"`
}

type ExtractedMedication struct {
	Name       string  `json:"name"`
	Code       *string `json:"code,omitempty"`
	CodeSystem *string `json:"codeSystem,omitempty"`
	Dose       *string `json:"dose,omitempty"`
	Route      *string `json:"route,omitempty"`
	Frequency  *string `json:"frequency,omitempty"`
	Confidence float64 `json:"confidence"`
	Negated    *bool   `json:"negated,omitempty"`
	TextSpan   *string `json:"textSpan,omitempty"`
}

type ExtractedProcedure struct {
	Name       string  `json:"name"`
	Code       *string `json:"code,omitempty"`
	CodeSystem *string `json:"codeSystem,omitempty"`
	Status     *string `json:"status,omitempty"`
	Confidence float64 `json:"confidence"`
	Negated    *bool   `json:"negated,omitempty"`
	TextSpan   *string `json:"textSpan,omitempty"`
}

type ExtractedVitalSign struct {
	Name           string  `json:"name"`
	LoincCode      *string `json:"loincCode,omitempty"`
	Value          string  `json:"value"`
	Unit           *string `json:"unit,omitempty"`
	Confidence     float64 `json:"confidence"`
	Interpretation *string `json:"interpretation,omitempty"`
	TextSpan       *string `json:"textSpan,omitempty"`
}

type ExtractionResult struct {
	Conditions        []ExtractedCondition  `json:"conditions"`
	Medications       []ExtractedMedication `json:"medications"`
	VitalSigns        []ExtractedVitalSign  `json:"vitalSigns"`
	Allergies         []ExtractedAllergy    `json:"allergies"`
	Procedures        []ExtractedProcedure  `json:"procedures"`
	OverallConfidence float64               `json:"overallConfidence"`
	ProcessingTimeMs  int                   `json:"processingTimeMs"`
	Model             *string               `json:"model,omitempty"`
}

type GenerateWorkflowInput struct {
	Description string   `json:"description"`
	EventTypes  []string `json:"eventTypes,omitempty"`
	ActionTypes []string `json:"actionTypes,omitempty"`
}

type GeneratedWorkflow struct {
	Yaml        string   `json:"yaml"`
	Explanation string   `json:"explanation"`
	Warnings    []string `json:"warnings"`
}

type HL7v2Config struct {
	DefaultVersion       string                    `json:"defaultVersion"`
	Timezone             string                    `json:"timezone"`
	Tolerance            *ToleranceConfig          `json:"tolerance,omitempty"`
	EventClassifications []EventClassificationRule `json:"eventClassifications"`
}

type HL7v2ConfigInput struct {
	DefaultVersion       *string                        `json:"defaultVersion,omitempty"`
	Timezone             *string                        `json:"timezone,omitempty"`
	Tolerance            *ToleranceConfigInput          `json:"tolerance,omitempty"`
	EventClassifications []EventClassificationRuleInput `json:"eventClassifications,omitempty"`
}

type IDPreferenceRule struct {
	Type             string  `json:"type"`
	AssignerContains *string `json:"assignerContains,omitempty"`
	Priority         int     `json:"priority"`
}

type IDPreferenceRuleInput struct {
	Type             string  `json:"type"`
	AssignerContains *string `json:"assignerContains,omitempty"`
	Priority         int     `json:"priority"`
}

type IdentifierConfig struct {
	AssigningAuthorities []AssigningAuthority         `json:"assigningAuthorities"`
	PrimaryIDPreference  []IDPreferenceRule           `json:"primaryIdPreference"`
	Validation           *ValidationSettingsConfig    `json:"validation,omitempty"`
	Normalization        *NormalizationSettingsConfig `json:"normalization,omitempty"`
}

type IdentifierConfigInput struct {
	AssigningAuthorities []AssigningAuthorityInput   `json:"assigningAuthorities,omitempty"`
	PrimaryIDPreference  []IDPreferenceRuleInput     `json:"primaryIdPreference,omitempty"`
	Validation           *ValidationSettingsInput    `json:"validation,omitempty"`
	Normalization        *NormalizationSettingsInput `json:"normalization,omitempty"`
}

type LLMCapability struct {
	Enabled             bool                   `json:"enabled"`
	Configured          bool                   `json:"configured"`
	ProviderBaseURLHost *string                `json:"providerBaseURLHost,omitempty"`
	DefaultModel        *string                `json:"defaultModel,omitempty"`
	QualityModel        *string                `json:"qualityModel,omitempty"`
	Status              string                 `json:"status"`
	Warnings            []string               `json:"warnings"`
	Features            []LLMFeatureCapability `json:"features"`
}

type ListMappingsInput struct {
	SourceSystem  *string             `json:"sourceSystem,omitempty"`
	TargetSystem  *string             `json:"targetSystem,omitempty"`
	ProfileID     *string             `json:"profileId,omitempty"`
	Origin        *MappingOrigin      `json:"origin,omitempty"`
	UploadBatchID *string             `json:"uploadBatchId,omitempty"`
	Equivalence   *MappingEquivalence `json:"equivalence,omitempty"`
	CreatedAfter  *time.Time          `json:"createdAfter,omitempty"`
	CreatedBefore *time.Time          `json:"createdBefore,omitempty"`
	First         *int                `json:"first,omitempty"`
	Offset        *int                `json:"offset,omitempty"`
}

type ListPendingAutoroutesInput struct {
	Status        *PendingAutorouteStatus `json:"status,omitempty"`
	MinConfidence *float64                `json:"minConfidence,omitempty"`
	SourceSystem  *string                 `json:"sourceSystem,omitempty"`
	TargetSystem  *string                 `json:"targetSystem,omitempty"`
	First         *int                    `json:"first,omitempty"`
	Offset        *int                    `json:"offset,omitempty"`
}

type MappingCandidate struct {
	Code        string              `json:"code"`
	Display     string              `json:"display"`
	System      string              `json:"system"`
	Confidence  float64             `json:"confidence"`
	Equivalence *MappingEquivalence `json:"equivalence,omitempty"`
	Reasoning   *string             `json:"reasoning,omitempty"`
	Score       *float64            `json:"score,omitempty"`
}

type MessageClassification struct {
	MessageType   string     `json:"messageType"`
	EventType     *EventType `json:"eventType,omitempty"`
	SuggestedTags []string   `json:"suggestedTags"`
	Confidence    float64    `json:"confidence"`
	Summary       *string    `json:"summary,omitempty"`
}

type Mutation struct {
}

type NormalizationSettingsConfig struct {
	SsnStripDashes    bool     `json:"ssnStripDashes"`
	SsnRejectPatterns []string `json:"ssnRejectPatterns"`
	PhoneNormalize    bool     `json:"phoneNormalize"`
	PhoneFormat       *string  `json:"phoneFormat,omitempty"`
}

type NormalizationSettingsInput struct {
	SsnStripDashes    *bool    `json:"ssnStripDashes,omitempty"`
	SsnRejectPatterns []string `json:"ssnRejectPatterns,omitempty"`
	PhoneNormalize    *bool    `json:"phoneNormalize,omitempty"`
	PhoneFormat       *string  `json:"phoneFormat,omitempty"`
}

// Every count of one window, read from one database snapshot.
type OperatorAdmissionStatistics struct {
	From             time.Time                `json:"from"`
	To               time.Time                `json:"to"`
	Bucket           OperatorStatisticsBucket `json:"bucket"`
	AcceptedReceipts int                      `json:"acceptedReceipts"`
	RejectedReceipts int                      `json:"rejectedReceipts"`
	CanonicalEvents  int                      `json:"canonicalEvents"`
	// Events whose payload retention replaced with a tombstone.
	PurgedEvents int `json:"purgedEvents"`
	// Events carrying a retention deadline whose payload is still intact.
	ScheduledForPurge     int                            `json:"scheduledForPurge"`
	QueuedAttempts        int                            `json:"queuedAttempts"`
	SucceededAttempts     int                            `json:"succeededAttempts"`
	FailedAttempts        int                            `json:"failedAttempts"`
	EventsByType          []OperatorKeyCount             `json:"eventsByType"`
	ReceiptsByDefinition  []OperatorDefinitionAdmissions `json:"receiptsByDefinition"`
	AttemptsByDestination []OperatorDestinationAttempts  `json:"attemptsByDestination"`
	// True when a grouped list reached 100 groups and was cut; totals never are.
	GroupsTruncated bool                             `json:"groupsTruncated"`
	Series          []OperatorStatisticsBucketCounts `json:"series"`
}

type OperatorAttemptFilter struct {
	Status                *string    `json:"status,omitempty"`
	DestinationArtifactID *string    `json:"destinationArtifactId,omitempty"`
	ReceiptID             *string    `json:"receiptId,omitempty"`
	Route                 *string    `json:"route,omitempty"`
	From                  *time.Time `json:"from,omitempty"`
	To                    *time.Time `json:"to,omitempty"`
}

type OperatorAuditConnection struct {
	Nodes    []OperatorAuditRecord `json:"nodes"`
	PageInfo *OperatorPageInfo     `json:"pageInfo"`
}

type OperatorAuditRecord struct {
	AuditID      string             `json:"auditId"`
	AttemptID    string             `json:"attemptId"`
	EventKind    string             `json:"eventKind"`
	AttemptCount int                `json:"attemptCount"`
	Principal    *OperatorPrincipal `json:"principal"`
	Reason       string             `json:"reason"`
	Detail       map[string]any     `json:"detail"`
	RecordedAt   time.Time          `json:"recordedAt"`
}

// One durable admission: a canonical event joined to its receipt.
type OperatorCanonicalEvent struct {
	EventID         string    `json:"eventId"`
	EventType       string    `json:"eventType"`
	SourceMessageID string    `json:"sourceMessageId"`
	CorrelationID   string    `json:"correlationId"`
	Classification  string    `json:"classification"`
	RecordedAt      time.Time `json:"recordedAt"`
	ReceiptID       string    `json:"receiptId"`
	// The admitting receipt's status: accepted or rejected.
	ReceiptStatus string `json:"receiptStatus"`
	// The integration definition revision the receipt recorded.
	Definition *IntegrationArtifactRevision `json:"definition"`
	// The source connection revision from the event's lineage; null without one.
	Source           *IntegrationArtifactRevision `json:"source,omitempty"`
	PayloadFields    []OperatorPayloadField       `json:"payloadFields"`
	PayloadTruncated bool                         `json:"payloadTruncated"`
	PurgeAfter       *time.Time                   `json:"purgeAfter,omitempty"`
	PurgedAt         *time.Time                   `json:"purgedAt,omitempty"`
}

type OperatorCanonicalEventConnection struct {
	Nodes    []OperatorCanonicalEvent `json:"nodes"`
	PageInfo *OperatorPageInfo        `json:"pageInfo"`
}

type OperatorCanonicalEventFilter struct {
	EventType *string `json:"eventType,omitempty"`
	// The integration definition (receipt integration revision) artifact id.
	DefinitionID *string `json:"definitionId,omitempty"`
	ReceiptID    *string `json:"receiptId,omitempty"`
	// MSH-10 for HL7v2 admissions.
	SourceMessageID *string    `json:"sourceMessageId,omitempty"`
	CorrelationID   *string    `json:"correlationId,omitempty"`
	From            *time.Time `json:"from,omitempty"`
	To              *time.Time `json:"to,omitempty"`
	// Include events whose payload retention has tombstoned. Omitted or false
	// lists only events whose payload is intact.
	IncludePurged *bool `json:"includePurged,omitempty"`
}

type OperatorCircuit struct {
	Destination         *IntegrationArtifactRevision `json:"destination"`
	State               string                       `json:"state"`
	ConsecutiveFailures int                          `json:"consecutiveFailures"`
	OpenUntil           *time.Time                   `json:"openUntil,omitempty"`
	UpdatedAt           time.Time                    `json:"updatedAt"`
}

type OperatorControlResult struct {
	Kind            string                   `json:"kind"`
	SourceAttemptID string                   `json:"sourceAttemptId"`
	ResultAttemptID string                   `json:"resultAttemptId"`
	Attempt         *OperatorDeliveryAttempt `json:"attempt"`
	Reason          string                   `json:"reason"`
	IdempotencyKey  string                   `json:"idempotencyKey"`
	Actor           *OperatorPrincipal       `json:"actor"`
}

type OperatorDeadLetter struct {
	AttemptID      string     `json:"attemptId"`
	Active         bool       `json:"active"`
	FailureCode    string     `json:"failureCode"`
	FailureDetail  string     `json:"failureDetail"`
	FailedAt       time.Time  `json:"failedAt"`
	ReplayCount    int        `json:"replayCount"`
	LastReplayedAt *time.Time `json:"lastReplayedAt,omitempty"`
	Resolution     string     `json:"resolution"`
	ResolvedAt     *time.Time `json:"resolvedAt,omitempty"`
}

type OperatorDeadLetterConnection struct {
	Nodes    []OperatorDeadLetter `json:"nodes"`
	PageInfo *OperatorPageInfo    `json:"pageInfo"`
}

type OperatorDefinitionAdmissions struct {
	DefinitionID string `json:"definitionId"`
	RevisionID   string `json:"revisionId"`
	Accepted     int    `json:"accepted"`
	Rejected     int    `json:"rejected"`
}

type OperatorDeliveryAttempt struct {
	TenantID        string                         `json:"tenantId"`
	AttemptID       string                         `json:"attemptId"`
	ParentAttemptID *string                        `json:"parentAttemptId,omitempty"`
	ReceiptID       string                         `json:"receiptId"`
	EventID         string                         `json:"eventId"`
	TraceID         string                         `json:"traceId"`
	Destination     *IntegrationPreviewDestination `json:"destination"`
	Route           string                         `json:"route"`
	Action          string                         `json:"action"`
	Status          string                         `json:"status"`
	AttemptCount    int                            `json:"attemptCount"`
	RecordedAt      time.Time                      `json:"recordedAt"`
	ScheduledAt     time.Time                      `json:"scheduledAt"`
	CompletedAt     *time.Time                     `json:"completedAt,omitempty"`
	LastErrorCode   string                         `json:"lastErrorCode"`
	LastErrorDetail string                         `json:"lastErrorDetail"`
	OutboxStatus    string                         `json:"outboxStatus"`
	Topic           string                         `json:"topic"`
	LeaseOwner      string                         `json:"leaseOwner"`
	LeaseExpiresAt  *time.Time                     `json:"leaseExpiresAt,omitempty"`
	DeadLetter      *OperatorDeadLetter            `json:"deadLetter,omitempty"`
	// Destination provenance-ledger rows for this attempt, newest first: 25 on a
	// single attempt read, 5 per attempt in a list or trace. Empty when this
	// process contacted no destination for the attempt (every kafka-class
	// delivery, and every delivery before the ledger existed).
	Deliveries []OperatorDestinationDelivery `json:"deliveries"`
}

type OperatorDeliveryAttemptConnection struct {
	Nodes    []OperatorDeliveryAttempt `json:"nodes"`
	PageInfo *OperatorPageInfo         `json:"pageInfo"`
}

type OperatorDeliveryControlInput struct {
	AttemptID string `json:"attemptId"`
	// Required operator justification recorded in the append-only audit trail.
	Reason string `json:"reason"`
	// Caller-owned key that makes a repeated control action a no-op.
	IdempotencyKey string `json:"idempotencyKey"`
}

type OperatorDeployment struct {
	DefinitionRevision  *IntegrationArtifactRevision `json:"definitionRevision"`
	State               string                       `json:"state"`
	Version             int                          `json:"version"`
	ReleaseID           *string                      `json:"releaseId,omitempty"`
	Health              string                       `json:"health"`
	ValidationPassed    bool                         `json:"validationPassed"`
	ValidationExpiresAt *time.Time                   `json:"validationExpiresAt,omitempty"`
	// Whether Deploy and Resume would pass the lifecycle's validation gate now:
	// a passed validation record whose expiry is still in the future, evaluated
	// server-side at read time.
	ValidationCurrent bool               `json:"validationCurrent"`
	UpdatedBy         *OperatorPrincipal `json:"updatedBy"`
	UpdatedReason     string             `json:"updatedReason"`
	UpdatedAt         time.Time          `json:"updatedAt"`
}

type OperatorDeploymentCommandInput struct {
	DefinitionID string `json:"definitionId"`
	RevisionID   string `json:"revisionId"`
	// Optimistic concurrency guard; a stale version is rejected, never retried.
	ExpectedVersion int    `json:"expectedVersion"`
	Reason          string `json:"reason"`
}

type OperatorDeploymentEvent struct {
	EventID    string             `json:"eventId"`
	Version    int                `json:"version"`
	Action     string             `json:"action"`
	FromState  string             `json:"fromState"`
	ToState    string             `json:"toState"`
	Health     string             `json:"health"`
	ReleaseID  *string            `json:"releaseId,omitempty"`
	Actor      *OperatorPrincipal `json:"actor"`
	Reason     string             `json:"reason"`
	OccurredAt time.Time          `json:"occurredAt"`
}

type OperatorDestinationAttempts struct {
	DestinationArtifactID string `json:"destinationArtifactId"`
	Queued                int    `json:"queued"`
	Succeeded             int    `json:"succeeded"`
	Failed                int    `json:"failed"`
}

// One executed destination delivery from the provenance ledger. The ledger is
// clinical-content-free by construction: server-owned provenance plus three
// advisory values (endpoint, certificate subject, OperationOutcome issue codes),
// never a response body, diagnostics text, or event content.
type OperatorDestinationDelivery struct {
	// https or fhir.
	Transport string `json:"transport"`
	// The verified destination revision; digest equals digestVerified.
	Destination    *IntegrationPreviewDestination `json:"destination"`
	DigestVerified string                         `json:"digestVerified"`
	// delivered, retryable, or refused.
	Outcome     string `json:"outcome"`
	FailureCode string `json:"failureCode"`
	// This process's own reduction of the response status: 1xx..5xx, or empty.
	HTTPStatusClass string `json:"httpStatusClass"`
	// Remote address the destination revision declares. Advisory only.
	EndpointAdvisory string `json:"endpointAdvisory"`
	// Subject of the certificate the destination served. Advisory only.
	ServedCertificateSubjectAdvisory string    `json:"servedCertificateSubjectAdvisory"`
	CompletedAt                      time.Time `json:"completedAt"`
	// FHIR resource types in the delivered Bundle, in bundle order; empty for https.
	FhirResourceTypes []string `json:"fhirResourceTypes"`
	// Entries in the delivered Bundle; 0 for https.
	FhirEntryCount int `json:"fhirEntryCount"`
	// OperationOutcome issue codes only, never diagnostics. Advisory only.
	FhirOutcomeCodesAdvisory []string `json:"fhirOutcomeCodesAdvisory"`
}

type OperatorDiagnostic struct {
	Severity       string  `json:"severity"`
	Stage          string  `json:"stage"`
	Code           string  `json:"code"`
	Path           *string `json:"path,omitempty"`
	Classification string  `json:"classification"`
}

type OperatorEvent struct {
	EventID          string                 `json:"eventId"`
	ReceiptID        string                 `json:"receiptId"`
	EventType        string                 `json:"eventType"`
	SourceMessageID  string                 `json:"sourceMessageId"`
	CorrelationID    string                 `json:"correlationId"`
	Classification   string                 `json:"classification"`
	RecordedAt       time.Time              `json:"recordedAt"`
	PayloadFields    []OperatorPayloadField `json:"payloadFields"`
	PayloadTruncated bool                   `json:"payloadTruncated"`
	// Retention deadline stamped by the purge worker; null until stamped.
	PurgeAfter *time.Time `json:"purgeAfter,omitempty"`
	// When retention replaced this event's payload with a tombstone. When set,
	// payloadFields describe the tombstone, not the admitted document.
	PurgedAt *time.Time `json:"purgedAt,omitempty"`
}

type OperatorKeyCount struct {
	Key   string `json:"key"`
	Count int    `json:"count"`
}

type OperatorLineage struct {
	LineageID         string                                 `json:"lineageId"`
	ReceiptID         string                                 `json:"receiptId"`
	EventID           string                                 `json:"eventId"`
	TraceID           string                                 `json:"traceId"`
	CorrelationID     string                                 `json:"correlationId"`
	SourceMessageID   string                                 `json:"sourceMessageId"`
	ArtifactRevisions *IntegrationExecutionArtifactRevisions `json:"artifactRevisions"`
	Routes            []OperatorRoute                        `json:"routes"`
	Diagnostics       []OperatorDiagnostic                   `json:"diagnostics"`
	RecordedAt        time.Time                              `json:"recordedAt"`
}

type OperatorMessageTrace struct {
	Receipt  *OperatorReceipt          `json:"receipt"`
	Events   []OperatorEvent           `json:"events"`
	Lineage  []OperatorLineage         `json:"lineage"`
	Attempts []OperatorDeliveryAttempt `json:"attempts"`
	Audit    []OperatorAuditRecord     `json:"audit"`
}

type OperatorPageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type OperatorPageInput struct {
	// Bounded page size. Omitted uses 25; the server caps every page at 100.
	First *int `json:"first,omitempty"`
	// Opaque forward cursor returned by a previous page.
	After *string `json:"after,omitempty"`
}

// One structural coordinate of a canonical event payload. Never a value.
type OperatorPayloadField struct {
	Path     string `json:"path"`
	Kind     string `json:"kind"`
	Repeated bool   `json:"repeated"`
}

type OperatorPrincipal struct {
	ID         string   `json:"id"`
	Kind       string   `json:"kind"`
	AuthMethod string   `json:"authMethod"`
	Roles      []string `json:"roles"`
}

type OperatorReceipt struct {
	TenantID            string                       `json:"tenantId"`
	ReceiptID           string                       `json:"receiptId"`
	Status              string                       `json:"status"`
	RecordedAt          time.Time                    `json:"recordedAt"`
	CorrelationID       string                       `json:"correlationId"`
	RawRetentionMode    string                       `json:"rawRetentionMode"`
	IntegrationRevision *IntegrationArtifactRevision `json:"integrationRevision"`
	Principal           *OperatorPrincipal           `json:"principal"`
	Reason              string                       `json:"reason"`
	EventCount          int                          `json:"eventCount"`
	AttemptCount        int                          `json:"attemptCount"`
	FailedAttemptCount  int                          `json:"failedAttemptCount"`
	DeadLetterCount     int                          `json:"deadLetterCount"`
}

type OperatorReceiptConnection struct {
	Nodes    []OperatorReceipt `json:"nodes"`
	PageInfo *OperatorPageInfo `json:"pageInfo"`
}

type OperatorReceiptFilter struct {
	Status                *string    `json:"status,omitempty"`
	IntegrationArtifactID *string    `json:"integrationArtifactId,omitempty"`
	CorrelationID         *string    `json:"correlationId,omitempty"`
	SourceMessageID       *string    `json:"sourceMessageId,omitempty"`
	From                  *time.Time `json:"from,omitempty"`
	To                    *time.Time `json:"to,omitempty"`
}

type OperatorRoute struct {
	Route           string   `json:"route"`
	Matched         bool     `json:"matched"`
	Skipped         bool     `json:"skipped"`
	SkipReason      *string  `json:"skipReason,omitempty"`
	TransformCount  int      `json:"transformCount"`
	PlannedActions  []string `json:"plannedActions"`
	DiagnosticCodes []string `json:"diagnosticCodes"`
}

// One bucket of the series. Receipts count by their recorded time, delivery
// attempts by the time they were created, each under its current status.
type OperatorStatisticsBucketCounts struct {
	Start     time.Time `json:"start"`
	Accepted  int       `json:"accepted"`
	Rejected  int       `json:"rejected"`
	Queued    int       `json:"queued"`
	Succeeded int       `json:"succeeded"`
	Failed    int       `json:"failed"`
}

// A half-open [from, to) statistics window.
type OperatorStatisticsWindow struct {
	From time.Time `json:"from"`
	To   time.Time `json:"to"`
}

type PagingInput struct {
	Limit  *int `json:"limit,omitempty"`
	Offset *int `json:"offset,omitempty"`
}

type PeekBatchConnectionInput struct {
	// A catalog batch_s3 or batch_sftp connection with a compiled revision.
	ConnectionID string `json:"connectionId"`
	// An active session.
	SessionID string `json:"sessionId"`
	// An object path from a previous listing. Without it the peek lists and reads nothing.
	ObjectPath *string `json:"objectPath,omitempty"`
	// 1-50; 10 when omitted.
	MaxObjects *int `json:"maxObjects,omitempty"`
	// 1-50; 5 when omitted.
	MaxMessages *int   `json:"maxMessages,omitempty"`
	Reason      string `json:"reason"`
}

type PendingAutoroute struct {
	ID               string                 `json:"id"`
	SourceSystem     string                 `json:"sourceSystem"`
	SourceCode       string                 `json:"sourceCode"`
	SourceDisplay    *string                `json:"sourceDisplay,omitempty"`
	TargetSystem     string                 `json:"targetSystem"`
	SuggestedCode    string                 `json:"suggestedCode"`
	SuggestedDisplay *string                `json:"suggestedDisplay,omitempty"`
	Confidence       float64                `json:"confidence"`
	Equivalence      *MappingEquivalence    `json:"equivalence,omitempty"`
	Reasoning        *string                `json:"reasoning,omitempty"`
	DecisionTrace    *AutorouteTrace        `json:"decisionTrace,omitempty"`
	Alternates       []MappingCandidate     `json:"alternates"`
	Status           PendingAutorouteStatus `json:"status"`
	CreatedAt        time.Time              `json:"createdAt"`
	ExpiresAt        *time.Time             `json:"expiresAt,omitempty"`
	ReviewedAt       *time.Time             `json:"reviewedAt,omitempty"`
	ReviewedBy       *string                `json:"reviewedBy,omitempty"`
	RejectionReason  *string                `json:"rejectionReason,omitempty"`
}

type PendingAutorouteConnection struct {
	Nodes      []PendingAutoroute `json:"nodes"`
	TotalCount int                `json:"totalCount"`
	PageInfo   *PageInfo          `json:"pageInfo"`
}

type PendingAutorouteStats struct {
	PendingCount  int      `json:"pendingCount"`
	ApprovedCount int      `json:"approvedCount"`
	RejectedCount int      `json:"rejectedCount"`
	ExpiredCount  int      `json:"expiredCount"`
	AvgConfidence *float64 `json:"avgConfidence,omitempty"`
}

type ProfileRevision struct {
	Version       string    `json:"version"`
	CreatedAt     time.Time `json:"createdAt"`
	CreatedBy     *string   `json:"createdBy,omitempty"`
	ChangeSummary *string   `json:"changeSummary,omitempty"`
}

type PromoteSessionPublicationInput struct {
	SessionID       string `json:"sessionId"`
	PublicationID   string `json:"publicationId"`
	ExpectedVersion int    `json:"expectedVersion"`
	Reason          string `json:"reason"`
}

type PublishIntegrationSessionInput struct {
	SessionID            string `json:"sessionId"`
	ProfileRevisionID    string `json:"profileRevisionId"`
	WorkflowSimulationID string `json:"workflowSimulationId"`
	DefinitionID         string `json:"definitionId"`
	DefinitionRevisionID string `json:"definitionRevisionId"`
	Reason               string `json:"reason"`
}

type PublishWorkflowVersionInput struct {
	WorkflowID  string  `json:"workflowId"`
	VersionID   string  `json:"versionId"`
	Environment string  `json:"environment"`
	PublishedBy *string `json:"publishedBy,omitempty"`
}

type QualityDimensions struct {
	Completeness float64 `json:"completeness"`
	Accuracy     float64 `json:"accuracy"`
	Consistency  float64 `json:"consistency"`
	Conformance  float64 `json:"conformance"`
	Timeliness   float64 `json:"timeliness"`
}

type QualityRecommendation struct {
	Priority    int     `json:"priority"`
	Category    *string `json:"category,omitempty"`
	Title       string  `json:"title"`
	Description string  `json:"description"`
	Impact      *string `json:"impact,omitempty"`
}

type Query struct {
}

type RejectPendingAutorouteInput struct {
	ID     string `json:"id"`
	Reason string `json:"reason"`
}

type RejectWorkflowVersionInput struct {
	ApprovalRequestID string  `json:"approvalRequestId"`
	ReviewedBy        *string `json:"reviewedBy,omitempty"`
	Comment           *string `json:"comment,omitempty"`
}

type RequestWorkflowApprovalInput struct {
	WorkflowID      string  `json:"workflowId"`
	TargetVersionID string  `json:"targetVersionId"`
	Environment     string  `json:"environment"`
	RequestedBy     *string `json:"requestedBy,omitempty"`
	Comment         *string `json:"comment,omitempty"`
}

type ResolveMappingInput struct {
	SourceCode     string   `json:"sourceCode"`
	SourceSystem   string   `json:"sourceSystem"`
	SourceDisplay  *string  `json:"sourceDisplay,omitempty"`
	TargetSystem   string   `json:"targetSystem"`
	ProfileID      *string  `json:"profileId,omitempty"`
	AllowAutoroute *bool    `json:"allowAutoroute,omitempty"`
	MinConfidence  *float64 `json:"minConfidence,omitempty"`
}

type ResolveMappingResult struct {
	Found      bool               `json:"found"`
	Decision   AutorouteDecision  `json:"decision"`
	Mapping    *CodeMapping       `json:"mapping,omitempty"`
	Candidates []MappingCandidate `json:"candidates"`
	Confidence *float64           `json:"confidence,omitempty"`
	Reasoning  *string            `json:"reasoning,omitempty"`
	Trace      *AutorouteTrace    `json:"trace,omitempty"`
	DurationMs int                `json:"durationMs"`
}

type RollbackWorkflowVersionInput struct {
	WorkflowID      string  `json:"workflowId"`
	TargetVersionID string  `json:"targetVersionId"`
	Environment     string  `json:"environment"`
	PublishedBy     *string `json:"publishedBy,omitempty"`
}

type RouteExplanation struct {
	Name        string   `json:"name"`
	Trigger     string   `json:"trigger"`
	Actions     []string `json:"actions"`
	Description string   `json:"description"`
}

type SaveWorkflowVersionInput struct {
	WorkflowID string  `json:"workflowId"`
	Yaml       string  `json:"yaml"`
	Notes      *string `json:"notes,omitempty"`
	CreatedBy  *string `json:"createdBy,omitempty"`
}

type SessionDeploymentSnapshot struct {
	DefinitionRevision *IntegrationArtifactRevision `json:"definitionRevision"`
	State              string                       `json:"state"`
	Version            int                          `json:"version"`
	ReleaseID          *string                      `json:"releaseId,omitempty"`
	Health             string                       `json:"health"`
}

type SessionPublication struct {
	ID                   string                       `json:"id"`
	SessionID            string                       `json:"sessionId"`
	Version              int                          `json:"version"`
	SessionProfile       *IntegrationArtifactRevision `json:"sessionProfile"`
	SessionWorkflow      *IntegrationArtifactRevision `json:"sessionWorkflow"`
	WorkflowSimulationID string                       `json:"workflowSimulationId"`
	DefinitionRevision   *IntegrationArtifactRevision `json:"definitionRevision"`
	DefinitionVersion    int                          `json:"definitionVersion"`
	ProductionProfile    *IntegrationArtifactRevision `json:"productionProfile"`
	ProductionWorkflow   *IntegrationArtifactRevision `json:"productionWorkflow"`
	SourceRunIds         []string                     `json:"sourceRunIds"`
	ManifestDigest       string                       `json:"manifestDigest"`
	SignatureAlgorithm   string                       `json:"signatureAlgorithm"`
	SigningKeyID         string                       `json:"signingKeyId"`
	PublishedBy          string                       `json:"publishedBy"`
	Reason               string                       `json:"reason"`
	CreatedAt            time.Time                    `json:"createdAt"`
}

type SessionWorkflowActionTrace struct {
	ID                    string  `json:"id"`
	Type                  string  `json:"type"`
	DestinationArtifactID *string `json:"destinationArtifactId,omitempty"`
}

type SessionWorkflowEventTrace struct {
	RunID     string                      `json:"runId"`
	EventID   string                      `json:"eventId"`
	EventType string                      `json:"eventType"`
	Routes    []SessionWorkflowRouteTrace `json:"routes"`
}

type SessionWorkflowRouteTrace struct {
	Name            string                          `json:"name"`
	Matched         bool                            `json:"matched"`
	SkipReason      *string                         `json:"skipReason,omitempty"`
	DiagnosticCodes []string                        `json:"diagnosticCodes"`
	Transforms      []SessionWorkflowTransformTrace `json:"transforms"`
	Actions         []SessionWorkflowActionTrace    `json:"actions"`
}

type SessionWorkflowSimulation struct {
	ID                     string                          `json:"id"`
	SessionID              string                          `json:"sessionId"`
	WorkflowArtifactID     string                          `json:"workflowArtifactId"`
	WorkflowRevisionID     string                          `json:"workflowRevisionId"`
	WorkflowRevisionDigest string                          `json:"workflowRevisionDigest"`
	SourceRunIds           []string                        `json:"sourceRunIds"`
	Events                 []SessionWorkflowEventTrace     `json:"events"`
	CreatedAt              time.Time                       `json:"createdAt"`
	Delta                  *SessionWorkflowSimulationDelta `json:"delta,omitempty"`
}

type SessionWorkflowSimulationDelta struct {
	BaselineSimulationID  string   `json:"baselineSimulationId"`
	CandidateSimulationID string   `json:"candidateSimulationId"`
	AddedEvents           []string `json:"addedEvents"`
	RemovedEvents         []string `json:"removedEvents"`
	AddedMatchedRoutes    []string `json:"addedMatchedRoutes"`
	RemovedMatchedRoutes  []string `json:"removedMatchedRoutes"`
	AddedTransforms       []string `json:"addedTransforms"`
	RemovedTransforms     []string `json:"removedTransforms"`
	AddedActions          []string `json:"addedActions"`
	RemovedActions        []string `json:"removedActions"`
}

type SessionWorkflowTransformTrace struct {
	Index  int    `json:"index"`
	Type   string `json:"type"`
	Status string `json:"status"`
}

type SignalReviewDecisionInput struct {
	WorkflowID          string              `json:"workflowId"`
	Approved            bool                `json:"approved"`
	DecidedBy           string              `json:"decidedBy"`
	EquivalenceOverride *MappingEquivalence `json:"equivalenceOverride,omitempty"`
	Comment             *string             `json:"comment,omitempty"`
	RejectionReason     *string             `json:"rejectionReason,omitempty"`
}

type SimulateSessionWorkflowInput struct {
	SessionID            string   `json:"sessionId"`
	WorkflowRevisionID   string   `json:"workflowRevisionId"`
	SourceRunIds         []string `json:"sourceRunIds"`
	BaselineSimulationID *string  `json:"baselineSimulationId,omitempty"`
}

type SourceProfile struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Version     string             `json:"version"`
	CreatedAt   time.Time          `json:"createdAt"`
	UpdatedAt   time.Time          `json:"updatedAt"`
	CreatedBy   *string            `json:"createdBy,omitempty"`
	IsActive    bool               `json:"isActive"`
	Hl7v2       *HL7v2Config       `json:"hl7v2,omitempty"`
	Identifiers *IdentifierConfig  `json:"identifiers,omitempty"`
	Terminology *TerminologyConfig `json:"terminology,omitempty"`
}

type StartConnectionCaptureInput struct {
	// The runtime source ID frames are admitted under (engineRuntime.adapters.sourceId).
	SourceID string `json:"sourceId"`
	// An active session.
	SessionID string `json:"sessionId"`
	// 1-100; 5 when omitted.
	MaxMessages *int `json:"maxMessages,omitempty"`
	// 1-900; 300 when omitted.
	TTLSeconds *int   `json:"ttlSeconds,omitempty"`
	Reason     string `json:"reason"`
}

type StartTerminologyReviewInput struct {
	SourceCode           string   `json:"sourceCode"`
	SourceSystem         string   `json:"sourceSystem"`
	SourceDisplay        *string  `json:"sourceDisplay,omitempty"`
	TargetSystem         string   `json:"targetSystem"`
	ProfileID            *string  `json:"profileId,omitempty"`
	AutoApproveThreshold *float64 `json:"autoApproveThreshold,omitempty"`
	ReviewTimeoutDays    *int     `json:"reviewTimeoutDays,omitempty"`
}

type StartTerminologyReviewResult struct {
	WorkflowID string `json:"workflowId"`
	RunID      string `json:"runId"`
	Started    bool   `json:"started"`
}

type Subscription struct {
}

type SuggestMappingsInput struct {
	SourceCode    string  `json:"sourceCode"`
	SourceSystem  string  `json:"sourceSystem"`
	SourceDisplay *string `json:"sourceDisplay,omitempty"`
	TargetSystem  string  `json:"targetSystem"`
	MaxCandidates *int    `json:"maxCandidates,omitempty"`
}

type TemporalWorkflow struct {
	ID           string                 `json:"id"`
	RunID        string                 `json:"runId"`
	WorkflowType string                 `json:"workflowType"`
	Status       TemporalWorkflowStatus `json:"status"`
	TaskQueue    string                 `json:"taskQueue"`
	StartTime    time.Time              `json:"startTime"`
	CloseTime    *time.Time             `json:"closeTime,omitempty"`
	DurationMs   *int                   `json:"durationMs,omitempty"`
	Input        map[string]any         `json:"input,omitempty"`
	Result       map[string]any         `json:"result,omitempty"`
	Error        *string                `json:"error,omitempty"`
}

type TemporalWorkflowConnection struct {
	Nodes      []TemporalWorkflow `json:"nodes"`
	TotalCount int                `json:"totalCount"`
	PageInfo   *PageInfo          `json:"pageInfo"`
}

type TemporalWorkflowFilter struct {
	WorkflowType    *string                 `json:"workflowType,omitempty"`
	Status          *TemporalWorkflowStatus `json:"status,omitempty"`
	StartTimeAfter  *time.Time              `json:"startTimeAfter,omitempty"`
	StartTimeBefore *time.Time              `json:"startTimeBefore,omitempty"`
}

type TerminologyConfig struct {
	Mappings []TerminologyMappingTable `json:"mappings"`
}

type TerminologyConfigInput struct {
	Mappings []TerminologyMappingTableInput `json:"mappings,omitempty"`
}

type TerminologyMappingEntry struct {
	SourceCode string  `json:"sourceCode"`
	TargetCode string  `json:"targetCode"`
	Display    *string `json:"display,omitempty"`
}

type TerminologyMappingEntryInput struct {
	SourceCode string  `json:"sourceCode"`
	TargetCode string  `json:"targetCode"`
	Display    *string `json:"display,omitempty"`
}

type TerminologyMappingTable struct {
	ID           string                    `json:"id"`
	SourceSystem string                    `json:"sourceSystem"`
	TargetSystem string                    `json:"targetSystem"`
	Entries      []TerminologyMappingEntry `json:"entries"`
}

type TerminologyMappingTableInput struct {
	ID           string                         `json:"id"`
	SourceSystem string                         `json:"sourceSystem"`
	TargetSystem string                         `json:"targetSystem"`
	Entries      []TerminologyMappingEntryInput `json:"entries,omitempty"`
}

type ToleranceConfig struct {
	MissingSegments       []string `json:"missingSegments"`
	NteAnywhere           bool     `json:"nteAnywhere"`
	ExtraComponents       bool     `json:"extraComponents"`
	UnknownSegments       bool     `json:"unknownSegments"`
	NonStandardDelimiters bool     `json:"nonStandardDelimiters"`
}

type ToleranceConfigInput struct {
	MissingSegments       []string `json:"missingSegments,omitempty"`
	NteAnywhere           *bool    `json:"nteAnywhere,omitempty"`
	ExtraComponents       *bool    `json:"extraComponents,omitempty"`
	UnknownSegments       *bool    `json:"unknownSegments,omitempty"`
	NonStandardDelimiters *bool    `json:"nonStandardDelimiters,omitempty"`
}

type UpdateConnectionInput struct {
	ID string `json:"id"`
	// Optimistic concurrency guard; a stale version is rejected, never retried.
	ExpectedVersion int     `json:"expectedVersion"`
	Name            *string `json:"name,omitempty"`
	Description     *string `json:"description,omitempty"`
	// Replaces the stored spec when present.
	Spec map[string]any `json:"spec,omitempty"`
	// Replaces the stored bindings when present, including with an empty list.
	SecretBindings []ConnectionSecretBindingInput `json:"secretBindings,omitempty"`
	Reason         string                         `json:"reason"`
}

type UpdateMappingInput struct {
	ID            string              `json:"id"`
	SourceDisplay *string             `json:"sourceDisplay,omitempty"`
	TargetDisplay *string             `json:"targetDisplay,omitempty"`
	Equivalence   *MappingEquivalence `json:"equivalence,omitempty"`
	Confidence    *float64            `json:"confidence,omitempty"`
	Comment       *string             `json:"comment,omitempty"`
}

type UpdateProfileInput struct {
	ChangeSummary string                  `json:"changeSummary"`
	Name          *string                 `json:"name,omitempty"`
	Hl7v2         *HL7v2ConfigInput       `json:"hl7v2,omitempty"`
	Identifiers   *IdentifierConfigInput  `json:"identifiers,omitempty"`
	Terminology   *TerminologyConfigInput `json:"terminology,omitempty"`
}

type UpdateWorkflowDefinitionInput struct {
	ID          string  `json:"id"`
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Status      *string `json:"status,omitempty"`
	UpdatedBy   *string `json:"updatedBy,omitempty"`
}

type UploadBatch struct {
	ID               string                  `json:"id"`
	Filename         string                  `json:"filename"`
	SourceSystem     *string                 `json:"sourceSystem,omitempty"`
	TargetSystem     *string                 `json:"targetSystem,omitempty"`
	ProfileID        *string                 `json:"profileId,omitempty"`
	TotalRows        int                     `json:"totalRows"`
	ValidRows        int                     `json:"validRows"`
	DuplicateRows    int                     `json:"duplicateRows"`
	ErrorRows        int                     `json:"errorRows"`
	UploadedAt       time.Time               `json:"uploadedAt"`
	UploadedBy       *string                 `json:"uploadedBy,omitempty"`
	ValidationErrors []UploadValidationError `json:"validationErrors"`
}

type UploadMappingCSVInput struct {
	CSV                 string  `json:"csv"`
	Filename            string  `json:"filename"`
	DefaultSourceSystem *string `json:"defaultSourceSystem,omitempty"`
	DefaultTargetSystem *string `json:"defaultTargetSystem,omitempty"`
	ProfileID           *string `json:"profileId,omitempty"`
	DryRun              *bool   `json:"dryRun,omitempty"`
}

type UploadMappingResult struct {
	Batch           *UploadBatch  `json:"batch"`
	MappingsCreated int           `json:"mappingsCreated"`
	MappingsSkipped int           `json:"mappingsSkipped"`
	Preview         []CodeMapping `json:"preview"`
}

type UploadValidationError struct {
	Row     int     `json:"row"`
	Column  *string `json:"column,omitempty"`
	Message string  `json:"message"`
}

type ValidateConnectionSpecInput struct {
	Kind           ConnectionKind                 `json:"kind"`
	Spec           map[string]any                 `json:"spec"`
	SecretBindings []ConnectionSecretBindingInput `json:"secretBindings,omitempty"`
}

type ValidationSettingsConfig struct {
	Npi *ValidatorSetting `json:"npi,omitempty"`
	Mbi *ValidatorSetting `json:"mbi,omitempty"`
	Ssn *ValidatorSetting `json:"ssn,omitempty"`
}

type ValidationSettingsInput struct {
	Npi *ValidatorSettingInput `json:"npi,omitempty"`
	Mbi *ValidatorSettingInput `json:"mbi,omitempty"`
	Ssn *ValidatorSettingInput `json:"ssn,omitempty"`
}

type ValidatorSetting struct {
	Enabled   bool   `json:"enabled"`
	OnInvalid string `json:"onInvalid"`
}

type ValidatorSettingInput struct {
	Enabled   bool   `json:"enabled"`
	OnInvalid string `json:"onInvalid"`
}

type WorkflowApprovalRequest struct {
	ID              string     `json:"id"`
	WorkflowID      string     `json:"workflowId"`
	TargetVersionID string     `json:"targetVersionId"`
	Environment     string     `json:"environment"`
	Status          string     `json:"status"`
	RequestedBy     string     `json:"requestedBy"`
	ReviewedBy      *string    `json:"reviewedBy,omitempty"`
	ReviewedAt      *time.Time `json:"reviewedAt,omitempty"`
	Comment         *string    `json:"comment,omitempty"`
}

type WorkflowApprovalRequestFilter struct {
	WorkflowID  *string `json:"workflowId,omitempty"`
	Environment *string `json:"environment,omitempty"`
	Status      *string `json:"status,omitempty"`
}

type WorkflowDefinition struct {
	ID                     string           `json:"id"`
	Name                   string           `json:"name"`
	Description            *string          `json:"description,omitempty"`
	Status                 string           `json:"status"`
	CreatedAt              time.Time        `json:"createdAt"`
	UpdatedAt              time.Time        `json:"updatedAt"`
	LatestVersion          *WorkflowVersion `json:"latestVersion,omitempty"`
	PublishedVersionsByEnv map[string]any   `json:"publishedVersionsByEnv"`
}

type WorkflowDefinitionFilter struct {
	Name   *string `json:"name,omitempty"`
	Status *string `json:"status,omitempty"`
}

type WorkflowExplanation struct {
	Summary           string             `json:"summary"`
	Description       string             `json:"description"`
	RouteExplanations []RouteExplanation `json:"routeExplanations"`
	Diagram           *string            `json:"diagram,omitempty"`
	Warnings          []string           `json:"warnings"`
}

type WorkflowRelease struct {
	ID                    string    `json:"id"`
	WorkflowID            string    `json:"workflowId"`
	Environment           string    `json:"environment"`
	VersionID             string    `json:"versionId"`
	PublishedBy           string    `json:"publishedBy"`
	PublishedAt           time.Time `json:"publishedAt"`
	RollbackFromReleaseID *string   `json:"rollbackFromReleaseId,omitempty"`
}

type WorkflowRun struct {
	ID              string    `json:"id"`
	WorkflowName    string    `json:"workflowName"`
	Environment     string    `json:"environment"`
	VersionID       *string   `json:"versionId,omitempty"`
	EventID         *string   `json:"eventId,omitempty"`
	RoutesMatched   int       `json:"routesMatched"`
	ActionsExecuted int       `json:"actionsExecuted"`
	Errors          []string  `json:"errors"`
	DurationMs      int       `json:"durationMs"`
	StartedAt       time.Time `json:"startedAt"`
	Status          string    `json:"status"`
}

type WorkflowRunFilter struct {
	WorkflowName  *string    `json:"workflowName,omitempty"`
	Environment   *string    `json:"environment,omitempty"`
	Status        *string    `json:"status,omitempty"`
	FromStartedAt *time.Time `json:"fromStartedAt,omitempty"`
	ToStartedAt   *time.Time `json:"toStartedAt,omitempty"`
}

type WorkflowValidation struct {
	Valid    bool     `json:"valid"`
	Errors   []string `json:"errors"`
	Warnings []string `json:"warnings"`
	Info     []string `json:"info"`
}

type WorkflowVersion struct {
	ID            string              `json:"id"`
	WorkflowID    string              `json:"workflowId"`
	VersionNumber int                 `json:"versionNumber"`
	Yaml          string              `json:"yaml"`
	Validation    *WorkflowValidation `json:"validation"`
	CreatedBy     string              `json:"createdBy"`
	CreatedAt     time.Time           `json:"createdAt"`
	Notes         *string             `json:"notes,omitempty"`
}

type AutorouteDecision string

const (
	AutorouteDecisionPersistentHit     AutorouteDecision = "PERSISTENT_HIT"
	AutorouteDecisionAutorouteHighConf AutorouteDecision = "AUTOROUTE_HIGH_CONF"
	AutorouteDecisionAutorouteMedConf  AutorouteDecision = "AUTOROUTE_MED_CONF"
	AutorouteDecisionAutorouteLowConf  AutorouteDecision = "AUTOROUTE_LOW_CONF"
	AutorouteDecisionNoMatch           AutorouteDecision = "NO_MATCH"
)

var AllAutorouteDecision = []AutorouteDecision{
	AutorouteDecisionPersistentHit,
	AutorouteDecisionAutorouteHighConf,
	AutorouteDecisionAutorouteMedConf,
	AutorouteDecisionAutorouteLowConf,
	AutorouteDecisionNoMatch,
}

func (e AutorouteDecision) IsValid() bool {
	switch e {
	case AutorouteDecisionPersistentHit, AutorouteDecisionAutorouteHighConf, AutorouteDecisionAutorouteMedConf, AutorouteDecisionAutorouteLowConf, AutorouteDecisionNoMatch:
		return true
	}
	return false
}

func (e AutorouteDecision) String() string {
	return string(e)
}

func (e *AutorouteDecision) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AutorouteDecision(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AutorouteDecision", str)
	}
	return nil
}

func (e AutorouteDecision) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AutorouteDecision) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AutorouteDecision) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ConnectionCaptureMode string

const (
	ConnectionCaptureModePeek   ConnectionCaptureMode = "PEEK"
	ConnectionCaptureModeStream ConnectionCaptureMode = "STREAM"
)

var AllConnectionCaptureMode = []ConnectionCaptureMode{
	ConnectionCaptureModePeek,
	ConnectionCaptureModeStream,
}

func (e ConnectionCaptureMode) IsValid() bool {
	switch e {
	case ConnectionCaptureModePeek, ConnectionCaptureModeStream:
		return true
	}
	return false
}

func (e ConnectionCaptureMode) String() string {
	return string(e)
}

func (e *ConnectionCaptureMode) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ConnectionCaptureMode(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ConnectionCaptureMode", str)
	}
	return nil
}

func (e ConnectionCaptureMode) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ConnectionCaptureMode) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ConnectionCaptureMode) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ConnectionCaptureStatus string

const (
	ConnectionCaptureStatusArmed     ConnectionCaptureStatus = "ARMED"
	ConnectionCaptureStatusComplete  ConnectionCaptureStatus = "COMPLETE"
	ConnectionCaptureStatusExpired   ConnectionCaptureStatus = "EXPIRED"
	ConnectionCaptureStatusCancelled ConnectionCaptureStatus = "CANCELLED"
	ConnectionCaptureStatusFailed    ConnectionCaptureStatus = "FAILED"
)

var AllConnectionCaptureStatus = []ConnectionCaptureStatus{
	ConnectionCaptureStatusArmed,
	ConnectionCaptureStatusComplete,
	ConnectionCaptureStatusExpired,
	ConnectionCaptureStatusCancelled,
	ConnectionCaptureStatusFailed,
}

func (e ConnectionCaptureStatus) IsValid() bool {
	switch e {
	case ConnectionCaptureStatusArmed, ConnectionCaptureStatusComplete, ConnectionCaptureStatusExpired, ConnectionCaptureStatusCancelled, ConnectionCaptureStatusFailed:
		return true
	}
	return false
}

func (e ConnectionCaptureStatus) String() string {
	return string(e)
}

func (e *ConnectionCaptureStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ConnectionCaptureStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ConnectionCaptureStatus", str)
	}
	return nil
}

func (e ConnectionCaptureStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ConnectionCaptureStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ConnectionCaptureStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ConnectionDirection string

const (
	ConnectionDirectionSource      ConnectionDirection = "SOURCE"
	ConnectionDirectionDestination ConnectionDirection = "DESTINATION"
)

var AllConnectionDirection = []ConnectionDirection{
	ConnectionDirectionSource,
	ConnectionDirectionDestination,
}

func (e ConnectionDirection) IsValid() bool {
	switch e {
	case ConnectionDirectionSource, ConnectionDirectionDestination:
		return true
	}
	return false
}

func (e ConnectionDirection) String() string {
	return string(e)
}

func (e *ConnectionDirection) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ConnectionDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ConnectionDirection", str)
	}
	return nil
}

func (e ConnectionDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ConnectionDirection) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ConnectionDirection) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ConnectionKind string

const (
	ConnectionKindMllp      ConnectionKind = "MLLP"
	ConnectionKindHTTP      ConnectionKind = "HTTP"
	ConnectionKindBatchS3   ConnectionKind = "BATCH_S3"
	ConnectionKindBatchSftp ConnectionKind = "BATCH_SFTP"
	ConnectionKindHTTPS     ConnectionKind = "HTTPS"
	ConnectionKindFhir      ConnectionKind = "FHIR"
	ConnectionKindKafka     ConnectionKind = "KAFKA"
)

var AllConnectionKind = []ConnectionKind{
	ConnectionKindMllp,
	ConnectionKindHTTP,
	ConnectionKindBatchS3,
	ConnectionKindBatchSftp,
	ConnectionKindHTTPS,
	ConnectionKindFhir,
	ConnectionKindKafka,
}

func (e ConnectionKind) IsValid() bool {
	switch e {
	case ConnectionKindMllp, ConnectionKindHTTP, ConnectionKindBatchS3, ConnectionKindBatchSftp, ConnectionKindHTTPS, ConnectionKindFhir, ConnectionKindKafka:
		return true
	}
	return false
}

func (e ConnectionKind) String() string {
	return string(e)
}

func (e *ConnectionKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ConnectionKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ConnectionKind", str)
	}
	return nil
}

func (e ConnectionKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ConnectionKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ConnectionKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MappingEquivalence string

const (
	MappingEquivalenceEquivalent MappingEquivalence = "EQUIVALENT"
	MappingEquivalenceWider      MappingEquivalence = "WIDER"
	MappingEquivalenceNarrower   MappingEquivalence = "NARROWER"
	MappingEquivalenceInexact    MappingEquivalence = "INEXACT"
)

var AllMappingEquivalence = []MappingEquivalence{
	MappingEquivalenceEquivalent,
	MappingEquivalenceWider,
	MappingEquivalenceNarrower,
	MappingEquivalenceInexact,
}

func (e MappingEquivalence) IsValid() bool {
	switch e {
	case MappingEquivalenceEquivalent, MappingEquivalenceWider, MappingEquivalenceNarrower, MappingEquivalenceInexact:
		return true
	}
	return false
}

func (e MappingEquivalence) String() string {
	return string(e)
}

func (e *MappingEquivalence) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MappingEquivalence(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MappingEquivalence", str)
	}
	return nil
}

func (e MappingEquivalence) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MappingEquivalence) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MappingEquivalence) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MappingOrigin string

const (
	MappingOriginCSVUpload         MappingOrigin = "CSV_UPLOAD"
	MappingOriginApprovedAutoroute MappingOrigin = "APPROVED_AUTOROUTE"
	MappingOriginManual            MappingOrigin = "MANUAL"
)

var AllMappingOrigin = []MappingOrigin{
	MappingOriginCSVUpload,
	MappingOriginApprovedAutoroute,
	MappingOriginManual,
}

func (e MappingOrigin) IsValid() bool {
	switch e {
	case MappingOriginCSVUpload, MappingOriginApprovedAutoroute, MappingOriginManual:
		return true
	}
	return false
}

func (e MappingOrigin) String() string {
	return string(e)
}

func (e *MappingOrigin) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MappingOrigin(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MappingOrigin", str)
	}
	return nil
}

func (e MappingOrigin) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MappingOrigin) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MappingOrigin) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// Time-series bucket width, in UTC. A window may span at most 744 buckets
// (a month of hours); a wider one is refused, never clipped.
type OperatorStatisticsBucket string

const (
	OperatorStatisticsBucketHour OperatorStatisticsBucket = "HOUR"
	OperatorStatisticsBucketDay  OperatorStatisticsBucket = "DAY"
)

var AllOperatorStatisticsBucket = []OperatorStatisticsBucket{
	OperatorStatisticsBucketHour,
	OperatorStatisticsBucketDay,
}

func (e OperatorStatisticsBucket) IsValid() bool {
	switch e {
	case OperatorStatisticsBucketHour, OperatorStatisticsBucketDay:
		return true
	}
	return false
}

func (e OperatorStatisticsBucket) String() string {
	return string(e)
}

func (e *OperatorStatisticsBucket) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OperatorStatisticsBucket(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OperatorStatisticsBucket", str)
	}
	return nil
}

func (e OperatorStatisticsBucket) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OperatorStatisticsBucket) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OperatorStatisticsBucket) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PendingAutorouteStatus string

const (
	PendingAutorouteStatusPending  PendingAutorouteStatus = "PENDING"
	PendingAutorouteStatusApproved PendingAutorouteStatus = "APPROVED"
	PendingAutorouteStatusRejected PendingAutorouteStatus = "REJECTED"
	PendingAutorouteStatusExpired  PendingAutorouteStatus = "EXPIRED"
)

var AllPendingAutorouteStatus = []PendingAutorouteStatus{
	PendingAutorouteStatusPending,
	PendingAutorouteStatusApproved,
	PendingAutorouteStatusRejected,
	PendingAutorouteStatusExpired,
}

func (e PendingAutorouteStatus) IsValid() bool {
	switch e {
	case PendingAutorouteStatusPending, PendingAutorouteStatusApproved, PendingAutorouteStatusRejected, PendingAutorouteStatusExpired:
		return true
	}
	return false
}

func (e PendingAutorouteStatus) String() string {
	return string(e)
}

func (e *PendingAutorouteStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PendingAutorouteStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PendingAutorouteStatus", str)
	}
	return nil
}

func (e PendingAutorouteStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PendingAutorouteStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PendingAutorouteStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TemporalWorkflowStatus string

const (
	TemporalWorkflowStatusRunning        TemporalWorkflowStatus = "RUNNING"
	TemporalWorkflowStatusCompleted      TemporalWorkflowStatus = "COMPLETED"
	TemporalWorkflowStatusFailed         TemporalWorkflowStatus = "FAILED"
	TemporalWorkflowStatusCanceled       TemporalWorkflowStatus = "CANCELED"
	TemporalWorkflowStatusTerminated     TemporalWorkflowStatus = "TERMINATED"
	TemporalWorkflowStatusContinuedAsNew TemporalWorkflowStatus = "CONTINUED_AS_NEW"
	TemporalWorkflowStatusTimedOut       TemporalWorkflowStatus = "TIMED_OUT"
)

var AllTemporalWorkflowStatus = []TemporalWorkflowStatus{
	TemporalWorkflowStatusRunning,
	TemporalWorkflowStatusCompleted,
	TemporalWorkflowStatusFailed,
	TemporalWorkflowStatusCanceled,
	TemporalWorkflowStatusTerminated,
	TemporalWorkflowStatusContinuedAsNew,
	TemporalWorkflowStatusTimedOut,
}

func (e TemporalWorkflowStatus) IsValid() bool {
	switch e {
	case TemporalWorkflowStatusRunning, TemporalWorkflowStatusCompleted, TemporalWorkflowStatusFailed, TemporalWorkflowStatusCanceled, TemporalWorkflowStatusTerminated, TemporalWorkflowStatusContinuedAsNew, TemporalWorkflowStatusTimedOut:
		return true
	}
	return false
}

func (e TemporalWorkflowStatus) String() string {
	return string(e)
}

func (e *TemporalWorkflowStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TemporalWorkflowStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TemporalWorkflowStatus", str)
	}
	return nil
}

func (e TemporalWorkflowStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TemporalWorkflowStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TemporalWorkflowStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
