// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type AnalyzeQualityInput struct {
	Event     map[string]any `json:"event"`
	EventType EventType      `json:"eventType"`
}

type ApprovePendingAutorouteInput struct {
	ID          string              `json:"id"`
	Equivalence *MappingEquivalence `json:"equivalence,omitempty"`
	Comment     *string             `json:"comment,omitempty"`
}

type ApproveWorkflowVersionInput struct {
	ApprovalRequestID string  `json:"approvalRequestId"`
	ReviewedBy        *string `json:"reviewedBy,omitempty"`
	Comment           *string `json:"comment,omitempty"`
}

type ArchiveWorkflowDefinitionInput struct {
	WorkflowID string  `json:"workflowId"`
	ArchivedBy *string `json:"archivedBy,omitempty"`
}

type AssigningAuthority struct {
	Code   string  `json:"code"`
	System string  `json:"system"`
	Name   *string `json:"name,omitempty"`
}

type AssigningAuthorityInput struct {
	Code   string  `json:"code"`
	System string  `json:"system"`
	Name   *string `json:"name,omitempty"`
}

type AutorouteStep struct {
	Step       string         `json:"step"`
	Result     string         `json:"result"`
	DurationMs int            `json:"durationMs"`
	Metadata   map[string]any `json:"metadata,omitempty"`
}

type AutorouteTrace struct {
	TraceID         string          `json:"traceId"`
	Timestamp       time.Time       `json:"timestamp"`
	Steps           []AutorouteStep `json:"steps"`
	TotalDurationMs int             `json:"totalDurationMs"`
}

type BulkApproveInput struct {
	MinConfidence *float64 `json:"minConfidence,omitempty"`
	MaxCount      *int     `json:"maxCount,omitempty"`
}

type BulkApproveResult struct {
	Approved int           `json:"approved"`
	Skipped  int           `json:"skipped"`
	Mappings []CodeMapping `json:"mappings"`
}

type ClassifyMessageInput struct {
	Data   string       `json:"data"`
	Format SourceFormat `json:"format"`
}

type CodeMapping struct {
	ID            string             `json:"id"`
	SourceSystem  string             `json:"sourceSystem"`
	SourceCode    string             `json:"sourceCode"`
	SourceDisplay *string            `json:"sourceDisplay,omitempty"`
	TargetSystem  string             `json:"targetSystem"`
	TargetCode    string             `json:"targetCode"`
	TargetDisplay *string            `json:"targetDisplay,omitempty"`
	Equivalence   MappingEquivalence `json:"equivalence"`
	Confidence    *float64           `json:"confidence,omitempty"`
	Comment       *string            `json:"comment,omitempty"`
	Origin        MappingOrigin      `json:"origin"`
	ProfileID     *string            `json:"profileId,omitempty"`
	UploadBatchID *string            `json:"uploadBatchId,omitempty"`
	CreatedAt     time.Time          `json:"createdAt"`
	CreatedBy     *string            `json:"createdBy,omitempty"`
	ApprovedAt    *time.Time         `json:"approvedAt,omitempty"`
	ApprovedBy    *string            `json:"approvedBy,omitempty"`
}

type CodeMappingConnection struct {
	Nodes      []CodeMapping `json:"nodes"`
	TotalCount int           `json:"totalCount"`
	PageInfo   *PageInfo     `json:"pageInfo"`
}

type CreateMappingInput struct {
	SourceSystem  string              `json:"sourceSystem"`
	SourceCode    string              `json:"sourceCode"`
	SourceDisplay *string             `json:"sourceDisplay,omitempty"`
	TargetSystem  string              `json:"targetSystem"`
	TargetCode    string              `json:"targetCode"`
	TargetDisplay *string             `json:"targetDisplay,omitempty"`
	Equivalence   *MappingEquivalence `json:"equivalence,omitempty"`
	Confidence    *float64            `json:"confidence,omitempty"`
	Origin        *MappingOrigin      `json:"origin,omitempty"`
	Comment       *string             `json:"comment,omitempty"`
	ProfileID     *string             `json:"profileId,omitempty"`
}

type CreateProfileInput struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type CreateWorkflowDefinitionInput struct {
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
	CreatedBy   *string `json:"createdBy,omitempty"`
}

type DataQualityIssue struct {
	Dimension     string  `json:"dimension"`
	Severity      string  `json:"severity"`
	Field         *string `json:"field,omitempty"`
	Description   string  `json:"description"`
	ActualValue   *string `json:"actualValue,omitempty"`
	ExpectedValue *string `json:"expectedValue,omitempty"`
}

type DataQualityScore struct {
	OverallScore     float64                 `json:"overallScore"`
	Dimensions       *QualityDimensions      `json:"dimensions"`
	Issues           []DataQualityIssue      `json:"issues"`
	Recommendations  []QualityRecommendation `json:"recommendations"`
	ProcessingTimeMs *int                    `json:"processingTimeMs,omitempty"`
	Model            *string                 `json:"model,omitempty"`
}

type EventClassificationRule struct {
	MessageType string  `json:"messageType"`
	Condition   *string `json:"condition,omitempty"`
	EventType   string  `json:"eventType"`
	Priority    int     `json:"priority"`
}

type EventClassificationRuleInput struct {
	MessageType string  `json:"messageType"`
	Condition   *string `json:"condition,omitempty"`
	EventType   string  `json:"eventType"`
	Priority    int     `json:"priority"`
}

type ExplainWorkflowInput struct {
	WorkflowYaml string  `json:"workflowYaml"`
	Audience     *string `json:"audience,omitempty"`
}

type ExtractEntitiesInput struct {
	Text           string   `json:"text"`
	DocumentType   *string  `json:"documentType,omitempty"`
	PatientAge     *int     `json:"patientAge,omitempty"`
	PatientGender  *string  `json:"patientGender,omitempty"`
	MinConfidence  *float64 `json:"minConfidence,omitempty"`
	IncludeNegated *bool    `json:"includeNegated,omitempty"`
}

type ExtractedAllergy struct {
	Substance  string  `json:"substance"`
	Code       *string `json:"code,omitempty"`
	CodeSystem *string `json:"codeSystem,omitempty"`
	Severity   *string `json:"severity,omitempty"`
	Reaction   *string `json:"reaction,omitempty"`
	Confidence float64 `json:"confidence"`
	Negated    *bool   `json:"negated,omitempty"`
	TextSpan   *string `json:"textSpan,omitempty"`
}

type ExtractedCondition struct {
	Name       string  `json:"name"`
	Code       *string `json:"code,omitempty"`
	CodeSystem *string `json:"codeSystem,omitempty"`
	Confidence float64 `json:"confidence"`
	Negated    *bool   `json:"negated,omitempty"`
	TextSpan   *string `json:"textSpan,omitempty"`
	Status     *string `json:"status,omitempty"`
}

type ExtractedMedication struct {
	Name       string  `json:"name"`
	Code       *string `json:"code,omitempty"`
	CodeSystem *string `json:"codeSystem,omitempty"`
	Dose       *string `json:"dose,omitempty"`
	Route      *string `json:"route,omitempty"`
	Frequency  *string `json:"frequency,omitempty"`
	Confidence float64 `json:"confidence"`
	Negated    *bool   `json:"negated,omitempty"`
	TextSpan   *string `json:"textSpan,omitempty"`
}

type ExtractedProcedure struct {
	Name       string  `json:"name"`
	Code       *string `json:"code,omitempty"`
	CodeSystem *string `json:"codeSystem,omitempty"`
	Status     *string `json:"status,omitempty"`
	Confidence float64 `json:"confidence"`
	Negated    *bool   `json:"negated,omitempty"`
	TextSpan   *string `json:"textSpan,omitempty"`
}

type ExtractedVitalSign struct {
	Name           string  `json:"name"`
	LoincCode      *string `json:"loincCode,omitempty"`
	Value          string  `json:"value"`
	Unit           *string `json:"unit,omitempty"`
	Confidence     float64 `json:"confidence"`
	Interpretation *string `json:"interpretation,omitempty"`
	TextSpan       *string `json:"textSpan,omitempty"`
}

type ExtractionResult struct {
	Conditions        []ExtractedCondition  `json:"conditions"`
	Medications       []ExtractedMedication `json:"medications"`
	VitalSigns        []ExtractedVitalSign  `json:"vitalSigns"`
	Allergies         []ExtractedAllergy    `json:"allergies"`
	Procedures        []ExtractedProcedure  `json:"procedures"`
	OverallConfidence float64               `json:"overallConfidence"`
	ProcessingTimeMs  int                   `json:"processingTimeMs"`
	Model             *string               `json:"model,omitempty"`
}

type GenerateWorkflowInput struct {
	Description string   `json:"description"`
	EventTypes  []string `json:"eventTypes,omitempty"`
	ActionTypes []string `json:"actionTypes,omitempty"`
}

type GeneratedWorkflow struct {
	Yaml        string   `json:"yaml"`
	Explanation string   `json:"explanation"`
	Warnings    []string `json:"warnings"`
}

type HL7v2Config struct {
	DefaultVersion       string                    `json:"defaultVersion"`
	Timezone             string                    `json:"timezone"`
	Tolerance            *ToleranceConfig          `json:"tolerance,omitempty"`
	EventClassifications []EventClassificationRule `json:"eventClassifications"`
}

type HL7v2ConfigInput struct {
	DefaultVersion       *string                        `json:"defaultVersion,omitempty"`
	Timezone             *string                        `json:"timezone,omitempty"`
	Tolerance            *ToleranceConfigInput          `json:"tolerance,omitempty"`
	EventClassifications []EventClassificationRuleInput `json:"eventClassifications,omitempty"`
}

type IDPreferenceRule struct {
	Type             string  `json:"type"`
	AssignerContains *string `json:"assignerContains,omitempty"`
	Priority         int     `json:"priority"`
}

type IDPreferenceRuleInput struct {
	Type             string  `json:"type"`
	AssignerContains *string `json:"assignerContains,omitempty"`
	Priority         int     `json:"priority"`
}

type IdentifierConfig struct {
	AssigningAuthorities []AssigningAuthority         `json:"assigningAuthorities"`
	PrimaryIDPreference  []IDPreferenceRule           `json:"primaryIdPreference"`
	Validation           *ValidationSettingsConfig    `json:"validation,omitempty"`
	Normalization        *NormalizationSettingsConfig `json:"normalization,omitempty"`
}

type IdentifierConfigInput struct {
	AssigningAuthorities []AssigningAuthorityInput   `json:"assigningAuthorities,omitempty"`
	PrimaryIDPreference  []IDPreferenceRuleInput     `json:"primaryIdPreference,omitempty"`
	Validation           *ValidationSettingsInput    `json:"validation,omitempty"`
	Normalization        *NormalizationSettingsInput `json:"normalization,omitempty"`
}

type LLMCapability struct {
	Enabled             bool                   `json:"enabled"`
	Configured          bool                   `json:"configured"`
	ProviderBaseURLHost *string                `json:"providerBaseURLHost,omitempty"`
	DefaultModel        *string                `json:"defaultModel,omitempty"`
	QualityModel        *string                `json:"qualityModel,omitempty"`
	Status              string                 `json:"status"`
	Warnings            []string               `json:"warnings"`
	Features            []LLMFeatureCapability `json:"features"`
}

type ListMappingsInput struct {
	SourceSystem  *string             `json:"sourceSystem,omitempty"`
	TargetSystem  *string             `json:"targetSystem,omitempty"`
	ProfileID     *string             `json:"profileId,omitempty"`
	Origin        *MappingOrigin      `json:"origin,omitempty"`
	UploadBatchID *string             `json:"uploadBatchId,omitempty"`
	Equivalence   *MappingEquivalence `json:"equivalence,omitempty"`
	CreatedAfter  *time.Time          `json:"createdAfter,omitempty"`
	CreatedBefore *time.Time          `json:"createdBefore,omitempty"`
	First         *int                `json:"first,omitempty"`
	Offset        *int                `json:"offset,omitempty"`
}

type ListPendingAutoroutesInput struct {
	Status        *PendingAutorouteStatus `json:"status,omitempty"`
	MinConfidence *float64                `json:"minConfidence,omitempty"`
	SourceSystem  *string                 `json:"sourceSystem,omitempty"`
	TargetSystem  *string                 `json:"targetSystem,omitempty"`
	First         *int                    `json:"first,omitempty"`
	Offset        *int                    `json:"offset,omitempty"`
}

type MappingCandidate struct {
	Code        string              `json:"code"`
	Display     string              `json:"display"`
	System      string              `json:"system"`
	Confidence  float64             `json:"confidence"`
	Equivalence *MappingEquivalence `json:"equivalence,omitempty"`
	Reasoning   *string             `json:"reasoning,omitempty"`
	Score       *float64            `json:"score,omitempty"`
}

type MessageClassification struct {
	MessageType   string     `json:"messageType"`
	EventType     *EventType `json:"eventType,omitempty"`
	SuggestedTags []string   `json:"suggestedTags"`
	Confidence    float64    `json:"confidence"`
	Summary       *string    `json:"summary,omitempty"`
}

type Mutation struct {
}

type NormalizationSettingsConfig struct {
	SsnStripDashes    bool     `json:"ssnStripDashes"`
	SsnRejectPatterns []string `json:"ssnRejectPatterns"`
	PhoneNormalize    bool     `json:"phoneNormalize"`
	PhoneFormat       *string  `json:"phoneFormat,omitempty"`
}

type NormalizationSettingsInput struct {
	SsnStripDashes    *bool    `json:"ssnStripDashes,omitempty"`
	SsnRejectPatterns []string `json:"ssnRejectPatterns,omitempty"`
	PhoneNormalize    *bool    `json:"phoneNormalize,omitempty"`
	PhoneFormat       *string  `json:"phoneFormat,omitempty"`
}

type PagingInput struct {
	Limit  *int `json:"limit,omitempty"`
	Offset *int `json:"offset,omitempty"`
}

type PendingAutoroute struct {
	ID               string                 `json:"id"`
	SourceSystem     string                 `json:"sourceSystem"`
	SourceCode       string                 `json:"sourceCode"`
	SourceDisplay    *string                `json:"sourceDisplay,omitempty"`
	TargetSystem     string                 `json:"targetSystem"`
	SuggestedCode    string                 `json:"suggestedCode"`
	SuggestedDisplay *string                `json:"suggestedDisplay,omitempty"`
	Confidence       float64                `json:"confidence"`
	Equivalence      *MappingEquivalence    `json:"equivalence,omitempty"`
	Reasoning        *string                `json:"reasoning,omitempty"`
	DecisionTrace    *AutorouteTrace        `json:"decisionTrace,omitempty"`
	Alternates       []MappingCandidate     `json:"alternates"`
	Status           PendingAutorouteStatus `json:"status"`
	CreatedAt        time.Time              `json:"createdAt"`
	ExpiresAt        *time.Time             `json:"expiresAt,omitempty"`
	ReviewedAt       *time.Time             `json:"reviewedAt,omitempty"`
	ReviewedBy       *string                `json:"reviewedBy,omitempty"`
	RejectionReason  *string                `json:"rejectionReason,omitempty"`
}

type PendingAutorouteConnection struct {
	Nodes      []PendingAutoroute `json:"nodes"`
	TotalCount int                `json:"totalCount"`
	PageInfo   *PageInfo          `json:"pageInfo"`
}

type PendingAutorouteStats struct {
	PendingCount  int      `json:"pendingCount"`
	ApprovedCount int      `json:"approvedCount"`
	RejectedCount int      `json:"rejectedCount"`
	ExpiredCount  int      `json:"expiredCount"`
	AvgConfidence *float64 `json:"avgConfidence,omitempty"`
}

type ProfileRevision struct {
	Version       string    `json:"version"`
	CreatedAt     time.Time `json:"createdAt"`
	CreatedBy     *string   `json:"createdBy,omitempty"`
	ChangeSummary *string   `json:"changeSummary,omitempty"`
}

type PublishWorkflowVersionInput struct {
	WorkflowID  string  `json:"workflowId"`
	VersionID   string  `json:"versionId"`
	Environment string  `json:"environment"`
	PublishedBy *string `json:"publishedBy,omitempty"`
}

type QualityDimensions struct {
	Completeness float64 `json:"completeness"`
	Accuracy     float64 `json:"accuracy"`
	Consistency  float64 `json:"consistency"`
	Conformance  float64 `json:"conformance"`
	Timeliness   float64 `json:"timeliness"`
}

type QualityRecommendation struct {
	Priority    int     `json:"priority"`
	Category    *string `json:"category,omitempty"`
	Title       string  `json:"title"`
	Description string  `json:"description"`
	Impact      *string `json:"impact,omitempty"`
}

type Query struct {
}

type RejectPendingAutorouteInput struct {
	ID     string `json:"id"`
	Reason string `json:"reason"`
}

type RejectWorkflowVersionInput struct {
	ApprovalRequestID string  `json:"approvalRequestId"`
	ReviewedBy        *string `json:"reviewedBy,omitempty"`
	Comment           *string `json:"comment,omitempty"`
}

type RequestWorkflowApprovalInput struct {
	WorkflowID      string  `json:"workflowId"`
	TargetVersionID string  `json:"targetVersionId"`
	Environment     string  `json:"environment"`
	RequestedBy     *string `json:"requestedBy,omitempty"`
	Comment         *string `json:"comment,omitempty"`
}

type ResolveMappingInput struct {
	SourceCode     string   `json:"sourceCode"`
	SourceSystem   string   `json:"sourceSystem"`
	SourceDisplay  *string  `json:"sourceDisplay,omitempty"`
	TargetSystem   string   `json:"targetSystem"`
	ProfileID      *string  `json:"profileId,omitempty"`
	AllowAutoroute *bool    `json:"allowAutoroute,omitempty"`
	MinConfidence  *float64 `json:"minConfidence,omitempty"`
}

type ResolveMappingResult struct {
	Found      bool               `json:"found"`
	Decision   AutorouteDecision  `json:"decision"`
	Mapping    *CodeMapping       `json:"mapping,omitempty"`
	Candidates []MappingCandidate `json:"candidates"`
	Confidence *float64           `json:"confidence,omitempty"`
	Reasoning  *string            `json:"reasoning,omitempty"`
	Trace      *AutorouteTrace    `json:"trace,omitempty"`
	DurationMs int                `json:"durationMs"`
}

type RollbackWorkflowVersionInput struct {
	WorkflowID      string  `json:"workflowId"`
	TargetVersionID string  `json:"targetVersionId"`
	Environment     string  `json:"environment"`
	PublishedBy     *string `json:"publishedBy,omitempty"`
}

type RouteExplanation struct {
	Name        string   `json:"name"`
	Trigger     string   `json:"trigger"`
	Actions     []string `json:"actions"`
	Description string   `json:"description"`
}

type SaveWorkflowVersionInput struct {
	WorkflowID string  `json:"workflowId"`
	Yaml       string  `json:"yaml"`
	Notes      *string `json:"notes,omitempty"`
	CreatedBy  *string `json:"createdBy,omitempty"`
}

type SignalReviewDecisionInput struct {
	WorkflowID          string              `json:"workflowId"`
	Approved            bool                `json:"approved"`
	DecidedBy           string              `json:"decidedBy"`
	EquivalenceOverride *MappingEquivalence `json:"equivalenceOverride,omitempty"`
	Comment             *string             `json:"comment,omitempty"`
	RejectionReason     *string             `json:"rejectionReason,omitempty"`
}

type SourceProfile struct {
	ID          string             `json:"id"`
	Name        string             `json:"name"`
	Version     string             `json:"version"`
	CreatedAt   time.Time          `json:"createdAt"`
	UpdatedAt   time.Time          `json:"updatedAt"`
	CreatedBy   *string            `json:"createdBy,omitempty"`
	IsActive    bool               `json:"isActive"`
	Hl7v2       *HL7v2Config       `json:"hl7v2,omitempty"`
	Identifiers *IdentifierConfig  `json:"identifiers,omitempty"`
	Terminology *TerminologyConfig `json:"terminology,omitempty"`
}

type StartTerminologyReviewInput struct {
	SourceCode           string   `json:"sourceCode"`
	SourceSystem         string   `json:"sourceSystem"`
	SourceDisplay        *string  `json:"sourceDisplay,omitempty"`
	TargetSystem         string   `json:"targetSystem"`
	ProfileID            *string  `json:"profileId,omitempty"`
	AutoApproveThreshold *float64 `json:"autoApproveThreshold,omitempty"`
	ReviewTimeoutDays    *int     `json:"reviewTimeoutDays,omitempty"`
}

type StartTerminologyReviewResult struct {
	WorkflowID string `json:"workflowId"`
	RunID      string `json:"runId"`
	Started    bool   `json:"started"`
}

type Subscription struct {
}

type SuggestMappingsInput struct {
	SourceCode    string  `json:"sourceCode"`
	SourceSystem  string  `json:"sourceSystem"`
	SourceDisplay *string `json:"sourceDisplay,omitempty"`
	TargetSystem  string  `json:"targetSystem"`
	MaxCandidates *int    `json:"maxCandidates,omitempty"`
}

type TemporalWorkflow struct {
	ID           string                 `json:"id"`
	RunID        string                 `json:"runId"`
	WorkflowType string                 `json:"workflowType"`
	Status       TemporalWorkflowStatus `json:"status"`
	TaskQueue    string                 `json:"taskQueue"`
	StartTime    time.Time              `json:"startTime"`
	CloseTime    *time.Time             `json:"closeTime,omitempty"`
	DurationMs   *int                   `json:"durationMs,omitempty"`
	Input        map[string]any         `json:"input,omitempty"`
	Result       map[string]any         `json:"result,omitempty"`
	Error        *string                `json:"error,omitempty"`
}

type TemporalWorkflowConnection struct {
	Nodes      []TemporalWorkflow `json:"nodes"`
	TotalCount int                `json:"totalCount"`
	PageInfo   *PageInfo          `json:"pageInfo"`
}

type TemporalWorkflowFilter struct {
	WorkflowType    *string                 `json:"workflowType,omitempty"`
	Status          *TemporalWorkflowStatus `json:"status,omitempty"`
	StartTimeAfter  *time.Time              `json:"startTimeAfter,omitempty"`
	StartTimeBefore *time.Time              `json:"startTimeBefore,omitempty"`
}

type TerminologyConfig struct {
	Mappings []TerminologyMappingTable `json:"mappings"`
}

type TerminologyConfigInput struct {
	Mappings []TerminologyMappingTableInput `json:"mappings,omitempty"`
}

type TerminologyMappingEntry struct {
	SourceCode string  `json:"sourceCode"`
	TargetCode string  `json:"targetCode"`
	Display    *string `json:"display,omitempty"`
}

type TerminologyMappingEntryInput struct {
	SourceCode string  `json:"sourceCode"`
	TargetCode string  `json:"targetCode"`
	Display    *string `json:"display,omitempty"`
}

type TerminologyMappingTable struct {
	ID           string                    `json:"id"`
	SourceSystem string                    `json:"sourceSystem"`
	TargetSystem string                    `json:"targetSystem"`
	Entries      []TerminologyMappingEntry `json:"entries"`
}

type TerminologyMappingTableInput struct {
	ID           string                         `json:"id"`
	SourceSystem string                         `json:"sourceSystem"`
	TargetSystem string                         `json:"targetSystem"`
	Entries      []TerminologyMappingEntryInput `json:"entries,omitempty"`
}

type ToleranceConfig struct {
	MissingSegments       []string `json:"missingSegments"`
	NteAnywhere           bool     `json:"nteAnywhere"`
	ExtraComponents       bool     `json:"extraComponents"`
	UnknownSegments       bool     `json:"unknownSegments"`
	NonStandardDelimiters bool     `json:"nonStandardDelimiters"`
}

type ToleranceConfigInput struct {
	MissingSegments       []string `json:"missingSegments,omitempty"`
	NteAnywhere           *bool    `json:"nteAnywhere,omitempty"`
	ExtraComponents       *bool    `json:"extraComponents,omitempty"`
	UnknownSegments       *bool    `json:"unknownSegments,omitempty"`
	NonStandardDelimiters *bool    `json:"nonStandardDelimiters,omitempty"`
}

type UpdateMappingInput struct {
	ID            string              `json:"id"`
	SourceDisplay *string             `json:"sourceDisplay,omitempty"`
	TargetDisplay *string             `json:"targetDisplay,omitempty"`
	Equivalence   *MappingEquivalence `json:"equivalence,omitempty"`
	Confidence    *float64            `json:"confidence,omitempty"`
	Comment       *string             `json:"comment,omitempty"`
}

type UpdateProfileInput struct {
	Name        *string                 `json:"name,omitempty"`
	Hl7v2       *HL7v2ConfigInput       `json:"hl7v2,omitempty"`
	Identifiers *IdentifierConfigInput  `json:"identifiers,omitempty"`
	Terminology *TerminologyConfigInput `json:"terminology,omitempty"`
}

type UpdateWorkflowDefinitionInput struct {
	ID          string  `json:"id"`
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Status      *string `json:"status,omitempty"`
	UpdatedBy   *string `json:"updatedBy,omitempty"`
}

type UploadBatch struct {
	ID               string                  `json:"id"`
	Filename         string                  `json:"filename"`
	SourceSystem     *string                 `json:"sourceSystem,omitempty"`
	TargetSystem     *string                 `json:"targetSystem,omitempty"`
	ProfileID        *string                 `json:"profileId,omitempty"`
	TotalRows        int                     `json:"totalRows"`
	ValidRows        int                     `json:"validRows"`
	DuplicateRows    int                     `json:"duplicateRows"`
	ErrorRows        int                     `json:"errorRows"`
	UploadedAt       time.Time               `json:"uploadedAt"`
	UploadedBy       *string                 `json:"uploadedBy,omitempty"`
	ValidationErrors []UploadValidationError `json:"validationErrors"`
}

type UploadMappingCSVInput struct {
	CSV                 string  `json:"csv"`
	Filename            string  `json:"filename"`
	DefaultSourceSystem *string `json:"defaultSourceSystem,omitempty"`
	DefaultTargetSystem *string `json:"defaultTargetSystem,omitempty"`
	ProfileID           *string `json:"profileId,omitempty"`
	DryRun              *bool   `json:"dryRun,omitempty"`
}

type UploadMappingResult struct {
	Batch           *UploadBatch  `json:"batch"`
	MappingsCreated int           `json:"mappingsCreated"`
	MappingsSkipped int           `json:"mappingsSkipped"`
	Preview         []CodeMapping `json:"preview"`
}

type UploadValidationError struct {
	Row     int     `json:"row"`
	Column  *string `json:"column,omitempty"`
	Message string  `json:"message"`
}

type ValidationSettingsConfig struct {
	Npi *ValidatorSetting `json:"npi,omitempty"`
	Mbi *ValidatorSetting `json:"mbi,omitempty"`
	Ssn *ValidatorSetting `json:"ssn,omitempty"`
}

type ValidationSettingsInput struct {
	Npi *ValidatorSettingInput `json:"npi,omitempty"`
	Mbi *ValidatorSettingInput `json:"mbi,omitempty"`
	Ssn *ValidatorSettingInput `json:"ssn,omitempty"`
}

type ValidatorSetting struct {
	Enabled   bool   `json:"enabled"`
	OnInvalid string `json:"onInvalid"`
}

type ValidatorSettingInput struct {
	Enabled   bool   `json:"enabled"`
	OnInvalid string `json:"onInvalid"`
}

type WorkflowApprovalRequest struct {
	ID              string     `json:"id"`
	WorkflowID      string     `json:"workflowId"`
	TargetVersionID string     `json:"targetVersionId"`
	Environment     string     `json:"environment"`
	Status          string     `json:"status"`
	RequestedBy     string     `json:"requestedBy"`
	ReviewedBy      *string    `json:"reviewedBy,omitempty"`
	ReviewedAt      *time.Time `json:"reviewedAt,omitempty"`
	Comment         *string    `json:"comment,omitempty"`
}

type WorkflowApprovalRequestFilter struct {
	WorkflowID  *string `json:"workflowId,omitempty"`
	Environment *string `json:"environment,omitempty"`
	Status      *string `json:"status,omitempty"`
}

type WorkflowDefinition struct {
	ID                     string           `json:"id"`
	Name                   string           `json:"name"`
	Description            *string          `json:"description,omitempty"`
	Status                 string           `json:"status"`
	CreatedAt              time.Time        `json:"createdAt"`
	UpdatedAt              time.Time        `json:"updatedAt"`
	LatestVersion          *WorkflowVersion `json:"latestVersion,omitempty"`
	PublishedVersionsByEnv map[string]any   `json:"publishedVersionsByEnv"`
}

type WorkflowDefinitionFilter struct {
	Name   *string `json:"name,omitempty"`
	Status *string `json:"status,omitempty"`
}

type WorkflowExplanation struct {
	Summary           string             `json:"summary"`
	Description       string             `json:"description"`
	RouteExplanations []RouteExplanation `json:"routeExplanations"`
	Diagram           *string            `json:"diagram,omitempty"`
	Warnings          []string           `json:"warnings"`
}

type WorkflowRelease struct {
	ID                    string    `json:"id"`
	WorkflowID            string    `json:"workflowId"`
	Environment           string    `json:"environment"`
	VersionID             string    `json:"versionId"`
	PublishedBy           string    `json:"publishedBy"`
	PublishedAt           time.Time `json:"publishedAt"`
	RollbackFromReleaseID *string   `json:"rollbackFromReleaseId,omitempty"`
}

type WorkflowRun struct {
	ID              string    `json:"id"`
	WorkflowName    string    `json:"workflowName"`
	Environment     string    `json:"environment"`
	VersionID       *string   `json:"versionId,omitempty"`
	EventID         *string   `json:"eventId,omitempty"`
	RoutesMatched   int       `json:"routesMatched"`
	ActionsExecuted int       `json:"actionsExecuted"`
	Errors          []string  `json:"errors"`
	DurationMs      int       `json:"durationMs"`
	StartedAt       time.Time `json:"startedAt"`
	Status          string    `json:"status"`
}

type WorkflowRunFilter struct {
	WorkflowName  *string    `json:"workflowName,omitempty"`
	Environment   *string    `json:"environment,omitempty"`
	Status        *string    `json:"status,omitempty"`
	FromStartedAt *time.Time `json:"fromStartedAt,omitempty"`
	ToStartedAt   *time.Time `json:"toStartedAt,omitempty"`
}

type WorkflowValidation struct {
	Valid    bool     `json:"valid"`
	Errors   []string `json:"errors"`
	Warnings []string `json:"warnings"`
	Info     []string `json:"info"`
}

type WorkflowVersion struct {
	ID            string              `json:"id"`
	WorkflowID    string              `json:"workflowId"`
	VersionNumber int                 `json:"versionNumber"`
	Yaml          string              `json:"yaml"`
	Validation    *WorkflowValidation `json:"validation"`
	CreatedBy     string              `json:"createdBy"`
	CreatedAt     time.Time           `json:"createdAt"`
	Notes         *string             `json:"notes,omitempty"`
}

type AutorouteDecision string

const (
	AutorouteDecisionPersistentHit     AutorouteDecision = "PERSISTENT_HIT"
	AutorouteDecisionAutorouteHighConf AutorouteDecision = "AUTOROUTE_HIGH_CONF"
	AutorouteDecisionAutorouteMedConf  AutorouteDecision = "AUTOROUTE_MED_CONF"
	AutorouteDecisionAutorouteLowConf  AutorouteDecision = "AUTOROUTE_LOW_CONF"
	AutorouteDecisionNoMatch           AutorouteDecision = "NO_MATCH"
)

var AllAutorouteDecision = []AutorouteDecision{
	AutorouteDecisionPersistentHit,
	AutorouteDecisionAutorouteHighConf,
	AutorouteDecisionAutorouteMedConf,
	AutorouteDecisionAutorouteLowConf,
	AutorouteDecisionNoMatch,
}

func (e AutorouteDecision) IsValid() bool {
	switch e {
	case AutorouteDecisionPersistentHit, AutorouteDecisionAutorouteHighConf, AutorouteDecisionAutorouteMedConf, AutorouteDecisionAutorouteLowConf, AutorouteDecisionNoMatch:
		return true
	}
	return false
}

func (e AutorouteDecision) String() string {
	return string(e)
}

func (e *AutorouteDecision) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AutorouteDecision(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AutorouteDecision", str)
	}
	return nil
}

func (e AutorouteDecision) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AutorouteDecision) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AutorouteDecision) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MappingEquivalence string

const (
	MappingEquivalenceEquivalent MappingEquivalence = "EQUIVALENT"
	MappingEquivalenceWider      MappingEquivalence = "WIDER"
	MappingEquivalenceNarrower   MappingEquivalence = "NARROWER"
	MappingEquivalenceInexact    MappingEquivalence = "INEXACT"
)

var AllMappingEquivalence = []MappingEquivalence{
	MappingEquivalenceEquivalent,
	MappingEquivalenceWider,
	MappingEquivalenceNarrower,
	MappingEquivalenceInexact,
}

func (e MappingEquivalence) IsValid() bool {
	switch e {
	case MappingEquivalenceEquivalent, MappingEquivalenceWider, MappingEquivalenceNarrower, MappingEquivalenceInexact:
		return true
	}
	return false
}

func (e MappingEquivalence) String() string {
	return string(e)
}

func (e *MappingEquivalence) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MappingEquivalence(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MappingEquivalence", str)
	}
	return nil
}

func (e MappingEquivalence) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MappingEquivalence) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MappingEquivalence) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type MappingOrigin string

const (
	MappingOriginCSVUpload         MappingOrigin = "CSV_UPLOAD"
	MappingOriginApprovedAutoroute MappingOrigin = "APPROVED_AUTOROUTE"
	MappingOriginManual            MappingOrigin = "MANUAL"
)

var AllMappingOrigin = []MappingOrigin{
	MappingOriginCSVUpload,
	MappingOriginApprovedAutoroute,
	MappingOriginManual,
}

func (e MappingOrigin) IsValid() bool {
	switch e {
	case MappingOriginCSVUpload, MappingOriginApprovedAutoroute, MappingOriginManual:
		return true
	}
	return false
}

func (e MappingOrigin) String() string {
	return string(e)
}

func (e *MappingOrigin) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MappingOrigin(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MappingOrigin", str)
	}
	return nil
}

func (e MappingOrigin) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MappingOrigin) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MappingOrigin) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PendingAutorouteStatus string

const (
	PendingAutorouteStatusPending  PendingAutorouteStatus = "PENDING"
	PendingAutorouteStatusApproved PendingAutorouteStatus = "APPROVED"
	PendingAutorouteStatusRejected PendingAutorouteStatus = "REJECTED"
	PendingAutorouteStatusExpired  PendingAutorouteStatus = "EXPIRED"
)

var AllPendingAutorouteStatus = []PendingAutorouteStatus{
	PendingAutorouteStatusPending,
	PendingAutorouteStatusApproved,
	PendingAutorouteStatusRejected,
	PendingAutorouteStatusExpired,
}

func (e PendingAutorouteStatus) IsValid() bool {
	switch e {
	case PendingAutorouteStatusPending, PendingAutorouteStatusApproved, PendingAutorouteStatusRejected, PendingAutorouteStatusExpired:
		return true
	}
	return false
}

func (e PendingAutorouteStatus) String() string {
	return string(e)
}

func (e *PendingAutorouteStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PendingAutorouteStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PendingAutorouteStatus", str)
	}
	return nil
}

func (e PendingAutorouteStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PendingAutorouteStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PendingAutorouteStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TemporalWorkflowStatus string

const (
	TemporalWorkflowStatusRunning        TemporalWorkflowStatus = "RUNNING"
	TemporalWorkflowStatusCompleted      TemporalWorkflowStatus = "COMPLETED"
	TemporalWorkflowStatusFailed         TemporalWorkflowStatus = "FAILED"
	TemporalWorkflowStatusCanceled       TemporalWorkflowStatus = "CANCELED"
	TemporalWorkflowStatusTerminated     TemporalWorkflowStatus = "TERMINATED"
	TemporalWorkflowStatusContinuedAsNew TemporalWorkflowStatus = "CONTINUED_AS_NEW"
	TemporalWorkflowStatusTimedOut       TemporalWorkflowStatus = "TIMED_OUT"
)

var AllTemporalWorkflowStatus = []TemporalWorkflowStatus{
	TemporalWorkflowStatusRunning,
	TemporalWorkflowStatusCompleted,
	TemporalWorkflowStatusFailed,
	TemporalWorkflowStatusCanceled,
	TemporalWorkflowStatusTerminated,
	TemporalWorkflowStatusContinuedAsNew,
	TemporalWorkflowStatusTimedOut,
}

func (e TemporalWorkflowStatus) IsValid() bool {
	switch e {
	case TemporalWorkflowStatusRunning, TemporalWorkflowStatusCompleted, TemporalWorkflowStatusFailed, TemporalWorkflowStatusCanceled, TemporalWorkflowStatusTerminated, TemporalWorkflowStatusContinuedAsNew, TemporalWorkflowStatusTimedOut:
		return true
	}
	return false
}

func (e TemporalWorkflowStatus) String() string {
	return string(e)
}

func (e *TemporalWorkflowStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TemporalWorkflowStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TemporalWorkflowStatus", str)
	}
	return nil
}

func (e TemporalWorkflowStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TemporalWorkflowStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TemporalWorkflowStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
