apiVersion: v2
name: fi-fhir
description: Healthcare integration platform for transforming HL7v2, CSV, and EDI into FHIR
icon: https://gitlab.flexinfer.ai/libs/fi-fhir/-/raw/main/assets/icon.png

type: application
version: 0.1.0
appVersion: "0.1.0"

keywords:
  - healthcare
  - fhir
  - hl7
  - edi
  - integration

home: https://gitlab.flexinfer.ai/libs/fi-fhir
sources:
  - https://gitlab.flexinfer.ai/libs/fi-fhir

maintainers:
  - name: fi-fhir
    url: https://gitlab.flexinfer.ai/libs/fi-fhir

annotations:
  category: Healthcare
  licenses: Apache-2.0
