package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"bytes"
	"context"
	"fmt"
	"strconv"
	"strings"
	"time"

	"github.com/google/uuid"
	graphql1 "gitlab.flexinfer.ai/libs/fi-fhir/internal/api/graphql"
	"gitlab.flexinfer.ai/libs/fi-fhir/internal/api/graphql/model"
	"gitlab.flexinfer.ai/libs/fi-fhir/internal/api/graphql/store"
	"gitlab.flexinfer.ai/libs/fi-fhir/internal/fhir/subscription"
	"gitlab.flexinfer.ai/libs/fi-fhir/internal/llm/extract"
	"gitlab.flexinfer.ai/libs/fi-fhir/internal/llm/quality"
	"gitlab.flexinfer.ai/libs/fi-fhir/internal/parser/cda"
	"gitlab.flexinfer.ai/libs/fi-fhir/internal/parser/csv"
	"gitlab.flexinfer.ai/libs/fi-fhir/internal/parser/edi"
	"gitlab.flexinfer.ai/libs/fi-fhir/internal/parser/fhir"
	"gitlab.flexinfer.ai/libs/fi-fhir/internal/parser/hl7v2"
	"gitlab.flexinfer.ai/libs/fi-fhir/pkg/llm/copilot"
	termdb "gitlab.flexinfer.ai/libs/fi-fhir/pkg/terminology/db"
	"gitlab.flexinfer.ai/libs/fi-fhir/pkg/terminology/upload"
)

// SubmitMessage is the resolver for the submitMessage field.
func (r *mutationResolver) SubmitMessage(ctx context.Context, input model.SubmitMessageInput) (*model.SubmitResult, error) {
	result := &model.SubmitResult{
		Warnings:        []model.ParseWarning{},
		Errors:          []string{},
		WorkflowResults: []model.WorkflowResult{},
	}

	// Parse the message based on format
	var parsedEvents []interface{}

	switch input.Format {
	case model.SourceFormatHL7v2:
		parser := hl7v2.NewParser(input.Source, hl7v2.ParserConfig{})
		parseResult, err := parser.ParseWithResult(input.Data)
		if err != nil {
			result.Errors = append(result.Errors, err.Error())
			return result, nil
		}
		if parseResult.Event != nil {
			parsedEvents = append(parsedEvents, parseResult.Event)
		}
		for _, w := range parseResult.Warnings {
			result.Warnings = append(result.Warnings, model.ParseWarning{
				Phase:   w.Phase,
				Code:    w.Code,
				Message: w.Message,
				Path:    strPtr(w.Path),
			})
		}

	case model.SourceFormatFHIR:
		parser := fhir.NewParser(input.Source)
		parseResult, err := parser.ParseWithResult([]byte(input.Data))
		if err != nil {
			result.Errors = append(result.Errors, err.Error())
			return result, nil
		}
		parsedEvents = parseResult.Events
		for _, w := range parseResult.Warnings {
			result.Warnings = append(result.Warnings, model.ParseWarning{
				Phase:   w.Phase,
				Code:    w.Code,
				Message: w.Message,
			})
		}

	case model.SourceFormatCSV:
		parser := csv.NewParser(input.Source, csv.ParserConfig{})
		parseResult, err := parser.Parse(bytes.NewReader([]byte(input.Data)))
		if err != nil {
			result.Errors = append(result.Errors, err.Error())
			return result, nil
		}
		parsedEvents = parseResult.Events
		for _, w := range parseResult.Warnings {
			result.Warnings = append(result.Warnings, model.ParseWarning{
				Phase:   w.Phase,
				Code:    w.Code,
				Message: w.Message,
				Path:    strPtr(w.Path),
			})
		}

	case model.SourceFormatCDA:
		parser := cda.NewParser(input.Source, nil)
		doc, err := parser.Parse([]byte(input.Data))
		if err != nil {
			result.Errors = append(result.Errors, err.Error())
			return result, nil
		}
		mapper := cda.NewMapper(nil)
		mapResult, err := mapper.Map(doc)
		if err != nil {
			result.Errors = append(result.Errors, err.Error())
			return result, nil
		}
		parsedEvents = mapResult.Events

	case model.SourceFormatEDI837, model.SourceFormatEDI835:
		parser := edi.NewParser()
		parseResult, err := parser.Parse(input.Data)
		if err != nil {
			result.Errors = append(result.Errors, err.Error())
			return result, nil
		}
		// Convert EDI interchange to events using mappers
		if parseResult.Interchange != nil {
			for _, fg := range parseResult.Interchange.FunctionalGroups {
				for _, tx := range fg.Transactions {
					var evts []interface{}
					switch tx.SetIdentifier {
					case "837":
						claims, mapErr := edi.Map837ToEvents(tx, input.Source)
						if mapErr == nil {
							for _, c := range claims {
								evts = append(evts, c)
							}
						}
					case "835":
						rems, mapErr := edi.Map835ToEvents(tx, input.Source)
						if mapErr == nil {
							for _, r := range rems {
								evts = append(evts, r)
							}
						}
					}
					parsedEvents = append(parsedEvents, evts...)
				}
			}
		}
		for _, w := range parseResult.Warnings {
			result.Warnings = append(result.Warnings, model.ParseWarning{
				Phase:   w.Phase,
				Code:    w.Code,
				Message: w.Message,
			})
		}

	default:
		result.Errors = append(result.Errors, fmt.Sprintf("unsupported format: %s", input.Format))
		return result, nil
	}

	// Convert and store events
	for _, evt := range parsedEvents {
		gqlEvent := convertToGraphQLEvent(evt, input.Source, input.Format, input.CorrelationID)
		if gqlEvent != nil {
			id, err := r.Store.SaveEvent(ctx, gqlEvent)
			if err != nil {
				result.Errors = append(result.Errors, err.Error())
			} else {
				result.EventID = &id
			}
		}
	}

	// Execute workflows if available
	if r.WorkflowEngine != nil && len(parsedEvents) > 0 {
		for _, evt := range parsedEvents {
			wfResult := r.WorkflowEngine.Process(evt)

			// Count matched routes and actions
			routesMatched := 0
			actionsExecuted := 0
			var errors []string

			for _, rr := range wfResult.RouteResults {
				if rr.Matched {
					routesMatched++
					actionsExecuted += rr.ActionsRun
					for _, err := range rr.ActionErrors {
						errors = append(errors, err.Error())
					}
				}
			}

			result.WorkflowResults = append(result.WorkflowResults, model.WorkflowResult{
				WorkflowName:    "default",
				RoutesMatched:   routesMatched,
				ActionsExecuted: actionsExecuted,
				Errors:          errors,
				Duration:        0,
			})
		}
	}

	result.Success = len(result.Errors) == 0
	return result, nil
}

// SubmitEvent is the resolver for the submitEvent field.
func (r *mutationResolver) SubmitEvent(ctx context.Context, input model.SubmitEventInput) (*model.SubmitResult, error) {
	result := &model.SubmitResult{
		Warnings:        []model.ParseWarning{},
		Errors:          []string{},
		WorkflowResults: []model.WorkflowResult{},
	}

	// Create event from input data
	event, err := createEventFromInput(input)
	if err != nil {
		result.Errors = append(result.Errors, err.Error())
		return result, nil
	}

	// Store the event
	id, err := r.Store.SaveEvent(ctx, event)
	if err != nil {
		result.Errors = append(result.Errors, err.Error())
		return result, nil
	}

	result.EventID = &id
	result.Success = true
	return result, nil
}

// SubmitBatch is the resolver for the submitBatch field.
func (r *mutationResolver) SubmitBatch(ctx context.Context, input model.SubmitBatchInput) (*model.BatchResult, error) {
	startTime := time.Now()

	// Calculate total items
	totalItems := len(input.Messages) + len(input.Events)
	if totalItems == 0 {
		return &model.BatchResult{
			TotalItems:   0,
			SuccessCount: 0,
			FailureCount: 0,
			Results:      []model.BatchItemResult{},
			DurationMs:   0,
		}, nil
	}

	// Enforce max batch size (prevent DoS)
	const maxBatchSize = 1000
	if totalItems > maxBatchSize {
		return nil, fmt.Errorf("batch size %d exceeds maximum of %d", totalItems, maxBatchSize)
	}

	stopOnError := input.StopOnError != nil && *input.StopOnError
	parallel := input.Parallel != nil && *input.Parallel

	results := make([]model.BatchItemResult, 0, totalItems)
	var successCount, failureCount int

	// Process messages
	if len(input.Messages) > 0 {
		messageResults := r.processBatchMessages(ctx, input.Messages, stopOnError, parallel)
		for _, res := range messageResults {
			if res.Success {
				successCount++
			} else {
				failureCount++
			}
		}
		results = append(results, messageResults...)

		// Check stop on error
		if stopOnError && failureCount > 0 {
			return &model.BatchResult{
				TotalItems:   totalItems,
				SuccessCount: successCount,
				FailureCount: failureCount,
				Results:      results,
				DurationMs:   int(time.Since(startTime).Milliseconds()),
			}, nil
		}
	}

	// Process pre-parsed events
	if len(input.Events) > 0 {
		// Adjust indices to continue from messages
		baseIndex := len(input.Messages)
		eventResults := r.processBatchEvents(ctx, input.Events, baseIndex, stopOnError, parallel)
		for _, res := range eventResults {
			if res.Success {
				successCount++
			} else {
				failureCount++
			}
		}
		results = append(results, eventResults...)
	}

	return &model.BatchResult{
		TotalItems:   totalItems,
		SuccessCount: successCount,
		FailureCount: failureCount,
		Results:      results,
		DurationMs:   int(time.Since(startTime).Milliseconds()),
	}, nil
}

// TriggerWorkflow is the resolver for the triggerWorkflow field.
func (r *mutationResolver) TriggerWorkflow(ctx context.Context, name string, event map[string]any) (*model.WorkflowResult, error) {
	if r.WorkflowEngine == nil {
		return nil, fmt.Errorf("workflow engine not configured")
	}

	// Process the event through the workflow engine
	// The engine accepts interface{}, so we can pass the map directly
	startTime := time.Now()
	wfResult := r.WorkflowEngine.ProcessWithContext(ctx, event)
	duration := time.Since(startTime).Milliseconds()

	// Collect matched routes and actions
	routesMatchedCount := 0
	actionsExecutedCount := 0
	var errors []string
	var routeNames []string
	var actionsSummary []string

	for _, rr := range wfResult.RouteResults {
		if rr.Matched {
			routesMatchedCount++
			routeNames = append(routeNames, rr.RouteName)
			actionsExecutedCount += rr.ActionsRun
			// Record how many actions ran for this route
			if rr.ActionsRun > 0 {
				actionsSummary = append(actionsSummary, fmt.Sprintf("%s:%d", rr.RouteName, rr.ActionsRun))
			}
			for _, err := range rr.ActionErrors {
				errors = append(errors, err.Error())
			}
			for _, err := range rr.TransformErrors {
				errors = append(errors, err.Error())
			}
		}
	}

	// Broadcast to workflow event subscribers
	notification := &model.WorkflowEventNotification{
		Event:           nil, // Raw map can't be converted to Event interface
		Workflow:        name,
		RoutesMatched:   routeNames,
		ActionsExecuted: actionsSummary,
		Duration:        int(duration),
	}
	r.broadcastWorkflowEvent(notification)

	return &model.WorkflowResult{
		WorkflowName:    name,
		RoutesMatched:   routesMatchedCount,
		ActionsExecuted: actionsExecutedCount,
		Errors:          errors,
		Duration:        int(duration),
	}, nil
}

// CreateFhirSubscription is the resolver for the createFhirSubscription field.
func (r *mutationResolver) CreateFhirSubscription(ctx context.Context, input model.CreateSubscriptionInput) (*model.FhirSubscription, error) {
	// Get or create a client for this FHIR server
	client, err := r.getOrCreateSubscriptionClient(input.Server)
	if err != nil {
		return nil, fmt.Errorf("create subscription client: %w", err)
	}

	// Build the FHIR Subscription resource
	sub := &subscription.Subscription{
		Status:   subscription.StatusRequested,
		Reason:   input.Name,
		Criteria: input.Criteria,
		Channel: subscription.Channel{
			Type:     subscription.ChannelRestHook,
			Endpoint: input.Endpoint,
			Payload:  "application/fhir+json",
		},
	}

	// Create on the FHIR server
	created, err := client.Create(ctx, sub)
	if err != nil {
		return nil, fmt.Errorf("create subscription on server: %w", err)
	}

	// Store locally for tracking
	record := &SubscriptionRecord{
		ID:        created.ID,
		Name:      input.Name,
		Server:    input.Server,
		Criteria:  input.Criteria,
		Endpoint:  input.Endpoint,
		Status:    string(created.Status),
		CreatedAt: time.Now(),
	}
	r.storeSubscriptionRecord(record)

	return &model.FhirSubscription{
		ID:        created.ID,
		Name:      input.Name,
		Status:    string(created.Status),
		Criteria:  input.Criteria,
		Server:    input.Server,
		Endpoint:  input.Endpoint,
		CreatedAt: record.CreatedAt,
	}, nil
}

// DeleteFhirSubscription is the resolver for the deleteFhirSubscription field.
func (r *mutationResolver) DeleteFhirSubscription(ctx context.Context, id string) (bool, error) {
	// Look up the subscription to get the server
	record, exists := r.getSubscriptionRecord(id)
	if !exists {
		return false, fmt.Errorf("subscription not found: %s", id)
	}

	// Get the client for this server
	client, err := r.getOrCreateSubscriptionClient(record.Server)
	if err != nil {
		return false, fmt.Errorf("get subscription client: %w", err)
	}

	// Delete from the FHIR server
	if err := client.Delete(ctx, id); err != nil {
		return false, fmt.Errorf("delete subscription: %w", err)
	}

	// Remove local record
	r.deleteSubscriptionRecord(id)

	return true, nil
}

// PauseFhirSubscription is the resolver for the pauseFhirSubscription field.
func (r *mutationResolver) PauseFhirSubscription(ctx context.Context, id string) (*model.FhirSubscription, error) {
	// Look up the subscription
	record, exists := r.getSubscriptionRecord(id)
	if !exists {
		return nil, fmt.Errorf("subscription not found: %s", id)
	}

	// Get the client for this server
	client, err := r.getOrCreateSubscriptionClient(record.Server)
	if err != nil {
		return nil, fmt.Errorf("get subscription client: %w", err)
	}

	// Pause on the FHIR server
	if err := client.Pause(ctx, id); err != nil {
		return nil, fmt.Errorf("pause subscription: %w", err)
	}

	// Update local status
	r.updateSubscriptionStatus(id, string(subscription.StatusOff))

	return &model.FhirSubscription{
		ID:        record.ID,
		Name:      record.Name,
		Status:    string(subscription.StatusOff),
		Criteria:  record.Criteria,
		Server:    record.Server,
		Endpoint:  record.Endpoint,
		CreatedAt: record.CreatedAt,
	}, nil
}

// ResumeFhirSubscription is the resolver for the resumeFhirSubscription field.
func (r *mutationResolver) ResumeFhirSubscription(ctx context.Context, id string) (*model.FhirSubscription, error) {
	// Look up the subscription
	record, exists := r.getSubscriptionRecord(id)
	if !exists {
		return nil, fmt.Errorf("subscription not found: %s", id)
	}

	// Get the client for this server
	client, err := r.getOrCreateSubscriptionClient(record.Server)
	if err != nil {
		return nil, fmt.Errorf("get subscription client: %w", err)
	}

	// Resume on the FHIR server
	if err := client.Resume(ctx, id); err != nil {
		return nil, fmt.Errorf("resume subscription: %w", err)
	}

	// Update local status (server will activate, so we mark as requested)
	r.updateSubscriptionStatus(id, string(subscription.StatusRequested))

	return &model.FhirSubscription{
		ID:        record.ID,
		Name:      record.Name,
		Status:    string(subscription.StatusRequested),
		Criteria:  record.Criteria,
		Server:    record.Server,
		Endpoint:  record.Endpoint,
		CreatedAt: record.CreatedAt,
	}, nil
}

// CreateProfile is the resolver for the createProfile field.
func (r *mutationResolver) CreateProfile(ctx context.Context, input model.CreateProfileInput) (*model.SourceProfile, error) {
	if r.ProfileStore == nil {
		return nil, fmt.Errorf("profile store not configured")
	}

	profile := &store.Profile{
		ID:       input.ID,
		Name:     input.Name,
		Version:  "1.0.0",
		Config:   []byte("{}"),
		IsActive: true,
	}

	if err := r.ProfileStore.CreateProfile(ctx, profile); err != nil {
		return nil, fmt.Errorf("create profile: %w", err)
	}

	// Fetch the created profile to get timestamps
	created, err := r.ProfileStore.GetProfile(ctx, input.ID)
	if err != nil {
		return nil, fmt.Errorf("get created profile: %w", err)
	}

	return convertStoreProfileToGraphQL(created)
}

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, id string, input model.UpdateProfileInput) (*model.SourceProfile, error) {
	if r.ProfileStore == nil {
		return nil, fmt.Errorf("profile store not configured")
	}

	// Get existing profile
	existing, err := r.ProfileStore.GetProfile(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("get profile: %w", err)
	}
	if existing == nil {
		return nil, fmt.Errorf("profile not found: %s", id)
	}

	// Update fields
	if input.Name != nil {
		existing.Name = *input.Name
	}

	// Convert GraphQL config to JSON
	configJSON, err := convertGraphQLConfigToJSON(input)
	if err != nil {
		return nil, fmt.Errorf("convert config: %w", err)
	}
	existing.Config = configJSON

	// Increment version
	existing.Version = incrementVersion(existing.Version)

	if err := r.ProfileStore.UpdateProfile(ctx, existing); err != nil {
		return nil, fmt.Errorf("update profile: %w", err)
	}

	// Fetch updated profile
	updated, err := r.ProfileStore.GetProfile(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("get updated profile: %w", err)
	}

	return convertStoreProfileToGraphQL(updated)
}

// DeleteProfile is the resolver for the deleteProfile field.
func (r *mutationResolver) DeleteProfile(ctx context.Context, id string) (bool, error) {
	if r.ProfileStore == nil {
		return false, fmt.Errorf("profile store not configured")
	}

	if err := r.ProfileStore.DeleteProfile(ctx, id); err != nil {
		return false, fmt.Errorf("delete profile: %w", err)
	}

	return true, nil
}

// DuplicateProfile is the resolver for the duplicateProfile field.
func (r *mutationResolver) DuplicateProfile(ctx context.Context, id string, newID string, newName string) (*model.SourceProfile, error) {
	if r.ProfileStore == nil {
		return nil, fmt.Errorf("profile store not configured")
	}

	duplicated, err := r.ProfileStore.DuplicateProfile(ctx, id, newID, newName)
	if err != nil {
		return nil, fmt.Errorf("duplicate profile: %w", err)
	}

	return convertStoreProfileToGraphQL(duplicated)
}

// GenerateWorkflow generates a workflow from natural language description.
func (r *mutationResolver) GenerateWorkflow(ctx context.Context, input model.GenerateWorkflowInput) (*model.GeneratedWorkflow, error) {
	// Return graceful degradation if copilot not configured
	if r.WorkflowCopilot == nil {
		return &model.GeneratedWorkflow{
			Yaml:        "# Workflow generation not available (copilot not configured)",
			Explanation: "LLM workflow generation is not configured",
			Warnings:    []string{"Workflow copilot service not available"},
		}, nil
	}

	// Build generation request
	req := copilot.GenerateRequest{
		Description: input.Description,
		EventTypes:  input.EventTypes,
		ActionTypes: input.ActionTypes,
	}

	// Generate workflow
	result, err := r.WorkflowCopilot.Generate(ctx, req)
	if err != nil {
		return nil, fmt.Errorf("generate workflow: %w", err)
	}

	// Convert to GraphQL model
	warnings := result.Warnings
	if warnings == nil {
		warnings = []string{}
	}

	return &model.GeneratedWorkflow{
		Yaml:        result.YAML,
		Explanation: result.Explanation,
		Warnings:    warnings,
	}, nil
}

// UploadMappingCSV is the resolver for the uploadMappingCSV field.
func (r *mutationResolver) UploadMappingCSV(ctx context.Context, input model.UploadMappingCSVInput) (*model.UploadMappingResult, error) {
	if r.MappingStore == nil {
		return nil, fmt.Errorf("terminology mapping store not configured")
	}

	// Configure parser
	opts := upload.ParseOptions{
		MaxRows: 10000, // Reasonable limit for uploads
	}
	if input.DefaultSourceSystem != nil {
		opts.DefaultSourceSystem = *input.DefaultSourceSystem
	}
	if input.DefaultTargetSystem != nil {
		opts.DefaultTargetSystem = *input.DefaultTargetSystem
	}

	// Parse CSV
	parser := upload.NewParser(opts)
	parseResult, err := parser.Parse(strings.NewReader(input.CSV))
	if err != nil {
		return nil, fmt.Errorf("parsing CSV: %w", err)
	}

	// Convert validation errors
	validationErrors := make([]model.UploadValidationError, 0, len(parseResult.Errors))
	for _, e := range parseResult.Errors {
		ve := model.UploadValidationError{
			Row:     e.Row,
			Message: e.Message,
		}
		if e.Column != "" {
			ve.Column = &e.Column
		}
		validationErrors = append(validationErrors, ve)
	}

	// Build result
	result := &model.UploadMappingResult{
		MappingsCreated: 0,
		MappingsSkipped: 0,
		Preview:         []model.CodeMapping{},
	}

	// Dry run: just return preview without persisting
	isDryRun := input.DryRun != nil && *input.DryRun
	if isDryRun {
		// Generate preview of first 100 valid rows
		limit := 100
		if len(parseResult.Rows) < limit {
			limit = len(parseResult.Rows)
		}
		for i := 0; i < limit; i++ {
			row := parseResult.Rows[i]
			preview := model.CodeMapping{
				ID:           fmt.Sprintf("preview-%d", i),
				SourceSystem: row.SourceSystem,
				SourceCode:   row.SourceCode,
				TargetSystem: row.TargetSystem,
				TargetCode:   row.TargetCode,
				Equivalence:  toGraphQLEquivalence(row.Equivalence),
				Origin:       model.MappingOriginCSVUpload,
				CreatedAt:    time.Now(),
			}
			if row.SourceDisplay != "" {
				preview.SourceDisplay = &row.SourceDisplay
			}
			if row.TargetDisplay != "" {
				preview.TargetDisplay = &row.TargetDisplay
			}
			if row.Confidence != nil {
				preview.Confidence = row.Confidence
			}
			if row.Comment != "" {
				preview.Comment = &row.Comment
			}
			if input.ProfileID != nil {
				preview.ProfileID = input.ProfileID
			}
			result.Preview = append(result.Preview, preview)
		}

		// Return dummy batch for preview
		result.Batch = &model.UploadBatch{
			ID:               "preview",
			Filename:         input.Filename,
			TotalRows:        parseResult.TotalRows,
			ValidRows:        parseResult.ValidRows,
			ErrorRows:        parseResult.ErrorRows,
			DuplicateRows:    0,
			UploadedAt:       time.Now(),
			ValidationErrors: validationErrors,
		}
		if input.DefaultSourceSystem != nil {
			result.Batch.SourceSystem = input.DefaultSourceSystem
		}
		if input.DefaultTargetSystem != nil {
			result.Batch.TargetSystem = input.DefaultTargetSystem
		}
		if input.ProfileID != nil {
			result.Batch.ProfileID = input.ProfileID
		}

		return result, nil
	}

	// Create batch record
	batch := &termdb.UploadBatch{
		Filename:  input.Filename,
		TotalRows: parseResult.TotalRows,
		ValidRows: parseResult.ValidRows,
		ErrorRows: parseResult.ErrorRows,
	}
	if input.DefaultSourceSystem != nil {
		batch.SourceSystem = *input.DefaultSourceSystem
	}
	if input.DefaultTargetSystem != nil {
		batch.TargetSystem = *input.DefaultTargetSystem
	}
	if input.ProfileID != nil {
		batch.ProfileID = *input.ProfileID
	}
	for _, e := range parseResult.Errors {
		batch.ValidationErrors = append(batch.ValidationErrors, termdb.ValidationError{
			Row:     e.Row,
			Column:  e.Column,
			Message: e.Message,
		})
	}

	if err := r.MappingStore.CreateBatch(ctx, batch); err != nil {
		return nil, fmt.Errorf("creating batch record: %w", err)
	}

	// Create mappings from valid rows
	var mappings []*termdb.CustomMapping
	for _, row := range parseResult.Rows {
		m := &termdb.CustomMapping{
			SourceSystem:  row.SourceSystem,
			SourceCode:    row.SourceCode,
			SourceDisplay: row.SourceDisplay,
			TargetSystem:  row.TargetSystem,
			TargetCode:    row.TargetCode,
			TargetDisplay: row.TargetDisplay,
			Equivalence:   row.Equivalence,
			Confidence:    row.Confidence,
			Comment:       row.Comment,
			Origin:        termdb.OriginCSVUpload,
			UploadBatchID: &batch.ID,
		}
		if input.ProfileID != nil {
			m.ProfileID = *input.ProfileID
		}
		mappings = append(mappings, m)
	}

	created, skipped, err := r.MappingStore.CreateMappingsBatch(ctx, mappings)
	if err != nil {
		return nil, fmt.Errorf("creating mappings: %w", err)
	}

	// Update batch with duplicate count
	batch.DuplicateRows = skipped

	result.MappingsCreated = created
	result.MappingsSkipped = skipped
	result.Batch = toGraphQLBatch(batch)

	return result, nil
}

// CreateMapping is the resolver for the createMapping field.
func (r *mutationResolver) CreateMapping(ctx context.Context, input model.CreateMappingInput) (*model.CodeMapping, error) {
	if r.MappingStore == nil {
		return nil, fmt.Errorf("terminology mapping store not configured")
	}

	mapping := &termdb.CustomMapping{
		SourceSystem: input.SourceSystem,
		SourceCode:   input.SourceCode,
		TargetSystem: input.TargetSystem,
		TargetCode:   input.TargetCode,
		Origin:       termdb.OriginManual,
		Equivalence:  termdb.EquivalenceEquivalent, // Default
	}
	if input.SourceDisplay != nil {
		mapping.SourceDisplay = *input.SourceDisplay
	}
	if input.TargetDisplay != nil {
		mapping.TargetDisplay = *input.TargetDisplay
	}
	if input.Equivalence != nil {
		mapping.Equivalence = toDBEquivalence(*input.Equivalence)
	}
	if input.Comment != nil {
		mapping.Comment = *input.Comment
	}
	if input.ProfileID != nil {
		mapping.ProfileID = *input.ProfileID
	}

	if err := r.MappingStore.CreateMapping(ctx, mapping); err != nil {
		return nil, fmt.Errorf("creating mapping: %w", err)
	}

	return toGraphQLMapping(mapping), nil
}

// DeleteMapping is the resolver for the deleteMapping field.
func (r *mutationResolver) DeleteMapping(ctx context.Context, id string) (bool, error) {
	if r.MappingStore == nil {
		return false, fmt.Errorf("terminology mapping store not configured")
	}

	mappingID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return false, fmt.Errorf("invalid mapping ID: %w", err)
	}

	err = r.MappingStore.DeleteMapping(ctx, mappingID)
	if err != nil {
		// Check if it's a "not found" error
		if strings.Contains(err.Error(), "not found") {
			return false, nil
		}
		return false, fmt.Errorf("deleting mapping: %w", err)
	}

	return true, nil
}

// DeleteMappingBatch is the resolver for the deleteMappingBatch field.
func (r *mutationResolver) DeleteMappingBatch(ctx context.Context, batchID string) (int, error) {
	if r.MappingStore == nil {
		return 0, fmt.Errorf("terminology mapping store not configured")
	}

	batchUUID, err := uuid.Parse(batchID)
	if err != nil {
		return 0, fmt.Errorf("invalid batch ID: %w", err)
	}

	count, err := r.MappingStore.DeleteMappingsByBatch(ctx, batchUUID)
	if err != nil {
		return 0, fmt.Errorf("deleting batch mappings: %w", err)
	}

	return int(count), nil
}

// Event is the resolver for the event field.
func (r *queryResolver) Event(ctx context.Context, id string) (model.Event, error) {
	return r.Store.GetEvent(ctx, id)
}

// Events is the resolver for the events field.
func (r *queryResolver) Events(ctx context.Context, filter *model.EventFilter, first *int, after *string, orderBy *model.EventOrderBy) (*model.EventConnection, error) {
	limit := 100
	if first != nil {
		limit = *first
	}
	return r.Store.QueryEvents(ctx, filter, limit, after, orderBy)
}

// Patient is the resolver for the patient field.
func (r *queryResolver) Patient(ctx context.Context, mrn string) (*model.Patient, error) {
	return r.Store.GetPatient(ctx, mrn)
}

// Patients is the resolver for the patients field.
func (r *queryResolver) Patients(ctx context.Context, filter *model.PatientFilter, first *int, after *string) (*model.PatientConnection, error) {
	limit := 100
	if first != nil {
		limit = *first
	}
	return r.Store.QueryPatients(ctx, filter, limit, after)
}

// Workflow is the resolver for the workflow field.
func (r *queryResolver) Workflow(ctx context.Context, name string) (*model.WorkflowStatus, error) {
	if r.WorkflowEngine == nil {
		return nil, fmt.Errorf("workflow engine not configured")
	}

	// Return basic workflow status
	return &model.WorkflowStatus{
		Name:            name,
		Enabled:         true,
		RouteCount:      0,
		EventsProcessed: 0,
		Errors:          0,
	}, nil
}

// Workflows is the resolver for the workflows field.
func (r *queryResolver) Workflows(ctx context.Context) ([]model.WorkflowStatus, error) {
	if r.WorkflowEngine == nil {
		return []model.WorkflowStatus{}, nil
	}

	// Return empty list - workflow listing not yet implemented
	return []model.WorkflowStatus{}, nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*model.HealthStatus, error) {
	uptime := int(time.Since(r.StartTime).Seconds())

	components := []model.ComponentHealth{
		{
			Name:   "event_store",
			Status: "healthy",
		},
		{
			Name:   "graphql_server",
			Status: "healthy",
		},
	}

	if r.WorkflowEngine != nil {
		components = append(components, model.ComponentHealth{
			Name:   "workflow_engine",
			Status: "healthy",
		})
	}

	return &model.HealthStatus{
		Status:     "healthy",
		Version:    r.Version,
		Uptime:     uptime,
		Components: components,
	}, nil
}

// ParsePreview is the resolver for the parsePreview field.
func (r *queryResolver) ParsePreview(ctx context.Context, format model.SourceFormat, data string, source *string) (*model.ParseResult, error) {
	result := &model.ParseResult{
		Events:   []model.Event{},
		Warnings: []model.ParseWarning{},
		Errors:   []string{},
	}

	src := "preview"
	if source != nil {
		src = *source
	}

	var parsedEvents []interface{}

	switch format {
	case model.SourceFormatHL7v2:
		parser := hl7v2.NewParser(src, hl7v2.ParserConfig{})
		parseResult, err := parser.ParseWithResult(data)
		if err != nil {
			result.Errors = append(result.Errors, err.Error())
			return result, nil
		}
		if parseResult.Event != nil {
			parsedEvents = append(parsedEvents, parseResult.Event)
		}
		for _, w := range parseResult.Warnings {
			result.Warnings = append(result.Warnings, model.ParseWarning{
				Phase:   w.Phase,
				Code:    w.Code,
				Message: w.Message,
				Path:    strPtr(w.Path),
			})
		}

	case model.SourceFormatFHIR:
		parser := fhir.NewParser(src)
		parseResult, err := parser.ParseWithResult([]byte(data))
		if err != nil {
			result.Errors = append(result.Errors, err.Error())
			return result, nil
		}
		parsedEvents = parseResult.Events
		for _, w := range parseResult.Warnings {
			result.Warnings = append(result.Warnings, model.ParseWarning{
				Phase:   w.Phase,
				Code:    w.Code,
				Message: w.Message,
			})
		}

	case model.SourceFormatCSV:
		parser := csv.NewParser(src, csv.ParserConfig{})
		parseResult, err := parser.Parse(bytes.NewReader([]byte(data)))
		if err != nil {
			result.Errors = append(result.Errors, err.Error())
			return result, nil
		}
		parsedEvents = parseResult.Events
		for _, w := range parseResult.Warnings {
			result.Warnings = append(result.Warnings, model.ParseWarning{
				Phase:   w.Phase,
				Code:    w.Code,
				Message: w.Message,
				Path:    strPtr(w.Path),
			})
		}

	case model.SourceFormatCDA:
		parser := cda.NewParser(src, nil)
		doc, err := parser.Parse([]byte(data))
		if err != nil {
			result.Errors = append(result.Errors, err.Error())
			return result, nil
		}
		mapper := cda.NewMapper(nil)
		mapResult, err := mapper.Map(doc)
		if err != nil {
			result.Errors = append(result.Errors, err.Error())
			return result, nil
		}
		parsedEvents = mapResult.Events

	case model.SourceFormatEDI837, model.SourceFormatEDI835:
		parser := edi.NewParser()
		parseResult, err := parser.Parse(data)
		if err != nil {
			result.Errors = append(result.Errors, err.Error())
			return result, nil
		}
		// Convert EDI interchange to events using mappers
		if parseResult.Interchange != nil {
			for _, fg := range parseResult.Interchange.FunctionalGroups {
				for _, tx := range fg.Transactions {
					var evts []interface{}
					switch tx.SetIdentifier {
					case "837":
						claims, mapErr := edi.Map837ToEvents(tx, src)
						if mapErr == nil {
							for _, c := range claims {
								evts = append(evts, c)
							}
						}
					case "835":
						rems, mapErr := edi.Map835ToEvents(tx, src)
						if mapErr == nil {
							for _, r := range rems {
								evts = append(evts, r)
							}
						}
					}
					parsedEvents = append(parsedEvents, evts...)
				}
			}
		}
		for _, w := range parseResult.Warnings {
			result.Warnings = append(result.Warnings, model.ParseWarning{
				Phase:   w.Phase,
				Code:    w.Code,
				Message: w.Message,
			})
		}

	default:
		result.Errors = append(result.Errors, fmt.Sprintf("unsupported format: %s", format))
		return result, nil
	}

	// Convert to GraphQL events
	for _, evt := range parsedEvents {
		gqlEvent := convertToGraphQLEvent(evt, src, format, nil)
		if gqlEvent != nil {
			result.Events = append(result.Events, gqlEvent)
		}
	}

	result.Success = len(result.Errors) == 0
	return result, nil
}

// PatientTimeline is the resolver for the patientTimeline field.
func (r *queryResolver) PatientTimeline(ctx context.Context, mrn string, fromTimestamp *time.Time, toTimestamp *time.Time, limit *int) (*model.PatientTimeline, error) {
	limitVal := 0
	if limit != nil {
		limitVal = *limit
	}
	return r.Projections.GetPatientTimeline(mrn, fromTimestamp, toTimestamp, limitVal)
}

// EventStatistics is the resolver for the eventStatistics field.
func (r *queryResolver) EventStatistics(ctx context.Context) (*model.EventStatistics, error) {
	return r.Projections.GetEventStatistics()
}

// ActiveEncounters is the resolver for the activeEncounters field.
func (r *queryResolver) ActiveEncounters(ctx context.Context, location *string, unit *string, class *string) ([]model.ActiveEncounter, error) {
	return r.Projections.GetActiveEncounters(location, unit, class)
}

// ActiveEncounter is the resolver for the activeEncounter field.
func (r *queryResolver) ActiveEncounter(ctx context.Context, id string) (*model.ActiveEncounter, error) {
	return r.Projections.GetActiveEncounter(id)
}

// ActiveEncounterByPatient is the resolver for the activeEncounterByPatient field.
func (r *queryResolver) ActiveEncounterByPatient(ctx context.Context, mrn string) (*model.ActiveEncounter, error) {
	return r.Projections.GetActiveEncounterByPatient(mrn)
}

// ProjectionStatus is the resolver for the projectionStatus field.
func (r *queryResolver) ProjectionStatus(ctx context.Context) ([]model.ProjectionStatus, error) {
	return r.Projections.GetProjectionStatus()
}

// Profiles is the resolver for the profiles field.
func (r *queryResolver) Profiles(ctx context.Context, activeOnly *bool) ([]model.SourceProfile, error) {
	if r.ProfileStore == nil {
		return []model.SourceProfile{}, nil
	}

	filterActive := true
	if activeOnly != nil {
		filterActive = *activeOnly
	}

	profiles, err := r.ProfileStore.ListProfiles(ctx, filterActive)
	if err != nil {
		return nil, fmt.Errorf("list profiles: %w", err)
	}

	result := make([]model.SourceProfile, 0, len(profiles))
	for _, p := range profiles {
		gqlProfile, err := convertStoreProfileToGraphQL(p)
		if err != nil {
			continue // Skip profiles that fail to convert
		}
		result = append(result, *gqlProfile)
	}

	return result, nil
}

// Profile is the resolver for the profile field.
func (r *queryResolver) Profile(ctx context.Context, id string) (*model.SourceProfile, error) {
	if r.ProfileStore == nil {
		return nil, nil
	}

	profile, err := r.ProfileStore.GetProfile(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("get profile: %w", err)
	}
	if profile == nil {
		return nil, nil
	}

	return convertStoreProfileToGraphQL(profile)
}

// ProfileRevisions is the resolver for the profileRevisions field.
func (r *queryResolver) ProfileRevisions(ctx context.Context, id string) ([]model.ProfileRevision, error) {
	if r.ProfileStore == nil {
		return []model.ProfileRevision{}, nil
	}

	revisions, err := r.ProfileStore.GetProfileRevisions(ctx, id)
	if err != nil {
		return nil, fmt.Errorf("get revisions: %w", err)
	}

	result := make([]model.ProfileRevision, 0, len(revisions))
	for _, rev := range revisions {
		result = append(result, model.ProfileRevision{
			Version:       rev.Version,
			CreatedAt:     rev.CreatedAt,
			CreatedBy:     strPtrEmpty(rev.CreatedBy),
			ChangeSummary: strPtrEmpty(rev.ChangeSummary),
		})
	}

	return result, nil
}

// ParsePreviewWithProfile is the resolver for the parsePreviewWithProfile field.
func (r *queryResolver) ParsePreviewWithProfile(ctx context.Context, format model.SourceFormat, data string, source *string, profileID *string) (*model.ParseResult, error) {
	// For now, delegate to the standard parsePreview
	// Profile-aware parsing will be added when profile integration is complete
	return r.ParsePreview(ctx, format, data, source)
}

// ExplainWarnings is the resolver for the explainWarnings field.
// It generates LLM-powered explanations for parse warnings.
func (r *queryResolver) ExplainWarnings(ctx context.Context, warnings []model.ParseWarningInput, format model.SourceFormat) ([]model.ExplainedWarning, error) {
	// Return empty if no explainer configured
	if r.WarningExplainer == nil {
		// Return empty explanations rather than error to allow graceful degradation
		results := make([]model.ExplainedWarning, len(warnings))
		for i, w := range warnings {
			results[i] = model.ExplainedWarning{
				Code:        w.Code,
				Explanation: "LLM explanation not available (explainer not configured)",
				FromCache:   false,
			}
		}
		return results, nil
	}

	// Convert GraphQL model to events.ParseWarning
	eventWarnings := make([]parseWarningForExplain, len(warnings))
	for i, w := range warnings {
		eventWarnings[i] = parseWarningForExplain{
			Phase:    w.Phase,
			Code:     w.Code,
			Message:  w.Message,
			Path:     derefStr(w.Path),
			Severity: derefStr(w.Severity),
		}
	}

	// Convert format to events.SourceFormat
	evtFormat := convertToEventsSourceFormat(format)

	// Call the explainer
	explained, err := r.explainWarningsBatch(ctx, eventWarnings, evtFormat)
	if err != nil {
		return nil, fmt.Errorf("explain warnings: %w", err)
	}

	// Convert back to GraphQL model
	results := make([]model.ExplainedWarning, len(explained))
	for i, e := range explained {
		results[i] = model.ExplainedWarning{
			Code:          e.Warning.Code,
			Explanation:   e.Explanation,
			FixSuggestion: strPtrEmpty(e.FixSuggestion),
			Impact:        strPtrEmpty(e.Impact),
			FromCache:     e.FromCache,
		}
	}

	return results, nil
}

// ExtractEntities extracts clinical entities from unstructured text using LLM.
func (r *queryResolver) ExtractEntities(ctx context.Context, input model.ExtractEntitiesInput) (*model.ExtractionResult, error) {
	// Return graceful degradation if extractor not configured
	if r.ClinicalExtractor == nil {
		return &model.ExtractionResult{
			Conditions:        []model.ExtractedCondition{},
			Medications:       []model.ExtractedMedication{},
			VitalSigns:        []model.ExtractedVitalSign{},
			Allergies:         []model.ExtractedAllergy{},
			Procedures:        []model.ExtractedProcedure{},
			OverallConfidence: 0,
			ProcessingTimeMs:  0,
		}, nil
	}

	// Build extraction options from input
	opts := extract.ExtractionOptions{
		DocumentType:       derefStr(input.DocumentType),
		ExtractConditions:  true,
		ExtractMedications: true,
		ExtractVitalSigns:  true,
		ExtractAllergies:   true,
		ExtractProcedures:  true,
		IncludeNegated:     derefBool(input.IncludeNegated),
	}

	// Set patient context if provided
	if input.PatientAge != nil {
		opts.PatientAge = *input.PatientAge
	}
	if input.PatientGender != nil {
		opts.PatientGender = *input.PatientGender
	}

	// Set minimum confidence threshold
	if input.MinConfidence != nil {
		opts.MinConfidence = *input.MinConfidence
	} else {
		opts.MinConfidence = 0.7 // Default
	}

	// Perform extraction
	startTime := time.Now()
	result, err := r.ClinicalExtractor.Extract(ctx, input.Text, opts)
	if err != nil {
		return nil, fmt.Errorf("extract entities: %w", err)
	}

	// Convert to GraphQL model
	return convertExtractionResult(result, time.Since(startTime)), nil
}

// AnalyzeQuality analyzes data quality of an event using LLM.
func (r *queryResolver) AnalyzeQuality(ctx context.Context, input model.AnalyzeQualityInput) (*model.DataQualityScore, error) {
	// Return graceful degradation if analyzer not configured
	if r.QualityAnalyzer == nil {
		return &model.DataQualityScore{
			OverallScore: 0.5,
			Dimensions: &model.QualityDimensions{
				Completeness: 0.5,
				Accuracy:     0.5,
				Consistency:  0.5,
				Conformance:  0.5,
				Timeliness:   0.5,
			},
			Issues:          []model.DataQualityIssue{},
			Recommendations: []model.QualityRecommendation{},
		}, nil
	}

	// Convert event type
	eventType := convertToEventsEventType(input.EventType)

	// Perform analysis
	startTime := time.Now()
	result, err := r.QualityAnalyzer.AnalyzeEvent(ctx, input.Event, eventType)
	if err != nil {
		return nil, fmt.Errorf("analyze quality: %w", err)
	}

	// Convert to GraphQL model
	return convertQualityScore(result, time.Since(startTime)), nil
}

// QuickQualityScore performs a lightweight quality assessment without LLM.
func (r *queryResolver) QuickQualityScore(ctx context.Context, event map[string]any) (*model.DataQualityScore, error) {
	// Use the quick score function (no LLM needed)
	result := quality.QuickScore(event)
	return convertQualityScore(result, 0), nil
}

// ExplainWorkflow generates a human-readable explanation of a workflow.
func (r *queryResolver) ExplainWorkflow(ctx context.Context, input model.ExplainWorkflowInput) (*model.WorkflowExplanation, error) {
	// Return graceful degradation if explainer not configured
	if r.WorkflowExplainer == nil {
		return &model.WorkflowExplanation{
			Summary:           "Workflow explanation not available",
			Description:       "LLM workflow explanation is not configured",
			RouteExplanations: []model.RouteExplanation{},
			Warnings:          []string{"Workflow explainer service not available"},
		}, nil
	}

	// Get explanation (with optional audience targeting)
	var explResult *workflowExplanationResult
	var err error

	if input.Audience != nil && *input.Audience != "" {
		result, explErr := r.WorkflowExplainer.ExplainForAudience(ctx, input.WorkflowYaml, *input.Audience)
		if explErr != nil {
			return nil, fmt.Errorf("explain workflow: %w", explErr)
		}
		explResult = convertExplainResult(result)
	} else {
		result, explErr := r.WorkflowExplainer.Explain(ctx, input.WorkflowYaml)
		if explErr != nil {
			return nil, fmt.Errorf("explain workflow: %w", explErr)
		}
		explResult = convertExplainResult(result)
	}

	if err != nil {
		return nil, fmt.Errorf("explain workflow: %w", err)
	}

	return convertWorkflowExplanation(explResult), nil
}

// ClassifyMessage classifies a message to suggest tags and event type.
func (r *queryResolver) ClassifyMessage(ctx context.Context, input model.ClassifyMessageInput) (*model.MessageClassification, error) {
	// For now, implement basic classification without LLM
	// This can be enhanced with LLM support later

	result := &model.MessageClassification{
		MessageType:   "UNKNOWN",
		SuggestedTags: []string{},
		Confidence:    0.5,
	}

	// Basic message type detection based on format
	switch input.Format {
	case model.SourceFormatHL7v2:
		result = classifyHL7v2Message(input.Data)
	case model.SourceFormatFHIR:
		result = classifyFHIRMessage(input.Data)
	case model.SourceFormatEDI837:
		result.MessageType = "837"
		result.EventType = eventTypePtr(model.EventTypeClaimSubmitted)
		result.SuggestedTags = []string{"claims", "professional", "edi"}
		result.Confidence = 0.9
		result.Summary = strPtrEmpty("Professional claim submission (837P)")
	case model.SourceFormatEDI835:
		result.MessageType = "835"
		result.EventType = eventTypePtr(model.EventTypeClaimAdjudicated)
		result.SuggestedTags = []string{"remittance", "payment", "edi"}
		result.Confidence = 0.9
		result.Summary = strPtrEmpty("Remittance advice (835)")
	case model.SourceFormatCDA:
		result.MessageType = "CDA"
		result.EventType = eventTypePtr(model.EventTypeDocument)
		result.SuggestedTags = []string{"clinical-document", "cda"}
		result.Confidence = 0.8
		result.Summary = strPtrEmpty("Clinical document")
	case model.SourceFormatCSV:
		result.MessageType = "CSV"
		result.SuggestedTags = []string{"batch", "csv"}
		result.Confidence = 0.7
		result.Summary = strPtrEmpty("CSV batch data")
	}

	return result, nil
}

// ListMappings is the resolver for the listMappings field.
func (r *queryResolver) ListMappings(ctx context.Context, input *model.ListMappingsInput) (*model.CodeMappingConnection, error) {
	if r.MappingStore == nil {
		return nil, fmt.Errorf("terminology mapping store not configured")
	}

	// Build filter from input
	filter := termdb.ListMappingsFilter{
		Limit:  100,
		Offset: 0,
	}

	if input != nil {
		if input.SourceSystem != nil {
			filter.SourceSystem = *input.SourceSystem
		}
		if input.TargetSystem != nil {
			filter.TargetSystem = *input.TargetSystem
		}
		if input.ProfileID != nil {
			filter.ProfileID = *input.ProfileID
		}
		if input.Origin != nil {
			filter.Origin = toDBOrigin(*input.Origin)
		}
		if input.UploadBatchID != nil {
			batchID, err := uuid.Parse(*input.UploadBatchID)
			if err != nil {
				return nil, fmt.Errorf("invalid batch ID: %w", err)
			}
			filter.UploadBatchID = &batchID
		}
		if input.First != nil && *input.First > 0 {
			filter.Limit = *input.First
		}
		if input.Offset != nil && *input.Offset > 0 {
			filter.Offset = *input.Offset
		}
	}

	mappings, total, err := r.MappingStore.ListMappings(ctx, filter)
	if err != nil {
		return nil, fmt.Errorf("listing mappings: %w", err)
	}

	nodes := make([]model.CodeMapping, 0, len(mappings))
	for _, m := range mappings {
		nodes = append(nodes, *toGraphQLMapping(m))
	}

	hasNextPage := filter.Offset+len(mappings) < total
	hasPrevPage := filter.Offset > 0

	return &model.CodeMappingConnection{
		Nodes:      nodes,
		TotalCount: total,
		PageInfo: &model.PageInfo{
			HasNextPage:     hasNextPage,
			HasPreviousPage: hasPrevPage,
		},
	}, nil
}

// GetMapping is the resolver for the getMapping field.
func (r *queryResolver) GetMapping(ctx context.Context, id string) (*model.CodeMapping, error) {
	if r.MappingStore == nil {
		return nil, fmt.Errorf("terminology mapping store not configured")
	}

	mappingID, err := strconv.ParseInt(id, 10, 64)
	if err != nil {
		return nil, fmt.Errorf("invalid mapping ID: %w", err)
	}

	mapping, err := r.MappingStore.GetMapping(ctx, mappingID)
	if err != nil {
		return nil, fmt.Errorf("getting mapping: %w", err)
	}
	if mapping == nil {
		return nil, nil // Not found
	}

	return toGraphQLMapping(mapping), nil
}

// LookupMapping is the resolver for the lookupMapping field.
func (r *queryResolver) LookupMapping(ctx context.Context, sourceSystem string, sourceCode string, targetSystem string, profileID *string) (*model.CodeMapping, error) {
	if r.MappingStore == nil {
		return nil, fmt.Errorf("terminology mapping store not configured")
	}

	profID := ""
	if profileID != nil {
		profID = *profileID
	}

	mapping, err := r.MappingStore.LookupMapping(ctx, sourceSystem, sourceCode, targetSystem, profID)
	if err != nil {
		return nil, fmt.Errorf("looking up mapping: %w", err)
	}
	if mapping == nil {
		return nil, nil // Not found
	}

	return toGraphQLMapping(mapping), nil
}

// GetUploadBatch is the resolver for the getUploadBatch field.
func (r *queryResolver) GetUploadBatch(ctx context.Context, id string) (*model.UploadBatch, error) {
	if r.MappingStore == nil {
		return nil, fmt.Errorf("terminology mapping store not configured")
	}

	batchID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid batch ID: %w", err)
	}

	batch, err := r.MappingStore.GetBatch(ctx, batchID)
	if err != nil {
		return nil, fmt.Errorf("getting upload batch: %w", err)
	}
	if batch == nil {
		return nil, nil // Not found
	}

	return toGraphQLBatch(batch), nil
}

// EventStream is the resolver for the eventStream field.
func (r *subscriptionResolver) EventStream(ctx context.Context, filter *model.EventFilter) (<-chan model.Event, error) {
	return r.Store.Subscribe(ctx, filter)
}

// WorkflowEvents is the resolver for the workflowEvents field.
func (r *subscriptionResolver) WorkflowEvents(ctx context.Context, workflowName string) (<-chan *model.WorkflowEventNotification, error) {
	// Subscribe to workflow events with optional workflow name filter
	ch := r.subscribeToWorkflowEvents(workflowName)

	// Clean up subscription when context is cancelled
	go func() {
		<-ctx.Done()
		r.unsubscribeFromWorkflowEvents(ch)
	}()

	return ch, nil
}

// PatientEvents is the resolver for the patientEvents field.
func (r *subscriptionResolver) PatientEvents(ctx context.Context, mrn string) (<-chan model.Event, error) {
	return r.Store.SubscribePatient(ctx, mrn)
}

// Mutation returns graphql1.MutationResolver implementation.
func (r *Resolver) Mutation() graphql1.MutationResolver { return &mutationResolver{r} }

// Query returns graphql1.QueryResolver implementation.
func (r *Resolver) Query() graphql1.QueryResolver { return &queryResolver{r} }

// Subscription returns graphql1.SubscriptionResolver implementation.
func (r *Resolver) Subscription() graphql1.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }

// Terminology mapping conversion helpers

// toGraphQLEquivalence converts database equivalence to GraphQL enum.
func toGraphQLEquivalence(e termdb.MappingEquivalence) model.MappingEquivalence {
	switch e {
	case termdb.EquivalenceEquivalent:
		return model.MappingEquivalenceEquivalent
	case termdb.EquivalenceWider:
		return model.MappingEquivalenceWider
	case termdb.EquivalenceNarrower:
		return model.MappingEquivalenceNarrower
	case termdb.EquivalenceInexact:
		return model.MappingEquivalenceInexact
	default:
		return model.MappingEquivalenceEquivalent
	}
}

// toDBEquivalence converts GraphQL enum to database equivalence.
func toDBEquivalence(e model.MappingEquivalence) termdb.MappingEquivalence {
	switch e {
	case model.MappingEquivalenceEquivalent:
		return termdb.EquivalenceEquivalent
	case model.MappingEquivalenceWider:
		return termdb.EquivalenceWider
	case model.MappingEquivalenceNarrower:
		return termdb.EquivalenceNarrower
	case model.MappingEquivalenceInexact:
		return termdb.EquivalenceInexact
	default:
		return termdb.EquivalenceEquivalent
	}
}

// toGraphQLOrigin converts database origin to GraphQL enum.
func toGraphQLOrigin(o termdb.MappingOrigin) model.MappingOrigin {
	switch o {
	case termdb.OriginCSVUpload:
		return model.MappingOriginCSVUpload
	case termdb.OriginApprovedAutoroute:
		return model.MappingOriginApprovedAutoroute
	case termdb.OriginManual:
		return model.MappingOriginManual
	default:
		return model.MappingOriginManual
	}
}

// toDBOrigin converts GraphQL enum to database origin.
func toDBOrigin(o model.MappingOrigin) termdb.MappingOrigin {
	switch o {
	case model.MappingOriginCSVUpload:
		return termdb.OriginCSVUpload
	case model.MappingOriginApprovedAutoroute:
		return termdb.OriginApprovedAutoroute
	case model.MappingOriginManual:
		return termdb.OriginManual
	default:
		return termdb.OriginManual
	}
}

// toGraphQLMapping converts a database mapping to a GraphQL model.
func toGraphQLMapping(m *termdb.CustomMapping) *model.CodeMapping {
	result := &model.CodeMapping{
		ID:           strconv.FormatInt(m.ID, 10),
		SourceSystem: m.SourceSystem,
		SourceCode:   m.SourceCode,
		TargetSystem: m.TargetSystem,
		TargetCode:   m.TargetCode,
		Equivalence:  toGraphQLEquivalence(m.Equivalence),
		Origin:       toGraphQLOrigin(m.Origin),
		CreatedAt:    m.CreatedAt,
		Confidence:   m.Confidence,
	}
	if m.SourceDisplay != "" {
		result.SourceDisplay = &m.SourceDisplay
	}
	if m.TargetDisplay != "" {
		result.TargetDisplay = &m.TargetDisplay
	}
	if m.Comment != "" {
		result.Comment = &m.Comment
	}
	if m.ProfileID != "" {
		result.ProfileID = &m.ProfileID
	}
	if m.UploadBatchID != nil {
		batchID := m.UploadBatchID.String()
		result.UploadBatchID = &batchID
	}
	if m.CreatedBy != "" {
		result.CreatedBy = &m.CreatedBy
	}
	if m.ApprovedAt != nil {
		result.ApprovedAt = m.ApprovedAt
	}
	if m.ApprovedBy != "" {
		result.ApprovedBy = &m.ApprovedBy
	}
	return result
}

// toGraphQLBatch converts a database upload batch to a GraphQL model.
func toGraphQLBatch(b *termdb.UploadBatch) *model.UploadBatch {
	result := &model.UploadBatch{
		ID:               b.ID.String(),
		Filename:         b.Filename,
		TotalRows:        b.TotalRows,
		ValidRows:        b.ValidRows,
		DuplicateRows:    b.DuplicateRows,
		ErrorRows:        b.ErrorRows,
		UploadedAt:       b.UploadedAt,
		ValidationErrors: make([]model.UploadValidationError, 0, len(b.ValidationErrors)),
	}
	if b.SourceSystem != "" {
		result.SourceSystem = &b.SourceSystem
	}
	if b.TargetSystem != "" {
		result.TargetSystem = &b.TargetSystem
	}
	if b.ProfileID != "" {
		result.ProfileID = &b.ProfileID
	}
	if b.UploadedBy != "" {
		result.UploadedBy = &b.UploadedBy
	}
	for _, e := range b.ValidationErrors {
		ve := model.UploadValidationError{
			Row:     e.Row,
			Message: e.Message,
		}
		if e.Column != "" {
			ve.Column = &e.Column
		}
		result.ValidationErrors = append(result.ValidationErrors, ve)
	}
	return result
}
