package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"bytes"
	"context"
	"fmt"
	"sync"
	"time"

	graphql1 "github.com/cblevins/fi-fhir/internal/api/graphql"
	"github.com/cblevins/fi-fhir/internal/api/graphql/model"
	"github.com/cblevins/fi-fhir/internal/fhir/subscription"
	"github.com/cblevins/fi-fhir/internal/parser/cda"
	"github.com/cblevins/fi-fhir/internal/parser/csv"
	"github.com/cblevins/fi-fhir/internal/parser/edi"
	"github.com/cblevins/fi-fhir/internal/parser/fhir"
	"github.com/cblevins/fi-fhir/internal/parser/hl7v2"
)

// SubmitMessage is the resolver for the submitMessage field.
func (r *mutationResolver) SubmitMessage(ctx context.Context, input model.SubmitMessageInput) (*model.SubmitResult, error) {
	result := &model.SubmitResult{
		Warnings:        []model.ParseWarning{},
		Errors:          []string{},
		WorkflowResults: []model.WorkflowResult{},
	}

	// Parse the message based on format
	var parsedEvents []interface{}

	switch input.Format {
	case model.SourceFormatHL7v2:
		parser := hl7v2.NewParser(input.Source, hl7v2.ParserConfig{})
		parseResult, err := parser.ParseWithResult(input.Data)
		if err != nil {
			result.Errors = append(result.Errors, err.Error())
			return result, nil
		}
		if parseResult.Event != nil {
			parsedEvents = append(parsedEvents, parseResult.Event)
		}
		for _, w := range parseResult.Warnings {
			result.Warnings = append(result.Warnings, model.ParseWarning{
				Phase:   w.Phase,
				Code:    w.Code,
				Message: w.Message,
				Path:    strPtr(w.Path),
			})
		}

	case model.SourceFormatFHIR:
		parser := fhir.NewParser(input.Source)
		parseResult, err := parser.ParseWithResult([]byte(input.Data))
		if err != nil {
			result.Errors = append(result.Errors, err.Error())
			return result, nil
		}
		parsedEvents = parseResult.Events
		for _, w := range parseResult.Warnings {
			result.Warnings = append(result.Warnings, model.ParseWarning{
				Phase:   w.Phase,
				Code:    w.Code,
				Message: w.Message,
			})
		}

	case model.SourceFormatCSV:
		parser := csv.NewParser(input.Source, csv.ParserConfig{})
		parseResult, err := parser.Parse(bytes.NewReader([]byte(input.Data)))
		if err != nil {
			result.Errors = append(result.Errors, err.Error())
			return result, nil
		}
		parsedEvents = parseResult.Events
		for _, w := range parseResult.Warnings {
			result.Warnings = append(result.Warnings, model.ParseWarning{
				Phase:   w.Phase,
				Code:    w.Code,
				Message: w.Message,
				Path:    strPtr(w.Path),
			})
		}

	case model.SourceFormatCDA:
		parser := cda.NewParser(input.Source, nil)
		doc, err := parser.Parse([]byte(input.Data))
		if err != nil {
			result.Errors = append(result.Errors, err.Error())
			return result, nil
		}
		mapper := cda.NewMapper(nil)
		mapResult, err := mapper.Map(doc)
		if err != nil {
			result.Errors = append(result.Errors, err.Error())
			return result, nil
		}
		parsedEvents = mapResult.Events

	case model.SourceFormatEDI837, model.SourceFormatEDI835:
		parser := edi.NewParser()
		parseResult, err := parser.Parse(input.Data)
		if err != nil {
			result.Errors = append(result.Errors, err.Error())
			return result, nil
		}
		// Convert EDI interchange to events using mappers
		if parseResult.Interchange != nil {
			for _, fg := range parseResult.Interchange.FunctionalGroups {
				for _, tx := range fg.Transactions {
					var evts []interface{}
					switch tx.SetIdentifier {
					case "837":
						claims, mapErr := edi.Map837ToEvents(tx, input.Source)
						if mapErr == nil {
							for _, c := range claims {
								evts = append(evts, c)
							}
						}
					case "835":
						rems, mapErr := edi.Map835ToEvents(tx, input.Source)
						if mapErr == nil {
							for _, r := range rems {
								evts = append(evts, r)
							}
						}
					}
					parsedEvents = append(parsedEvents, evts...)
				}
			}
		}
		for _, w := range parseResult.Warnings {
			result.Warnings = append(result.Warnings, model.ParseWarning{
				Phase:   w.Phase,
				Code:    w.Code,
				Message: w.Message,
			})
		}

	default:
		result.Errors = append(result.Errors, fmt.Sprintf("unsupported format: %s", input.Format))
		return result, nil
	}

	// Convert and store events
	for _, evt := range parsedEvents {
		gqlEvent := convertToGraphQLEvent(evt, input.Source, input.Format, input.CorrelationID)
		if gqlEvent != nil {
			id, err := r.Store.SaveEvent(ctx, gqlEvent)
			if err != nil {
				result.Errors = append(result.Errors, err.Error())
			} else {
				result.EventID = &id
			}
		}
	}

	// Execute workflows if available
	if r.WorkflowEngine != nil && len(parsedEvents) > 0 {
		for _, evt := range parsedEvents {
			wfResult := r.WorkflowEngine.Process(evt)

			// Count matched routes and actions
			routesMatched := 0
			actionsExecuted := 0
			var errors []string

			for _, rr := range wfResult.RouteResults {
				if rr.Matched {
					routesMatched++
					actionsExecuted += rr.ActionsRun
					for _, err := range rr.ActionErrors {
						errors = append(errors, err.Error())
					}
				}
			}

			result.WorkflowResults = append(result.WorkflowResults, model.WorkflowResult{
				WorkflowName:    "default",
				RoutesMatched:   routesMatched,
				ActionsExecuted: actionsExecuted,
				Errors:          errors,
				Duration:        0,
			})
		}
	}

	result.Success = len(result.Errors) == 0
	return result, nil
}

// SubmitEvent is the resolver for the submitEvent field.
func (r *mutationResolver) SubmitEvent(ctx context.Context, input model.SubmitEventInput) (*model.SubmitResult, error) {
	result := &model.SubmitResult{
		Warnings:        []model.ParseWarning{},
		Errors:          []string{},
		WorkflowResults: []model.WorkflowResult{},
	}

	// Create event from input data
	event, err := createEventFromInput(input)
	if err != nil {
		result.Errors = append(result.Errors, err.Error())
		return result, nil
	}

	// Store the event
	id, err := r.Store.SaveEvent(ctx, event)
	if err != nil {
		result.Errors = append(result.Errors, err.Error())
		return result, nil
	}

	result.EventID = &id
	result.Success = true
	return result, nil
}

// SubmitBatch is the resolver for the submitBatch field.
func (r *mutationResolver) SubmitBatch(ctx context.Context, input model.SubmitBatchInput) (*model.BatchResult, error) {
	startTime := time.Now()

	// Calculate total items
	totalItems := len(input.Messages) + len(input.Events)
	if totalItems == 0 {
		return &model.BatchResult{
			TotalItems:   0,
			SuccessCount: 0,
			FailureCount: 0,
			Results:      []model.BatchItemResult{},
			DurationMs:   0,
		}, nil
	}

	// Enforce max batch size (prevent DoS)
	const maxBatchSize = 1000
	if totalItems > maxBatchSize {
		return nil, fmt.Errorf("batch size %d exceeds maximum of %d", totalItems, maxBatchSize)
	}

	stopOnError := input.StopOnError != nil && *input.StopOnError
	parallel := input.Parallel != nil && *input.Parallel

	results := make([]model.BatchItemResult, 0, totalItems)
	var successCount, failureCount int

	// Process messages
	if len(input.Messages) > 0 {
		messageResults := r.processBatchMessages(ctx, input.Messages, stopOnError, parallel)
		for _, res := range messageResults {
			if res.Success {
				successCount++
			} else {
				failureCount++
			}
		}
		results = append(results, messageResults...)

		// Check stop on error
		if stopOnError && failureCount > 0 {
			return &model.BatchResult{
				TotalItems:   totalItems,
				SuccessCount: successCount,
				FailureCount: failureCount,
				Results:      results,
				DurationMs:   int(time.Since(startTime).Milliseconds()),
			}, nil
		}
	}

	// Process pre-parsed events
	if len(input.Events) > 0 {
		// Adjust indices to continue from messages
		baseIndex := len(input.Messages)
		eventResults := r.processBatchEvents(ctx, input.Events, baseIndex, stopOnError, parallel)
		for _, res := range eventResults {
			if res.Success {
				successCount++
			} else {
				failureCount++
			}
		}
		results = append(results, eventResults...)
	}

	return &model.BatchResult{
		TotalItems:   totalItems,
		SuccessCount: successCount,
		FailureCount: failureCount,
		Results:      results,
		DurationMs:   int(time.Since(startTime).Milliseconds()),
	}, nil
}

// processBatchMessages processes a batch of raw messages
func (r *mutationResolver) processBatchMessages(ctx context.Context, messages []model.BatchMessageItem, stopOnError, parallel bool) []model.BatchItemResult {
	results := make([]model.BatchItemResult, len(messages))

	processOne := func(i int, msg model.BatchMessageItem) model.BatchItemResult {
		index := i
		if msg.Index != nil {
			index = *msg.Index
		}

		// Convert to SubmitMessageInput and process
		input := model.SubmitMessageInput{
			Format:        msg.Format,
			Data:          msg.Data,
			Source:        msg.Source,
			CorrelationID: msg.CorrelationID,
		}

		submitResult, err := r.SubmitMessage(ctx, input)

		result := model.BatchItemResult{
			Index:    index,
			Warnings: []model.ParseWarning{},
			Errors:   []string{},
		}

		if err != nil {
			result.Success = false
			result.Errors = []string{err.Error()}
		} else {
			result.Success = submitResult.Success
			result.EventID = submitResult.EventID
			result.Warnings = submitResult.Warnings
			result.Errors = submitResult.Errors
			result.WorkflowResults = submitResult.WorkflowResults
		}

		return result
	}

	if parallel {
		// Process in parallel using goroutines
		var wg sync.WaitGroup
		for i, msg := range messages {
			wg.Add(1)
			go func(idx int, m model.BatchMessageItem) {
				defer wg.Done()
				results[idx] = processOne(idx, m)
			}(i, msg)
		}
		wg.Wait()
	} else {
		// Process sequentially
		for i, msg := range messages {
			results[i] = processOne(i, msg)
			if stopOnError && !results[i].Success {
				// Stop processing and truncate results to only include processed items
				return results[:i+1]
			}
		}
	}

	return results
}

// processBatchEvents processes a batch of pre-parsed events
func (r *mutationResolver) processBatchEvents(ctx context.Context, events []model.BatchEventItem, baseIndex int, stopOnError, parallel bool) []model.BatchItemResult {
	results := make([]model.BatchItemResult, len(events))

	processOne := func(i int, evt model.BatchEventItem) model.BatchItemResult {
		index := baseIndex + i
		if evt.Index != nil {
			index = *evt.Index
		}

		// Convert to SubmitEventInput and process
		input := model.SubmitEventInput{
			Type:          evt.Type,
			Data:          evt.Data,
			Source:        evt.Source,
			CorrelationID: evt.CorrelationID,
		}

		submitResult, err := r.SubmitEvent(ctx, input)

		result := model.BatchItemResult{
			Index:    index,
			Warnings: []model.ParseWarning{},
			Errors:   []string{},
		}

		if err != nil {
			result.Success = false
			result.Errors = []string{err.Error()}
		} else {
			result.Success = submitResult.Success
			result.EventID = submitResult.EventID
			result.Warnings = submitResult.Warnings
			result.Errors = submitResult.Errors
			result.WorkflowResults = submitResult.WorkflowResults
		}

		return result
	}

	if parallel {
		// Process in parallel using goroutines
		var wg sync.WaitGroup
		for i, evt := range events {
			wg.Add(1)
			go func(idx int, e model.BatchEventItem) {
				defer wg.Done()
				results[idx] = processOne(idx, e)
			}(i, evt)
		}
		wg.Wait()
	} else {
		// Process sequentially
		for i, evt := range events {
			results[i] = processOne(i, evt)
			if stopOnError && !results[i].Success {
				// Stop processing and truncate results to only include processed items
				return results[:i+1]
			}
		}
	}

	return results
}

// TriggerWorkflow is the resolver for the triggerWorkflow field.
func (r *mutationResolver) TriggerWorkflow(ctx context.Context, name string, event map[string]any) (*model.WorkflowResult, error) {
	if r.WorkflowEngine == nil {
		return nil, fmt.Errorf("workflow engine not configured")
	}

	// Process the event through the workflow engine
	// The engine accepts interface{}, so we can pass the map directly
	startTime := time.Now()
	wfResult := r.WorkflowEngine.ProcessWithContext(ctx, event)
	duration := time.Since(startTime).Milliseconds()

	// Count matched routes and actions
	routesMatched := 0
	actionsExecuted := 0
	var errors []string

	for _, rr := range wfResult.RouteResults {
		if rr.Matched {
			routesMatched++
			actionsExecuted += rr.ActionsRun
			for _, err := range rr.ActionErrors {
				errors = append(errors, err.Error())
			}
			for _, err := range rr.TransformErrors {
				errors = append(errors, err.Error())
			}
		}
	}

	return &model.WorkflowResult{
		WorkflowName:    name,
		RoutesMatched:   routesMatched,
		ActionsExecuted: actionsExecuted,
		Errors:          errors,
		Duration:        int(duration),
	}, nil
}

// CreateFhirSubscription is the resolver for the createFhirSubscription field.
func (r *mutationResolver) CreateFhirSubscription(ctx context.Context, input model.CreateSubscriptionInput) (*model.FhirSubscription, error) {
	// Get or create a client for this FHIR server
	client, err := r.getOrCreateSubscriptionClient(input.Server)
	if err != nil {
		return nil, fmt.Errorf("create subscription client: %w", err)
	}

	// Build the FHIR Subscription resource
	sub := &subscription.Subscription{
		Status:   subscription.StatusRequested,
		Reason:   input.Name,
		Criteria: input.Criteria,
		Channel: subscription.Channel{
			Type:     subscription.ChannelRestHook,
			Endpoint: input.Endpoint,
			Payload:  "application/fhir+json",
		},
	}

	// Create on the FHIR server
	created, err := client.Create(ctx, sub)
	if err != nil {
		return nil, fmt.Errorf("create subscription on server: %w", err)
	}

	// Store locally for tracking
	record := &SubscriptionRecord{
		ID:        created.ID,
		Name:      input.Name,
		Server:    input.Server,
		Criteria:  input.Criteria,
		Endpoint:  input.Endpoint,
		Status:    string(created.Status),
		CreatedAt: time.Now(),
	}
	r.storeSubscriptionRecord(record)

	return &model.FhirSubscription{
		ID:        created.ID,
		Name:      input.Name,
		Status:    string(created.Status),
		Criteria:  input.Criteria,
		Server:    input.Server,
		Endpoint:  input.Endpoint,
		CreatedAt: record.CreatedAt,
	}, nil
}

// DeleteFhirSubscription is the resolver for the deleteFhirSubscription field.
func (r *mutationResolver) DeleteFhirSubscription(ctx context.Context, id string) (bool, error) {
	// Look up the subscription to get the server
	record, exists := r.getSubscriptionRecord(id)
	if !exists {
		return false, fmt.Errorf("subscription not found: %s", id)
	}

	// Get the client for this server
	client, err := r.getOrCreateSubscriptionClient(record.Server)
	if err != nil {
		return false, fmt.Errorf("get subscription client: %w", err)
	}

	// Delete from the FHIR server
	if err := client.Delete(ctx, id); err != nil {
		return false, fmt.Errorf("delete subscription: %w", err)
	}

	// Remove local record
	r.deleteSubscriptionRecord(id)

	return true, nil
}

// PauseFhirSubscription is the resolver for the pauseFhirSubscription field.
func (r *mutationResolver) PauseFhirSubscription(ctx context.Context, id string) (*model.FhirSubscription, error) {
	// Look up the subscription
	record, exists := r.getSubscriptionRecord(id)
	if !exists {
		return nil, fmt.Errorf("subscription not found: %s", id)
	}

	// Get the client for this server
	client, err := r.getOrCreateSubscriptionClient(record.Server)
	if err != nil {
		return nil, fmt.Errorf("get subscription client: %w", err)
	}

	// Pause on the FHIR server
	if err := client.Pause(ctx, id); err != nil {
		return nil, fmt.Errorf("pause subscription: %w", err)
	}

	// Update local status
	r.updateSubscriptionStatus(id, string(subscription.StatusOff))

	return &model.FhirSubscription{
		ID:        record.ID,
		Name:      record.Name,
		Status:    string(subscription.StatusOff),
		Criteria:  record.Criteria,
		Server:    record.Server,
		Endpoint:  record.Endpoint,
		CreatedAt: record.CreatedAt,
	}, nil
}

// ResumeFhirSubscription is the resolver for the resumeFhirSubscription field.
func (r *mutationResolver) ResumeFhirSubscription(ctx context.Context, id string) (*model.FhirSubscription, error) {
	// Look up the subscription
	record, exists := r.getSubscriptionRecord(id)
	if !exists {
		return nil, fmt.Errorf("subscription not found: %s", id)
	}

	// Get the client for this server
	client, err := r.getOrCreateSubscriptionClient(record.Server)
	if err != nil {
		return nil, fmt.Errorf("get subscription client: %w", err)
	}

	// Resume on the FHIR server
	if err := client.Resume(ctx, id); err != nil {
		return nil, fmt.Errorf("resume subscription: %w", err)
	}

	// Update local status (server will activate, so we mark as requested)
	r.updateSubscriptionStatus(id, string(subscription.StatusRequested))

	return &model.FhirSubscription{
		ID:        record.ID,
		Name:      record.Name,
		Status:    string(subscription.StatusRequested),
		Criteria:  record.Criteria,
		Server:    record.Server,
		Endpoint:  record.Endpoint,
		CreatedAt: record.CreatedAt,
	}, nil
}

// Event is the resolver for the event field.
func (r *queryResolver) Event(ctx context.Context, id string) (model.Event, error) {
	return r.Store.GetEvent(ctx, id)
}

// Events is the resolver for the events field.
func (r *queryResolver) Events(ctx context.Context, filter *model.EventFilter, first *int, after *string, orderBy *model.EventOrderBy) (*model.EventConnection, error) {
	limit := 100
	if first != nil {
		limit = *first
	}
	return r.Store.QueryEvents(ctx, filter, limit, after, orderBy)
}

// Patient is the resolver for the patient field.
func (r *queryResolver) Patient(ctx context.Context, mrn string) (*model.Patient, error) {
	return r.Store.GetPatient(ctx, mrn)
}

// Patients is the resolver for the patients field.
func (r *queryResolver) Patients(ctx context.Context, filter *model.PatientFilter, first *int, after *string) (*model.PatientConnection, error) {
	limit := 100
	if first != nil {
		limit = *first
	}
	return r.Store.QueryPatients(ctx, filter, limit, after)
}

// Workflow is the resolver for the workflow field.
func (r *queryResolver) Workflow(ctx context.Context, name string) (*model.WorkflowStatus, error) {
	if r.WorkflowEngine == nil {
		return nil, fmt.Errorf("workflow engine not configured")
	}

	// Return basic workflow status
	return &model.WorkflowStatus{
		Name:            name,
		Enabled:         true,
		RouteCount:      0,
		EventsProcessed: 0,
		Errors:          0,
	}, nil
}

// Workflows is the resolver for the workflows field.
func (r *queryResolver) Workflows(ctx context.Context) ([]model.WorkflowStatus, error) {
	if r.WorkflowEngine == nil {
		return []model.WorkflowStatus{}, nil
	}

	// Return empty list - workflow listing not yet implemented
	return []model.WorkflowStatus{}, nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*model.HealthStatus, error) {
	uptime := int(time.Since(r.StartTime).Seconds())

	components := []model.ComponentHealth{
		{
			Name:   "event_store",
			Status: "healthy",
		},
		{
			Name:   "graphql_server",
			Status: "healthy",
		},
	}

	if r.WorkflowEngine != nil {
		components = append(components, model.ComponentHealth{
			Name:   "workflow_engine",
			Status: "healthy",
		})
	}

	return &model.HealthStatus{
		Status:     "healthy",
		Version:    r.Version,
		Uptime:     uptime,
		Components: components,
	}, nil
}

// ParsePreview is the resolver for the parsePreview field.
func (r *queryResolver) ParsePreview(ctx context.Context, format model.SourceFormat, data string, source *string) (*model.ParseResult, error) {
	result := &model.ParseResult{
		Events:   []model.Event{},
		Warnings: []model.ParseWarning{},
		Errors:   []string{},
	}

	src := "preview"
	if source != nil {
		src = *source
	}

	var parsedEvents []interface{}

	switch format {
	case model.SourceFormatHL7v2:
		parser := hl7v2.NewParser(src, hl7v2.ParserConfig{})
		parseResult, err := parser.ParseWithResult(data)
		if err != nil {
			result.Errors = append(result.Errors, err.Error())
			return result, nil
		}
		if parseResult.Event != nil {
			parsedEvents = append(parsedEvents, parseResult.Event)
		}
		for _, w := range parseResult.Warnings {
			result.Warnings = append(result.Warnings, model.ParseWarning{
				Phase:   w.Phase,
				Code:    w.Code,
				Message: w.Message,
				Path:    strPtr(w.Path),
			})
		}

	case model.SourceFormatFHIR:
		parser := fhir.NewParser(src)
		parseResult, err := parser.ParseWithResult([]byte(data))
		if err != nil {
			result.Errors = append(result.Errors, err.Error())
			return result, nil
		}
		parsedEvents = parseResult.Events
		for _, w := range parseResult.Warnings {
			result.Warnings = append(result.Warnings, model.ParseWarning{
				Phase:   w.Phase,
				Code:    w.Code,
				Message: w.Message,
			})
		}

	case model.SourceFormatCSV:
		parser := csv.NewParser(src, csv.ParserConfig{})
		parseResult, err := parser.Parse(bytes.NewReader([]byte(data)))
		if err != nil {
			result.Errors = append(result.Errors, err.Error())
			return result, nil
		}
		parsedEvents = parseResult.Events
		for _, w := range parseResult.Warnings {
			result.Warnings = append(result.Warnings, model.ParseWarning{
				Phase:   w.Phase,
				Code:    w.Code,
				Message: w.Message,
				Path:    strPtr(w.Path),
			})
		}

	case model.SourceFormatCDA:
		parser := cda.NewParser(src, nil)
		doc, err := parser.Parse([]byte(data))
		if err != nil {
			result.Errors = append(result.Errors, err.Error())
			return result, nil
		}
		mapper := cda.NewMapper(nil)
		mapResult, err := mapper.Map(doc)
		if err != nil {
			result.Errors = append(result.Errors, err.Error())
			return result, nil
		}
		parsedEvents = mapResult.Events

	case model.SourceFormatEDI837, model.SourceFormatEDI835:
		parser := edi.NewParser()
		parseResult, err := parser.Parse(data)
		if err != nil {
			result.Errors = append(result.Errors, err.Error())
			return result, nil
		}
		// Convert EDI interchange to events using mappers
		if parseResult.Interchange != nil {
			for _, fg := range parseResult.Interchange.FunctionalGroups {
				for _, tx := range fg.Transactions {
					var evts []interface{}
					switch tx.SetIdentifier {
					case "837":
						claims, mapErr := edi.Map837ToEvents(tx, src)
						if mapErr == nil {
							for _, c := range claims {
								evts = append(evts, c)
							}
						}
					case "835":
						rems, mapErr := edi.Map835ToEvents(tx, src)
						if mapErr == nil {
							for _, r := range rems {
								evts = append(evts, r)
							}
						}
					}
					parsedEvents = append(parsedEvents, evts...)
				}
			}
		}
		for _, w := range parseResult.Warnings {
			result.Warnings = append(result.Warnings, model.ParseWarning{
				Phase:   w.Phase,
				Code:    w.Code,
				Message: w.Message,
			})
		}

	default:
		result.Errors = append(result.Errors, fmt.Sprintf("unsupported format: %s", format))
		return result, nil
	}

	// Convert to GraphQL events
	for _, evt := range parsedEvents {
		gqlEvent := convertToGraphQLEvent(evt, src, format, nil)
		if gqlEvent != nil {
			result.Events = append(result.Events, gqlEvent)
		}
	}

	result.Success = len(result.Errors) == 0
	return result, nil
}

// PatientTimeline is the resolver for the patientTimeline field.
func (r *queryResolver) PatientTimeline(ctx context.Context, mrn string, fromTimestamp *time.Time, toTimestamp *time.Time, limit *int) (*model.PatientTimeline, error) {
	limitVal := 0
	if limit != nil {
		limitVal = *limit
	}
	return r.Projections.GetPatientTimeline(mrn, fromTimestamp, toTimestamp, limitVal)
}

// EventStatistics is the resolver for the eventStatistics field.
func (r *queryResolver) EventStatistics(ctx context.Context) (*model.EventStatistics, error) {
	return r.Projections.GetEventStatistics()
}

// ActiveEncounters is the resolver for the activeEncounters field.
func (r *queryResolver) ActiveEncounters(ctx context.Context, location *string, unit *string, class *string) ([]model.ActiveEncounter, error) {
	return r.Projections.GetActiveEncounters(location, unit, class)
}

// ActiveEncounter is the resolver for the activeEncounter field.
func (r *queryResolver) ActiveEncounter(ctx context.Context, id string) (*model.ActiveEncounter, error) {
	return r.Projections.GetActiveEncounter(id)
}

// ActiveEncounterByPatient is the resolver for the activeEncounterByPatient field.
func (r *queryResolver) ActiveEncounterByPatient(ctx context.Context, mrn string) (*model.ActiveEncounter, error) {
	return r.Projections.GetActiveEncounterByPatient(mrn)
}

// ProjectionStatus is the resolver for the projectionStatus field.
func (r *queryResolver) ProjectionStatus(ctx context.Context) ([]model.ProjectionStatus, error) {
	return r.Projections.GetProjectionStatus()
}

// EventStream is the resolver for the eventStream field.
func (r *subscriptionResolver) EventStream(ctx context.Context, filter *model.EventFilter) (<-chan model.Event, error) {
	return r.Store.Subscribe(ctx, filter)
}

// WorkflowEvents is the resolver for the workflowEvents field.
func (r *subscriptionResolver) WorkflowEvents(ctx context.Context, workflowName string) (<-chan *model.WorkflowEventNotification, error) {
	ch := make(chan *model.WorkflowEventNotification, 100)

	// TODO: Hook into workflow engine for real-time notifications
	// For now, return an empty channel
	go func() {
		<-ctx.Done()
		close(ch)
	}()

	return ch, nil
}

// PatientEvents is the resolver for the patientEvents field.
func (r *subscriptionResolver) PatientEvents(ctx context.Context, mrn string) (<-chan model.Event, error) {
	return r.Store.SubscribePatient(ctx, mrn)
}

// Mutation returns graphql1.MutationResolver implementation.
func (r *Resolver) Mutation() graphql1.MutationResolver { return &mutationResolver{r} }

// Query returns graphql1.QueryResolver implementation.
func (r *Resolver) Query() graphql1.QueryResolver { return &queryResolver{r} }

// Subscription returns graphql1.SubscriptionResolver implementation.
func (r *Resolver) Subscription() graphql1.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
