#!/usr/bin/env bash
# worklog.sh — Manage the per-entry worklog under .loom/worklog/.
#
# Entries are one file each, named YYYY-MM-DD-<slug>.md, because a single
# append-only worklog conflicts on every concurrent merge: two branches adding
# an entry both touch the last line of the same file, and git cannot merge
# that. Separate files never collide.
#
# Usage:
#   bash scripts/worklog.sh new "CI benchmark gate: per-CPU thresholds"
#   bash scripts/worklog.sh render                # whole log, oldest first
#   bash scripts/worklog.sh render --newest       # newest first
#   bash scripts/worklog.sh check                 # validate naming + headings
#
# Exit codes:
#   0 — OK
#   1 — Validation failure (check), or bad usage
#   2 — Script error

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
WORKLOG_DIR="${PROJECT_ROOT}/.loom/worklog"
# Kept as a landing page for the many documents that link to it. It must never
# hold entries again — see cmd_check.
POINTER_PAGE="${PROJECT_ROOT}/.loom/50-worklog.md"

die() {
	echo "worklog: $*" >&2
	exit 2
}

usage() {
	sed -n '2,18p' "$0" | sed 's/^# \{0,1\}//'
}

# slugify turns a title into a filename-safe slug of at most 7 words.
slugify() {
	printf '%s' "$1" |
		tr '[:upper:]' '[:lower:]' |
		sed 's/[^a-z0-9]\{1,\}/-/g; s/^-//; s/-$//' |
		awk -F- '{n = (NF > 7 ? 7 : NF); for (i = 1; i <= n; i++) printf "%s%s", $i, (i < n ? "-" : "")}'
}

cmd_new() {
	local title="${1:-}"
	[ -n "$title" ] || die "new requires a title: worklog.sh new \"<title>\""

	local date slug path
	date="$(date +%F)"
	slug="$(slugify "$title")"
	[ -n "$slug" ] || die "title produced an empty slug: $title"
	path="${WORKLOG_DIR}/${date}-${slug}.md"

	if [ -e "$path" ]; then
		die "entry already exists: ${path#"${PROJECT_ROOT}"/}"
	fi

	mkdir -p "$WORKLOG_DIR"
	cat >"$path" <<EOF
### ${date} - ${title}

- What changed:
- Why:
- Evidence:
- What's next:
- Sources:
  - [S1]
EOF
	echo "${path#"${PROJECT_ROOT}"/}"
}

cmd_render() {
	local order="sort"
	[ "${1:-}" = "--newest" ] && order="sort -r"

	local files
	files="$(find "$WORKLOG_DIR" -maxdepth 1 -name '*.md' ! -name 'README.md' -type f 2>/dev/null | $order)"
	[ -n "$files" ] || die "no entries found in ${WORKLOG_DIR#"${PROJECT_ROOT}"/}"

	# This output is meant to be piped into head or less. A reader that closes
	# the pipe early must not look like a failure, so stop treating SIGPIPE and
	# the resulting write errors as fatal from here on.
	trap '' PIPE
	set +e

	echo "# Worklog"
	echo
	echo "Chronological notes while executing the plan (useful for handoffs and debugging)."
	echo
	echo "Generated by \`scripts/worklog.sh render\` — do not edit; edit the files in .loom/worklog/."
	echo

	local f
	while IFS= read -r f; do
		cat "$f"
		echo
	done <<<"$files"

	exit 0
}

cmd_check() {
	local rc=0 f base date_part heading heading_date

	[ -d "$WORKLOG_DIR" ] || die "missing ${WORKLOG_DIR#"${PROJECT_ROOT}"/}"

	while IFS= read -r f; do
		base="$(basename "$f")"
		[ "$base" = "README.md" ] && continue

		if ! printf '%s' "$base" | grep -Eq '^[0-9]{4}-[0-9]{2}-[0-9]{2}-[a-z0-9-]+\.md$'; then
			echo "FAIL $base: name must be YYYY-MM-DD-<lowercase-slug>.md" >&2
			rc=1
			continue
		fi
		date_part="${base:0:10}"

		heading="$(head -1 "$f")"
		if ! printf '%s' "$heading" | grep -Eq '^### [0-9]{4}-[0-9]{2}-[0-9]{2}'; then
			echo "FAIL $base: first line must be '### YYYY-MM-DD ...', got: $heading" >&2
			rc=1
			continue
		fi
		heading_date="$(printf '%s' "$heading" | sed -E 's/^### ([0-9]{4}-[0-9]{2}-[0-9]{2}).*/\1/')"
		if [ "$heading_date" != "$date_part" ]; then
			echo "FAIL $base: heading date $heading_date does not match filename date $date_part" >&2
			rc=1
		fi
	done < <(find "$WORKLOG_DIR" -maxdepth 1 -name '*.md' -type f | sort)

	# A second heading in one file means someone appended instead of adding a
	# new file — the exact habit this layout exists to prevent.
	while IFS= read -r f; do
		base="$(basename "$f")"
		[ "$base" = "README.md" ] && continue
		if [ "$(grep -c '^### [0-9]\{4\}-' "$f")" -gt 1 ]; then
			echo "FAIL $base: contains more than one entry heading; split it with 'worklog.sh new'" >&2
			rc=1
		fi
	done < <(find "$WORKLOG_DIR" -maxdepth 1 -name '*.md' -type f | sort)

	# The pointer page must stay a pointer. Appending an entry there is the old
	# habit, and it brings the end-of-file merge conflict straight back.
	if [ -f "$POINTER_PAGE" ] && grep -q '^#\{2,3\} [0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}' "$POINTER_PAGE"; then
		echo "FAIL ${POINTER_PAGE#"${PROJECT_ROOT}"/}: contains a dated entry heading." >&2
		echo "     That file is a pointer page, not the worklog. Every branch appends to" >&2
		echo "     its end, which is exactly the conflict .loom/worklog/ exists to remove." >&2
		echo "     Move the entry out with: bash scripts/worklog.sh new \"<title>\"" >&2
		rc=1
	fi

	if [ "$rc" -eq 0 ]; then
		echo "worklog: OK ($(find "$WORKLOG_DIR" -maxdepth 1 -name '*.md' ! -name 'README.md' -type f | wc -l | tr -d ' ') entries)"
	fi
	return "$rc"
}

case "${1:-}" in
new)
	shift
	cmd_new "$@"
	;;
render)
	shift
	cmd_render "$@"
	;;
check)
	cmd_check
	;;
-h | --help | "")
	usage
	;;
*)
	echo "worklog: unknown command: $1" >&2
	usage >&2
	exit 1
	;;
esac
